eclipse-pde/eclipse.pde

Jenkinsfile, pom.xml
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/177
Change-Id: I1c91e3a973514eb81f2a8396f2ba90e99b9e062e
=> Step 6 and Step 7 of migration of pde.ui

releng/org.eclipse.pde.ui.setup/PDE.setup
https://github.com/eclipse-pde/eclipse.pde.ui/issues/4
=> Migrate PDE.setup to use github URIs for eclipse.pde.ui

ui/org.eclipse.pde.ui.templates/plugin.properties
A quick fix to correct some spelling errors in the templates help.
=> Templates text correction

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/ClasspathHelper.java
Fixes #16 
Change-Id: I848152b9acf4be8821dd7f04dbe4af46bf0acc2c
=> Internal error exporting plug-ins or features #16

Jenkinsfile
Fixes #27 
Change-Id: I4e4de4ca56ef5877042c6b2ae96c9f5be4d9757d
=> Update Jenkins File with timestamp and JUnit reports

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/search/dialogs/FilteredPluginArtifactsSelectionDialog.java
Fixes #45 
Change-Id: I725e4f867f9d3815ebca7a824c8671636ba052d6
=> NPE when selecting feature in "Open Plug-in Artifact" menu #45

Jenkinsfile
There is Cobol source AFAICT in PDE.
Change-Id: I0b9995f145741f43e370efab1aed8726a3c79cd1
=> Get rid of acuCobol issues in Jenkinsfile

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/context/InputContextManager.java
Use Map<IEditorInput, InputContext> instead of Hashtable<IEditorInput,Object> because the value type is known and then all iterations over the map's values can be simplified.
=> Avoid the use of HashTable in InputContextManager

.mvn/extensions.xml
Part of  https://github.com/eclipse-platform/.github/issues/8
=> Update tycho-build extension to 2.7.2

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/correction/RemoveBuildEntryResolution.java
Change-Id: I7b39b6005c5787d1718745dbe2f0c4ca7d043ae0
Co-authored-by: Hannes Wellmann <wellmann.hannes1@gmx.net>
=> Make RemoveBuildEntryResolution as a multifix

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/correction/AddBuildEntrySrcExcludesResolution.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/correction/ResolutionGenerator.java
Change-Id: I4832e14c42fef6ef094a6c55b182a44e90b16b86
=> Make AddBuildEntryResolution as a multi-fix

build/org.eclipse.pde.build.tests/src/org/eclipse/pde/build/internal/tests/p2/PublishingTests.java
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/75
=> Fix failing PublishingTest in I-build

ui/org.eclipse.pde.spy.context/about.html, ui/org.eclipse.pde.spy.css/about.html, ui/org.eclipse.pde.spy.event/about.html, ui/org.eclipse.pde.spy.event/build.properties, ui/org.eclipse.pde.spy.model/about.html, ui/org.eclipse.pde.spy.preferences/about.html
=> Add about.html in o.e.pde.spy.event

ui/org.eclipse.pde.spy.model/META-INF/MANIFEST.MF, ui/org.eclipse.pde.spy.model/pom.xml
=> Version bump for 4.24 stream

ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/LaunchPluginValidator.java, ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/EclipseApplicationLaunchConfiguration.java
Dogfooding the improve JDT cleanup from Bug 572440 to ensure the JDT
cleanup is stable and functional. Push in small chunks to make review
easier.a
=> Apply Remove overridden assignment JDT clean in pde.launching

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/P2Utils.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/BuildErrorReporter.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/exports/ProductExportOperation.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/PDETextHelper.java
Dogfooding the improve JDT cleanup from Bug 572440 to ensure the JDT
cleanup is stable and functional. Push in small chunks to make review
easier.
=> Apply Remove overridden assignment JDT clean in pde.core

Jenkinsfile
And kill the previous if there is new one scheduled.
=> Only single build per branch/PR.

ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/BundleLauncherHelper.java, ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/launcher/PluginBasedLaunchTest.java
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/88
=> Don't throw NSEE for missing workspace-plugins in Launch-configs

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/commands/CommandDetails.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/contentassist/XMLCompletionProposal.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/contentassist/XMLInsertionComputer.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/BundleInputContext.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/DependencyManagementSection.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/schema/SchemaIncludesSection.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/targetdefinition/TargetEditor.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/nls/InternationalizeWizardLocalePage.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/nls/InternationalizeWizardPluginPage.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/search/ManifestEditorOpener.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/extension/BaseExtensionPointMainPage.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/extension/NewExtensionRegistryReader.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/imports/PluginImportWizardDetailedPage.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/plugin/ContentPage.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/product/ProductIntroOperation.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/target/TargetCreationPage.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/tools/ConvertPreferencesWizard.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/ui/launcher/EclipseLauncherTabGroup.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/ui/launcher/JUnitTabGroup.java
Dogfooding the improve JDT cleanup from Bug 572440 to ensure the JDT
cleanup is stable and functional. Push in small chunks to make review
easier.a
=> Apply Remove overridden assignment JDT clean in pde.ui

apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/compatibility/BundleMergeSplitTests.java, ui/org.eclipse.pde.spy.event/src/org/eclipse/pde/spy/event/internal/ui/CapturedEventTree.java
=> Work on I-build warnings and failing tests.

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/text/ManifestConfiguration.java
Fixes NPE in background thread.
=> Initialize PDEPluginImages in SWT thread. fixes #81

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/exports/ProductExportOperation.java, ui/org.eclipse.pde.core/text/org/eclipse/pde/internal/core/text/bundle/BundleModelFactory.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/correction/AddDefaultExecutionEnvironmentResolution.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/correction/Messages.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/correction/OptionalMessageDialog.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/correction/messages.properties, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/JRESection.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/exports/ExportDestinationTab.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/exports/ExportOptionsTab.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/exports/ProductDestinationGroup.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/extension/BaseExtensionPointMainPage.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/plugin/NewLibraryPluginCreationPage.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/plugin/PluginContentPage.java
Fixes #108 
Change-Id: I8577e60b3f614d52a3b5a0d84f78399fd3530d2c
=> Lot of warnings about "Non-externalized string literal"

ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/LauncherUtils.java
FYI @jhonnen, when I adapted the implementation of this test to the improved `DependencyManager`, we agreed that this test is not ideally implemented. I think this is a better solution. :)
Although I expect no noticeable performance improvement because the call will still be dominated by `DependencyManager.getSelfAndDependencies()`.
=> Minor speed-up of test if launch requires SWT

ui/org.eclipse.pde.junit.runtime/META-INF/MANIFEST.MF
Change-Id: I73e4e7b573730250212a8770f063c88b92d3e23c
=> update version of pde.junit.runtime

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/RemoteTargetHandle.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/EditTargetContainerPage.java
as a location URI in  the 'Create target reference' page
Also provide choices of available workspace *.target files in the
drop-down of the 'Create target reference' page
https://github.com/eclipse-pde/eclipse.pde/issues/121
=> Ensure that file:${project_loc:/project}/my.target validates on Windows

features/org.eclipse.pde-feature/feature.xml, ui/org.eclipse.pde/META-INF/MANIFEST.MF, ui/org.eclipse.pde/pom.xml
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/313
=> Version updates for 4.25

build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java
Change-Id: I37597e541cd398d004602288fe4652a622fa69a3
=> [19] Ensure PDE export works OK for a plugin project with Java 19

ui/org.eclipse.pde.genericeditor.extension.tests/META-INF/MANIFEST.MF, ui/org.eclipse.pde.genericeditor.extension.tests/pom.xml, ui/org.eclipse.pde.genericeditor.extension.tests/src/org/eclipse/pde/genericeditor/extension/tests/UpdateUnitVersionsCommandTests.java
Unstable test so first round of cleanups to it.
* Use Map.of
* Remove useless cast
=> Cosmetics to UpdateUnitVersionsCommandTests

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetReferenceBundleContainer.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/AddBundleContainerSelectionPage.java
Don't add duplicate locations in the target editor( fixes #183)
Change-Id: Icabab6136ddddf13b61eda762f2f9ef5a18e1db0
=> Don't add duplicate locations in the target editor ( fixes #183)

ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/PDEMessages.java, ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/BundleLauncherHelper.java, ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/pderesources.properties
Skipping features with null id prevents subsequent NPEs.
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/185
@laeubi what do you think?
=> Skip and warn features without Id when launching

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/AbstractPluginBlock.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/PluginStatusDialog.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/PluginValidationStatusHandler.java
Workaround for Validation error when launching child eclipse
Change-Id: Icfa7b40456e97444655aeec7aa6a8a4ac418e803
=> Workaround for Validation error when launching child eclipse( fixes #194)

features/org.eclipse.pde.unittest.junit-feature/feature.xml, features/org.eclipse.pde.unittest.junit-feature/pom.xml, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsClasspathContainer.java, ui/org.eclipse.pde.junit.runtime.tests/META-INF/MANIFEST.MF, ui/org.eclipse.pde.junit.runtime.tests/pom.xml, ui/org.eclipse.pde.junit.runtime.tests/src/org/eclipse/pde/junit/runtime/tests/JUnit5SuiteExecutionTest.java, ui/org.eclipse.pde.junit.runtime.tests/test-bundles/verification.tests.junit4.platform/META-INF/MANIFEST.MF, ui/org.eclipse.pde.junit.runtime.tests/test-bundles/verification.tests.junit5.suite/META-INF/MANIFEST.MF, ui/org.eclipse.pde.junit.runtime.tests/test-bundles/verification.tests.junit5/META-INF/MANIFEST.MF, ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/JUnitLaunchConfigurationDelegate.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/correction/java/JavaResolutionFactory.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/correction/java/UnresolvedImportFixProcessor.java, ui/org.eclipse.pde.unittest.junit/META-INF/MANIFEST.MF, ui/org.eclipse.pde.unittest.junit/pom.xml, ui/org.eclipse.pde.unittest.junit/src/org/eclipse/pde/unittest/junit/launcher/JUnitPluginLaunchConfigurationDelegate.java
This will make adoption of JUnit 5 from Maven Central easier.
=> Use JUnit from Maven Central

ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/LaunchValidationOperation.java
Change-Id: I71489bec44c57e1aa608adb2f031ba18cb7af3bf
Also-by: Hannes Wellmann <wellmann.hannes1@gmx.net>
=> Backport validation error in 4.23

ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/LauncherUtils.java
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/238
=> Don't fail with NPE if "org.eclipse.swt" is not in the target platform

ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/classpathcontributor/ClasspathContributorTest.java
Fix https://github.com/eclipse-pde/eclipse.pde/issues/243
=> Adjust ClasspathContributorTest for new annotations

ui/org.eclipse.pde.ui.templates/templates_3.5/E4Application/$pluginId$.product
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/262
=> Adjust Apache Commons IO bundle name to the upstream one.

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiAnalysisApplication.java
Currently the ApiAnalysisApplication uses the toString representation of
the marker this has some drawbacks:
- it is unclear how it looks like as toString has only weak semantics
- it is very hard to read by the user
- it is very hard to reliable parse by tools
This changes the output to the following format:
`[SERVERITY] File FILENAME at line LINENUMBER: MESSAGE (location: PATH)`
This will fix https://github.com/eclipse-pde/eclipse.pde/issues/217 and fix https://github.com/eclipse-pde/eclipse.pde/issues/216
=> Format the output of markers of the ApiAnalysisApplication

ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/classpathcontributor/ClasspathContributorTest.java
Fix https://github.com/eclipse-pde/eclipse.pde/issues/272
=> Add org.osgi.service.component.annotations to the allowed Classpath

ui/org.eclipse.pde.genericeditor.extension.tests/src/org/eclipse/pde/genericeditor/extension/tests/Bug527084CompletionWithCommentsTest.java, ui/org.eclipse.pde.genericeditor.extension.tests/src/org/eclipse/pde/genericeditor/extension/tests/TagNameCompletionTests.java, ui/org.eclipse.pde.genericeditor.extension/META-INF/MANIFEST.MF, ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/autocomplete/processors/TagCompletionProcessor.java, ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/command/UpdateUnitVersions.java, ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/model/DependencyNode.java, ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/model/ITargetConstants.java, ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/model/xml/Parser.java, ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/reconciler/folding/FoldingReconcilerStrategy.java, ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/reconciler/presentation/TargetPlatformAttributeRule.java, ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/reconciler/presentation/TargetPlatformTagRule.java
Handles coloring and completion.
Tests are adjusted accordingly.
=> Update *.target editor to support Maven artifacts

build/org.eclipse.pde.build/META-INF/MANIFEST.MF, build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java
=> get latest java version dynamically

.github/workflows/build.yml
See https://github.com/actions/upload-artifact/issues/240
FYI @vogella
=> Disable artifact upload for windows due to actions/upload-artifact#240

build/org.eclipse.pde.build/src_ant/org/eclipse/pde/internal/build/tasks/BuildScriptGeneratorTask.java, build/org.eclipse.pde.build/src_ant/org/eclipse/pde/internal/build/tasks/FeatureGeneratorTask.java, build/org.eclipse.pde.build/src_ant/org/eclipse/pde/internal/build/tasks/FetchFileGeneratorTask.java, build/org.eclipse.pde.build/src_ant/org/eclipse/pde/internal/build/tasks/FetchTask.java, build/org.eclipse.pde.build/src_ant/org/eclipse/pde/internal/build/tasks/PackagerTask.java, build/org.eclipse.pde.build/src_ant/org/eclipse/pde/internal/build/tasks/TaskHelper.java, build/org.eclipse.pde.build/src_ant/org/eclipse/pde/internal/build/tasks/UnzipperGeneratorTask.java, ui/org.eclipse.pde.core/src_ant/org/eclipse/pde/internal/core/ant/TargetPlatformProvisionTask.java
This could help to solve https://github.com/eclipse-pde/eclipse.pde/issues/189.
=> Improve error reporting of PDE's ANT-tasks

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/LaunchAction.java
https://github.com/eclipse-pde/eclipse.pde/issues/298
=> Ensure that adding userArgs to the launcher's initialArgs works properly

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/LaunchAction.java
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/316
This is a regression from https://github.com/eclipse-pde/eclipse.pde/pull/288.
=> Fix regression in LaunchAction.concatArgs

apitools/org.eclipse.pde.api.tools.tests/pom.xml, apitools/pom.xml, build/pom.xml, ds/pom.xml, pom.xml, ua/org.eclipse.pde.ua.tests/pom.xml, ua/pom.xml, ui/org.eclipse.pde.genericeditor.extension.tests/pom.xml, ui/org.eclipse.pde.junit.runtime.tests/pom.xml, ui/org.eclipse.pde.ui.templates.tests/pom.xml, ui/org.eclipse.pde.ui.tests.smartimport/pom.xml, ui/org.eclipse.pde.ui.tests/pom.xml, ui/org.eclipse.pde/pom.xml, ui/pom.xml
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/514
=> Opening of 4 26 stream for development

apitools/org.eclipse.pde.api.tools/META-INF/MANIFEST.MF, features/org.eclipse.pde-feature/feature.xml, ui/org.eclipse.pde/META-INF/MANIFEST.MF, ui/org.eclipse.pde/pom.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/540
=> Version bumps for 4.26 stream

build/org.eclipse.pde.build/META-INF/MANIFEST.MF, build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java, ui/org.eclipse.pde.core/META-INF/MANIFEST.MF, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/TargetPlatformHelper.java
JavaRuntime.getExecutionEnvironmentsManager().getEnvironment(execEnvID) may return null
=> Avoid NPE if JRE is missing #341

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetDefinition.java
Improves code, and hopefully fixes
https://github.com/eclipse-pde/eclipse.pde/issues/347
=> Improve equals computation in TargetDefinition

ui/org.eclipse.pde.ui/forceQualifierUpdate.txt
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/383
=> Touch org.eclipse.pde.ui to fix comparator errors

apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/compatibility/BundleMergeSplitTests.java
It failed in I20221108-1800 cen64-gtk3-java19 run and this commit it just minor code improvements while trying to figure what's going wrong.
=> Minor edits to BundleMergeSplitTests

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/WorkspacePluginModelManager.java
* Use Set.of instead of the complex way
* use if(!condition) instead of if (condition == false)
=> Minor code improvements to WorkspacePluginModelManager

apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/ApiBuilderTest.java
=> Use varargs in parent test classes

apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/util/tests/ApiBaselineManagerTests.java
Done instead of touching bundle for
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/667
=> Improve asserts in ApiBaselineManagerTests

apitools/org.eclipse.pde.api.tools.tests/pom.xml, apitools/pom.xml, build/pom.xml, ds/pom.xml, pom.xml, ua/org.eclipse.pde.ua.tests/pom.xml, ua/pom.xml, ui/org.eclipse.pde.genericeditor.extension.tests/pom.xml, ui/org.eclipse.pde.junit.runtime.tests/pom.xml, ui/org.eclipse.pde.ui.templates.tests/pom.xml, ui/org.eclipse.pde.ui.tests.smartimport/pom.xml, ui/org.eclipse.pde.ui.tests/pom.xml, ui/org.eclipse.pde/pom.xml, ui/pom.xml
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/712
=> POM and product version changes for 4.27 release

apitools/org.eclipse.pde.api.tools/META-INF/MANIFEST.MF, features/org.eclipse.pde-feature/feature.xml, ui/org.eclipse.pde/META-INF/MANIFEST.MF, ui/org.eclipse.pde/pom.xml
=> Comparator issues in I20221130-1800

apitools/org.eclipse.pde.api.tools.tests/META-INF/MANIFEST.MF, apitools/org.eclipse.pde.api.tools.tests/pom.xml, apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/util/tests/UtilTests.java
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/748.
=> Migrate to javax.servlet.jsp-api from Maven-Central

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/MinimalState.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/TargetPlatformHelper.java, ui/org.eclipse.pde.launching/META-INF/MANIFEST.MF, ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/LaunchValidationOperation.java, ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/ProductValidationOperation.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/preferences/TargetPlatformPreferencePage.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/StyledBundleLabelProvider.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/TargetLocationContentProvider.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/target/EditTargetDefinitionWizard.java
Does anybody want to review this?
=> Miscellaneous clean-ups and minor code improvements.

apitools/org.eclipse.pde.api.tools.ui/META-INF/MANIFEST.MF, apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/markers/ApiQuickFixProcessor.java, apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/markers/ConfigureProblemSeverityForAPIToolsResolution.java, apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/markers/DefaultApiProfileResolution.java, apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/markers/OpenPropertyPageResolution.java, apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/markers/ProblemExplainIncompatibilityResolution.java, apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/markers/SinceTagResolution.java, apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/use/ApiUseScanJob.java, apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/wizards/ApiToolingSetupWizardPage.java, ui/org.eclipse.pde.runtime/META-INF/MANIFEST.MF, ui/org.eclipse.pde.runtime/src/org/eclipse/pde/internal/runtime/registry/RegistryBrowserModelChangeListener.java, ui/org.eclipse.pde.ui.tests/META-INF/MANIFEST.MF, ui/org.eclipse.pde.ui.tests/pom.xml, ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/PDETestCase.java, ui/org.eclipse.pde.ui/META-INF/MANIFEST.MF, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/DependencyManagementSection.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ImportPackageSection.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/OverviewPage.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/RequiresSection.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/targetdefinition/TargetEditor.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/preferences/TargetPlatformPreferencePage.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/TargetLocationsGroup.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/TargetStatus.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/imports/PluginImportOperation.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/target/TargetDefinitionContentPage.java
The factory was introduce in https://github.com/eclipse-platform/eclipse.platform.ui/pull/387.
=> Use new static factory method to create UIJobs

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/RequiresSection.java
=> fix NPE in RequiresSection #190

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/targetdefinition/TargetEditorContributor.java
Code commented out in 2009, time to delete it.
=> Removes dead code from TargetEditorContributor

ui/org.eclipse.pde.ui.templates/templates_3.5/E4View/fragment.e4xmi
The currently contributed part is not closable which is not a typical
behavior for contributed parts.
=> Make the e4 view created by PDE template closable

ui/org.eclipse.pde.spy.bundle/.project, ui/org.eclipse.pde.spy.context/.project, ui/org.eclipse.pde.spy.core/.project, ui/org.eclipse.pde.spy.css/.project, ui/org.eclipse.pde.spy.event/.project, ui/org.eclipse.pde.spy.model/.project, ui/org.eclipse.pde.spy.preferences/.project
=> Enable Api analysis in the new plugins

Jenkinsfile
=> Build with Temurin JVM

apitools/org.eclipse.pde.api.tools.tests/build.properties
=> Add newly added test resources to build.properties

apitools/org.eclipse.pde.api.tools.tests/pom.xml, apitools/pom.xml, build/pom.xml, ds/pom.xml, pom.xml, ua/org.eclipse.pde.ua.tests/pom.xml, ua/pom.xml, ui/org.eclipse.pde.genericeditor.extension.tests/pom.xml, ui/org.eclipse.pde.junit.runtime.tests/pom.xml, ui/org.eclipse.pde.ui.templates.tests/pom.xml, ui/org.eclipse.pde.ui.tests.smartimport/pom.xml, ui/org.eclipse.pde.ui.tests/pom.xml, ui/org.eclipse.pde/pom.xml, ui/pom.xml
@akurtakov FYI it seems I have had to create the PR manually as automatic creation failed with:
```
Create or update the pull request
Attempting creation of pull request
Error: GitHub Actions is not permitted to create or approve pull requests.
```
maybe the eclipse-releng bot needs additional permissions?
=> Update for release 4.28

ui/org.eclipse.pde.launching/forceQualifierUpdate.txt
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/947
=> Comparator errors in I20230307-0840

features/org.eclipse.pde-feature/feature.xml, ui/org.eclipse.pde.launching/META-INF/MANIFEST.MF, ui/org.eclipse.pde/META-INF/MANIFEST.MF, ui/org.eclipse.pde/pom.xml
Tracked by
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/917
=> Version bumps for 4.28 stream

apitools/org.eclipse.pde.api.tools.ui/META-INF/MANIFEST.MF, apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/wizards/JavadocConversionRefactoring.java, apitools/org.eclipse.pde.api.tools/META-INF/MANIFEST.MF, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/JavadocTagManager.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/ApiAnalysisBuilder.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/BaseApiAnalyzer.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/provisional/scanner/TagScanner.java, ds/org.eclipse.pde.ds.annotations.tests/src/org/eclipse/pde/ds/internal/annotations/tests/AllDSAnnotationsTests.java, ds/org.eclipse.pde.ds.annotations.tests/src/org/eclipse/pde/ds/internal/annotations/tests/ManagedProjectTest.java, ds/org.eclipse.pde.ds.annotations/META-INF/MANIFEST.MF, ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/AnnotationVisitor.java, ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/DSEnums.java, ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/ProjectState.java, ui/org.eclipse.pde.core/META-INF/MANIFEST.MF, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsClasspathContainer.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/BuildErrorReporter.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/BundleErrorReporter.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/exports/FeatureExportOperation.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/exports/ProductExportOperation.java, ui/org.eclipse.pde.ui.templates/META-INF/MANIFEST.MF, ui/org.eclipse.pde.ui.templates/templates_3.1/helloOSGiService/java/DictionaryImpl.java, ui/org.eclipse.pde.ui.templates/templates_3.1/helloOSGiServiceComponent/java/DictionaryImpl.java, ui/org.eclipse.pde.ui.tests/META-INF/MANIFEST.MF, ui/org.eclipse.pde.ui.tests/pom.xml, ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/imports/ImportFeatureProjectsTestCase.java, ui/org.eclipse.pde.ui/META-INF/MANIFEST.MF, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/product/ProductFromConfigOperation.java
Searched for ".unmodifiable(" and "Arrays.asList(" to find suitable applications.
=> Use static Collection factories

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PDEState.java
Currently the comparator in PDEState vialoates the transitive contract of compare in the follwoing situation:
- There are two bundles of different versions with the same bsn and they both export the same package
- There is another bundle with a different bsn and it also export the package
This leads to the follwoing problem:
The two bundles with the same BSN are always compared with their version, but the other bundle is compared against the two ones using the bundle id.
That leads to the situation that if these three bundles are A, B, C that A > B and B > C but A <= C
This changes the compare function to always compare the version of the supplier, what gives a predictable order of A, B, C and only if BSN is equal AND version is equal finally the bundle id is used to impose a total order. …
=> Fix ordering problem in PDEState

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiAnalysisApplication.java
Currently the ApiAnalysisApplication only accepts atarget that then is resolved and afterwards transformed in a list of files.
This change add support for passing a list of bundles directly to prevent this kind of indirection and save workload if the caller already knows the list of bundles (e.g. Tycho).
=> Add support for loading the baseline from a file that list bundles

ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/project/ProjectCreationTests.java
See https://github.com/eclipse-pde/eclipse.pde/issues/523
=> Close streams opened by ProjectCreationTests.testHeaderFormatting()

ui/org.eclipse.pde.core/META-INF/MANIFEST.MF, ui/org.eclipse.pde.core/build.properties, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PDECore.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndResourceChangeListener.java
As described here: 
- https://github.com/eclipse-pde/eclipse.pde/pull/536#issuecomment-1489733174
FYI @iloveeclipse
=> Register listener in activator to avoid start order dependency with JDT

ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/launcher/PluginBasedLaunchTest.java
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/480.
In PluginBasedLaunchTest the test cases
- testTwoVersionsOfSameBundleBundlesInfo
- testTwoVersionsOfSameBundleConfigIni
failed on Windows (and probably similar on Mac) because the URL/URI value of the '-configuration' program argument is not correctly build. On windows it is something similiar to 'file:C:/path1/path2/' while it should be 'file:///C:/path1/path2/'.
This makes the test case resilient against this kind of malformed URL/URIs.
It is great that we now build on all platforms, which should prevent such failures in the future.
This also reminds me about https://github.com/eclipse-platform/eclipse.platform/issues/35.
=> Fix 'URI is not hierarchical' failure in PluginBasedLaunchTest

ui/org.eclipse.pde.ui/plugin.properties, ui/org.eclipse.pde.ui/plugin.xml
Onboarding image will be added via separate commit. For #557
=> Add minimalistic PDE onboarding properties.

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/AbstractModel.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PDECore.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/WorkspaceModelManager.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/DependencyLoopFinder.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/project/BundleProjectService.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/IUBundleContainer.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/ManifestUtils.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/PDEXMLHelper.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/XMLComponentRegistry.java, ui/org.eclipse.pde.core/src_ant/org/eclipse/pde/internal/core/ant/ConvertSchemaToHTML.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/contentassist/XMLCompletionProposal.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/TargetContentsGroup.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/util/ExtensionsFilterUtil.java, ui/org.eclipse.ui.trace/src/org/eclipse/ui/trace/internal/TracingPreferencePage.java
See https://github.com/eclipse-platform/eclipse.platform/issues/444
=> Fix for "Redundant specification of type arguments" error

apitools/org.eclipse.pde.api.tools.tests/pom.xml, apitools/pom.xml, build/pom.xml, ds/pom.xml, pom.xml, ua/org.eclipse.pde.ua.tests/pom.xml, ua/pom.xml, ui/org.eclipse.pde.genericeditor.extension.tests/pom.xml, ui/org.eclipse.pde.junit.runtime.tests/pom.xml, ui/org.eclipse.pde.ui.templates.tests/pom.xml, ui/org.eclipse.pde.ui.tests.smartimport/pom.xml, ui/org.eclipse.pde.ui.tests/pom.xml, ui/org.eclipse.pde/pom.xml, ui/pom.xml
tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1100
=> POM and product version changes for 4.29 release

features/org.eclipse.pde-feature/feature.xml, ui/org.eclipse.pde/META-INF/MANIFEST.MF, ui/org.eclipse.pde/pom.xml
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1125
=> Version bumps for 4.29 stream

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/BaseApiAnalyzer.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/BuildState.java, apitools/org.eclipse.pde.api.tools/src_ant/org/eclipse/pde/api/tools/internal/tasks/AnalysisReportConversionTask.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/PDEStorageDocumentProvider.java
This change does not try to fix anything. Just reduces code.
=> Use try-with-resource

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/comparator/Delta.java
Did use identity hashcode.
see https://rules.sonarsource.com/java/RSPEC-2116
=> fix org.eclipse.pde.api.tools.internal.comparator.Delta.hashCode()

ds/org.eclipse.pde.ds.ui/META-INF/MANIFEST.MF, ds/org.eclipse.pde.ds.ui/src/org/eclipse/pde/internal/ds/ui/wizards/DSCreationOperation.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/ManifestConsistencyChecker.java, ui/org.eclipse.pde.ui.templates/META-INF/MANIFEST.MF, ui/org.eclipse.pde.ui.templates/templates_3.1/helloOSGiService/java/DictionaryImpl.java, ui/org.eclipse.pde.ui.templates/templates_3.1/helloOSGiServiceComponent/java/DictionaryImpl.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/commands/CommandTreeContentProvider.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/BundleSourcePage.java
=> Add missing "static" modifier for constants

apitools/org.eclipse.pde.api.tools.ui/META-INF/MANIFEST.MF, apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/actions/ExportDialog.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/util/Util.java, ui/org.eclipse.pde.core/text/org/eclipse/pde/internal/core/text/build/Build.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/search/ExtensionsPatternFilter.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/extension/PointSelectionPage.java
To avoid calculation on right side.
=> Use short-circuit logic

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bundle/BundlePluginBase.java
Codereview: Loop would throw IndexOutOfBoundsException
=> BundlePluginBase: fix wrong loop

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
See https://github.com/eclipse-pde/eclipse.pde/issues/307
=> Fix NLS missing message: MainPreferencePage_RunAPIAnalysisBuilderAsJob

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ManifestEditor.java
With https://github.com/eclipse-pde/eclipse.pde/pull/604 the zip-file of an external Plugin is closed when being opened in the Manifest-Editor, but the closing of that file must not happen before the Editor is full opened and all content is read. Otherwise a "zip file closed" exception is thrown and the Editor can only show that exception.
Besides fixing the mentioned issue, other ZipFiles are also closed via a try-with-resources block.
FYI @jukzi
=> Fix "zip file closed" exception when opening Bundles from the TP

ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/launcher/AllLauncherTests.java, ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/launcher/product/ProductEditorLaunchingTest.java
... and rename it to a more usual schema.
=> Run 'ProductEditorLaunchingTest' in verification builds

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/util/TarFile.java
https://rules.sonarsource.com/java/RSPEC-4517
=> fix TarFile.TarInputStream.read() to return unsigned byte

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndProjectManager.java
Processor is a Closeable that was not closed.
=> BndProjectManager: close Processor

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/CopyLocationAction.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/Messages.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/TargetContentsGroup.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/TargetLocationsGroup.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/messages.properties, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/views/target/StateViewPage.java
https://github.com/eclipse-pde/eclipse.pde/issues/676
=> Support copying the location of a bundle or feature to the clipboard

ds/org.eclipse.pde.ds.core/src/org/eclipse/pde/internal/ds/core/builders/DSBuilder.java, ds/org.eclipse.pde.ds.core/src/org/eclipse/pde/internal/ds/core/builders/DSErrorReporter.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/XMLDefaultHandler.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/IncrementalErrorReporter.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/XMLErrorReporter.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/plugin/PluginHandler.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/IUBundleContainer.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/RepositoryBundleContainer.java, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetDefinition.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/exports/FeatureExportWizard.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/exports/PluginExportWizard.java
and apply a few simplifications.
=> Restore usage of a specific 'Declarative Services Problem' marker

build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/717
Since this is a fix for a regression, it should be merged for RC1.
I plan to merge this latest today (Wednesday) evening.
=> Suppress warning about no JRE-packages if no compatible VM is available

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ApiBaseline.java
https://github.com/eclipse-pde/eclipse.pde/issues/689
=> fix NPE in ApiBaseline.initialize #689

apitools/org.eclipse.pde.api.tools.tests/pom.xml, apitools/pom.xml, build/pom.xml, ds/pom.xml, pom.xml, ua/org.eclipse.pde.ua.tests/pom.xml, ua/pom.xml, ui/org.eclipse.pde.genericeditor.extension.tests/pom.xml, ui/org.eclipse.pde.junit.runtime.tests/pom.xml, ui/org.eclipse.pde.ui.templates.tests/pom.xml, ui/org.eclipse.pde.ui.tests.smartimport/pom.xml, ui/org.eclipse.pde.ui.tests/pom.xml, ui/org.eclipse.pde/pom.xml, ui/pom.xml
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1289
=> POM and product version changes for 4.30 release

apitools/org.eclipse.pde.api.tools/forceQualifierUpdate.txt
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1318
=> Comparator errors in I20230906-0400

apitools/org.eclipse.pde.api.tools/META-INF/MANIFEST.MF
Continuation of https://github.com/eclipse-pde/eclipse.pde/pull/737
=> Version bumps for 4.30 stream

apitools/org.eclipse.pde.api.tools/forceQualifierUpdate.txt, ui/org.eclipse.pde.spy.preferences/forceQualifierUpdate.txt, ui/org.eclipse.pde.ui.templates/forceQualifierUpdate.txt, ui/org.eclipse.pde.ui.tests/forceQualifierUpdate.txt
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1378
=> Touch bundles affected by changed bytecode generation

build/README.md
=> Fix Headline and add info of support options for migration

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/BundleComponent.java
throws ZipException on zip slip
=> BundleComponent clean up

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndBuilder.java
The ProjectBuilder currently uses the output folder of a project as an additional classpath jar, this then can even confuse BND as it thinks we have a split package and try to copy that class into the jar itself.
This extends the default ProjectBuilder, check if the jar is sourced at the output location and then skip adding the jar.
=> Fix using the outputfolder as a classpath jar

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetDefinition.java
Currently the flow of action is quite hard to understand, also synchronizers are performed first and can stop resolving other locations even if these do not fail.
This changes it in a way where we first collect all synchronizers but perform any other location resolving first. Then all remaining items are resolved and added to the status that is then finally resolved to include all target states.
@merks @HannesWell this is a prerequisite for making 
- https://github.com/eclipse-pde/eclipse.pde/pull/792
work more smooth, also it is now much more clear what happens when...
=> Rework TargetDefinition#resolve

ds/org.eclipse.pde.ds.ui/forceQualifierUpdate.txt, ua/org.eclipse.pde.ua.ui/forceQualifierUpdate.txt
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1480
=> Touch bundles affected by the signature change in MultiSourceEditor

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ExportPackageVisibilitySection.java
Fix https://github.com/eclipse-pde/eclipse.pde/issues/664
=> Prevent NPE where model is null

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/MinimalState.java
Relates to https://github.com/eclipse-pde/eclipse.pde/pull/849
=> Extract IPluginModelBase.getInstallLocation() expression in MinimalState

features/org.eclipse.pde-feature/feature.xml, features/org.eclipse.pde.spies-feature/feature.xml, features/org.eclipse.pde.unittest.junit-feature/feature.xml
Apply the result of https://github.com/eclipse-pde/eclipse.pde/issues/730 to PDE.
=> Remove unnecessary attributes from PDE's feature.xml

Jenkinsfile
This doesn't fix the problem, but may be gives some hints
See https://github.com/eclipse-pde/eclipse.pde/issues/888
=> Enable tycho.apitools.debug & disable DetectVMInstallationsJob

Jenkinsfile
Reverts eclipse-pde/eclipse.pde#889 since #888 is fixed.
=> Revert "Enable tycho.apitools.debug & disable DetectVMInstallationsJob"

ui/org.eclipse.pde.ui.tests/pom.xml, ui/org.eclipse.pde.ui.tests/tests/projects/classpathupdater/META-INF/MANIFEST.MF
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/764
=> Specify BREE of test-project of ClasspathUpdaterTest

releng/org.eclipse.pde.setup/PDE.setup
https://github.com/eclipse-jdt/eclipse.jdt/issues/79
=> Encourage rebase on forks by configuring the clone default for that

build/org.eclipse.pde.build.tests/src/org/eclipse/pde/build/internal/tests/ScriptGenerationTests.java
Adopted test expectations
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/884
=> Fix for ScriptGenerationTests.testBug156043()

features/org.eclipse.pde-feature/feature.xml, ui/org.eclipse.pde/META-INF/MANIFEST.MF, ui/org.eclipse.pde/pom.xml
Tracked in eclipse-platform/eclipse.platform.releng.aggregator#1590
=> Version bumps for 4.31 stream

apitools/org.eclipse.pde.api.tools.tests/pom.xml, ua/org.eclipse.pde.ua.tests/pom.xml, ui/org.eclipse.pde.genericeditor.extension.tests/pom.xml, ui/org.eclipse.pde.junit.runtime.tests/pom.xml, ui/org.eclipse.pde.ui.templates.tests/pom.xml, ui/org.eclipse.pde.ui.tests/pom.xml
This fixes a warning at each of the remove elements.
=> Remove inherited (and therefore unnecessary) elements in pom.xml files

ui/org.eclipse.pde.core/META-INF/MANIFEST.MF
See https://github.com/eclipse-pde/eclipse.pde/pull/940
=> Fix API error on unneeded version bump

README.md
See https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4016
=> Add sponsoring info for SAP

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/AbstractPluginBlock.java
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/649
=> Disposing the editor in tree viewer.

Jenkinsfile
FYI @jukzi @vogella @akurtakov
=> Enable the Quality Gate

ui/org.eclipse.pde.bnd.ui/build.properties
Hopefully fix https://github.com/eclipse-pde/eclipse.pde/issues/968
=> add about.html to source build

ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/AnnotationVisitor.java
Currently for a class used in component property types the property looks like MyClass.class where according to the spec it should be a string holding the class name, also empty arrays result in a property with no value in the xml while the spec says it should be omitted,
This is now fixed, empty properties are only removed and Types are resolved to their type name from now on.
See also https://github.com/osgi/osgi/issues/646
=> Fix handling of class types and empty array in component property types

ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/AnnotationVisitor.java
Fix https://github.com/eclipse-pde/eclipse.pde/issues/973
=> Constant expressions must be resolved for component property types

ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/DSAnnotationPropertyPage.java
Fix https://github.com/eclipse-pde/eclipse.pde/issues/972
=> Fix wrong constant in drop down

ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/ReferenceProcessor.java
Initiated by https://download.eclipse.org/eclipse/downloads/drops4/I20231212-1800/compilelogs/plugins/org.eclipse.pde.ds.annotations_1.3.200.v20231203-1627/@dot.html
=> DS ReferenceProcessor warning fixes

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/FilterStore.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/AbstractProblemDetector.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/ReferenceExtractor.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/provisional/Factory.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/search/UseScanManager.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/search/UseScanParser.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/util/Util.java, apitools/org.eclipse.pde.api.tools/src_ant/org/eclipse/pde/api/tools/internal/tasks/APIToolsAnalysisTask.java, apitools/org.eclipse.pde.api.tools/src_ant/org/eclipse/pde/api/tools/internal/tasks/MissingRefProblemsTask.java, ui/org.eclipse.pde.spy.bundle/META-INF/MANIFEST.MF, ui/org.eclipse.pde.spy.bundle/src/org/eclipse/pde/spy/bundle/internal/BundleDataProvider.java
* Use simplified lambda syntax
* Use Collection.isEmpty
* Fix broken @see tag
* Use pattern matching
* Use try-with-resources
* Use StandardCharsets
* Immediate return
Complains from sonarlint in my workspace
=> Various cleanups

ds/org.eclipse.pde.ds.tests/forceQualifierUpdate.txt, ua/org.eclipse.pde.ua.tests/forceQualifierUpdate.txt, ui/org.eclipse.pde.junit.runtime/forceQualifierUpdate.txt, ui/org.eclipse.pde.unittest.junit/forceQualifierUpdate.txt, ui/org.eclipse.ui.trace/forceQualifierUpdate.txt
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1659
@iloveeclipse Please check
=> Touch bundles affected by the changed compilation settings

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/product/BaseProductCreationOperation.java
Use Integer.parseInt(slinfo[0]) instead of
Integer.valueOf(slinfo[0]).intValue());
=> Use parseInt in BaseProductCreationOperation

features/org.eclipse.pde-feature/feature.xml
=> Add bnd templates template to feature

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ApiBaseline.java
An attempt to reduce the probability of errors while API baseline is being updated due the JVM change.
- Move rebindVM() to a job and let it wait for pending API analysis jobs
- changed most of internal maps/lists to concurrent versions
- made initialize() synchronized
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/1042
=> NPE in ApiBaseline on adding new JVM

ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/views/log/LogEntryTest.java
See https://github.com/eclipse-platform/eclipse.platform.ui/pull/1493
=> Update exception signature change in LogEntry tests

apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/leak/ClassImplementsLeak.java, apitools/org.eclipse.pde.api.tools.tests/test-builder/leak/class/test37.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/LeakImplementsProblemDetector.java
https://github.com/eclipse-pde/eclipse.pde/discussions/1064
=> A noextend API class that implements noimplement interface isn't a leak

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java
Currently access to the profile field is scattered around in the P2TargetUtils class leading to the unfortunate situation that it might be null or inconsistent.
This makes the following changes:
- synchronize all methods that modify the field
- never read the filed but get a profile passed as a parameter
=> Sync on profile field in P2TargetUtils

apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/problems/tests/ApiProblemTests.java, apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/search/tests/UseSearchTests.java, apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/preferences/ApiBaselinePreferencePage.java, apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/preferences/ApiBaselinesConfigurationBlock.java, apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/refactoring/FilterRenameParticipant.java, apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/refactoring/RefactoringUtils.java, apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/use/ApiUseScanTab.java, apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/use/DescriptionPatternPage.java, apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/use/PatternWizard.java, apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/use/UsePatternPage.java, apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/wizards/CompareOperation.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/AnyValue.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiDescription.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/BaseApiAnalyzer.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/ProblemDetectorBuilder.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/ReferenceAnalyzer.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/ReferenceResolver.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/comparator/ClassFileComparator.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ApiBaseline.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ApiType.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/BundleComponent.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/TypeStructureBuilder.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/problems/ApiProblem.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/problems/ApiProblemFactory.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/provisional/comparator/ApiComparator.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/provisional/model/ApiScopeVisitor.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/provisional/model/ApiTypeContainerVisitor.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/provisional/search/ApiSearchEngine.java
reduces warnings and removes dead code
=> fix "The value of the parameter is not used"

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/category/CategorySection.java, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/site/CategorySection.java
"The variable item cannot be null at this location"
=> fix Redundant null check

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/AnyValue.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ApiBaseline.java
https://github.com/eclipse-pde/eclipse.pde/issues/1073
=> Restore the AnyValue(String) constructor to support filter wildcards

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PreferenceInitializer.java
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/1082
=> Restore RUN_API_ANALYSIS_AS_JOB default value

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiBaselineManager.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/ApiAnalysisBuilder.java
Makes workspace baseline disposal task to job and makes sure it doesn't run in parallel with API analysis jobs.
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/1088
=> Deadlock in API tooling after removing projects from workspace

ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/LaunchListener.java
https://github.com/eclipse-equinox/p2/issues/166
=> Handle return value 24 the same as 23

ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/LaunchListener.java
This reverts commit e41959b261bcf067243f292639bf2811072b901d.
=> Revert "Handle return value 24 the same as 23"

build/org.eclipse.pde.build.tests/pom.xml
https://github.com/eclipse-platform/eclipse.platform.ui/issues/1628
=> remove ignoredWarnings

releng/org.eclipse.pde.setup/PDE.setup
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1612
=> uniformly use 4GB Heap on Workspace

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/bndtools/BndCompletionProcessor.java
Fix https://github.com/eclipse-pde/eclipse.pde/issues/1138
=> Apply the changes in the SWT thread of the text widget

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/context/InputContextManager.java
https://github.com/eclipse-pde/eclipse.pde/issues/1129
=> InputContextManager.save(): split monitor #1129

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/preferences/TargetPlatformPreferencePage.java
https://github.com/eclipse-pde/eclipse.pde/issues/432
=> TargetPlatformPreferencePage: fix "Widget is disposed" #432

apitools/org.eclipse.pde.api.tools.tests/pom.xml, apitools/pom.xml, build/org.eclipse.pde.build.tests/pom.xml, build/org.eclipse.pde.build.tests/test-sdk.product, build/pom.xml, ds/org.eclipse.pde.ds.tck/pom.xml, ds/pom.xml, e4tools/bundles/org.eclipse.e4.tools.emf.ui/pom.xml, e4tools/pom.xml, e4tools/tests/org.eclipse.e4.tools.compatibility.migration.tests/pom.xml, e4tools/tests/org.eclipse.e4.tools.persistence.tests/pom.xml, org.eclipse.pde.doc.user/pom.xml, pom.xml, ua/org.eclipse.pde.ua.tests/pom.xml, ua/pom.xml, ui/org.eclipse.pde.genericeditor.extension.tests/pom.xml, ui/org.eclipse.pde.junit.runtime.tests/pom.xml, ui/org.eclipse.pde.ui.templates.tests/pom.xml, ui/org.eclipse.pde.ui.tests/pom.xml, ui/org.eclipse.pde/pom.xml, ui/pom.xml
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1844
https://github.com/eclipse-pde/eclipse.pde/issues/1180
=> POM and product version changes for 4.32 release

org.eclipse.pde.doc.user/forceQualifierUpdate.txt
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1860
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1868
=> Clean forceQualifierUpdate files for doc bundles

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/GeneralInfoSection.java
- See https://github.com/eclipse-pde/eclipse.pde/issues/1189
=> Fix clipped text in Product Editor

e4tools/bundles/org.eclipse.e4.tools.emf.ui/forceQualifierUpdate.txt
Relates to https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1940
=> Enforce qualifier update of e4.tools.emf.ui

ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/reconciler/folding/TargetPlatformFoldingReconciler.java
Fixes https://github.com/eclipse-platform/eclipse.platform.ui/issues/1798
=> Fixed CCE on opening target file in compare editor

apitools/org.eclipse.pde.api.tools.ui/forceQualifierUpdate.txt, e4tools/bundles/org.eclipse.e4.tools.emf.ui/forceQualifierUpdate.txt, ui/org.eclipse.pde.spy.event/forceQualifierUpdate.txt, ui/org.eclipse.pde.ui/forceQualifierUpdate.txt
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1979
=> Touching bundles after compiler change

apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/model/tests/ApiDescriptionTests.java, apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/model/tests/ComponentManifestTests.java, apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/model/tests/TestSuiteHelper.java, apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/search/tests/SearchTest.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ApiBaseline.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ApiModelFactory.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/util/Util.java, apitools/org.eclipse.pde.api.tools/src_ant/org/eclipse/pde/api/tools/internal/tasks/CommonUtilsTask.java
Leverage the new ExecutionEnvironmentDescription(Map) constructor introduced in https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/282
=> [APItools] Leverage ExecutionEnvironmentDescription(Map) constructor

build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java
The new method JavaRuntime.getProvidedVMPackages(IVMInstall, String) was introduced with https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/175
=> Leverage new JDT API to obtain the packages provided by a VMInstall

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PluginModelManager.java
Currently there is a TODO that classpath updates should better always run in a job instead of synchronous to the call.
As asynchronous is often needed anyways this now finally resolves this TODO and aims to perform the action always in a background job.
=> Always run in a Job in PluginModelManager

org.eclipse.pde.doc.user/forceQualifierUpdate.txt
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2024
=> Touch doc bundle for

ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/PDETestCase.java
Currently a failure to delete a project fails the test randomly on windows. This can be caused for example when things happen too fast and a file is still locked.
This first try the delete and if it fails wait one second, sync the project and if it still exits retry the delete.
Fix https://github.com/eclipse-pde/eclipse.pde/issues/1265
=> Retry delete after a little delay / refresh in PDETestCase

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/P2Utils.java, ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/build/properties/AbstractBuildValidationTest.java, ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/performance/parts/TargetPlatformPerfTest.java, ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/target/AbstractTargetTest.java, ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/target/LocalTargetDefinitionTests.java
Remove unused code and unify and modernize remaining code.
=> Clean-up LocalTargetDefinitionTests

apitools/org.eclipse.pde.api.tools.tests/pom.xml, apitools/pom.xml, build/org.eclipse.pde.build.tests/pom.xml, build/org.eclipse.pde.build.tests/test-sdk.product, build/pom.xml, ds/org.eclipse.pde.ds.tck/pom.xml, ds/pom.xml, e4tools/bundles/org.eclipse.e4.tools.emf.ui/pom.xml, e4tools/pom.xml, e4tools/tests/org.eclipse.e4.tools.compatibility.migration.tests/pom.xml, e4tools/tests/org.eclipse.e4.tools.persistence.tests/pom.xml, org.eclipse.pde.doc.user/pom.xml, pom.xml, ua/org.eclipse.pde.ua.tests/pom.xml, ua/pom.xml, ui/org.eclipse.pde.genericeditor.extension.tests/pom.xml, ui/org.eclipse.pde.junit.runtime.tests/pom.xml, ui/org.eclipse.pde.ui.templates.tests/pom.xml, ui/org.eclipse.pde.ui.tests/pom.xml, ui/org.eclipse.pde/pom.xml, ui/pom.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2074
=> POM and product version changes for 4.33 release

build/org.eclipse.pde.build.tests/META-INF/MANIFEST.MF, build/org.eclipse.pde.build.tests/pom.xml, features/org.eclipse.pde-feature/feature.xml, org.eclipse.pde.doc.user/META-INF/MANIFEST.MF, org.eclipse.pde.doc.user/pom.xml, ui/org.eclipse.pde/META-INF/MANIFEST.MF, ui/org.eclipse.pde/pom.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2085
=> Version Bump

build/org.eclipse.pde.build.tests/pom.xml, build/org.eclipse.pde.build.tests/test.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2109
=> Test removing org.eclipse.rcp.configuration.feature.group

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/contentassist/display/JavaDocCommentReader.java
Use the proper api from o.e.text
=> Stop using jface internal SingleCharReader

e4tools/bundles/org.eclipse.e4.tools.compatibility.migration/META-INF/MANIFEST.MF, e4tools/bundles/org.eclipse.e4.tools.compatibility.migration/src/org/eclipse/e4/tools/internal/compatibiliy/migration/E4MigrationTool.java, features/org.eclipse.e4.tools.persistence.feature/feature.xml, ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/bndtools/BndTargetLocationFactory.java
Avoids NON-NLS and possible UnsupportedEncodingException
=> Replace "UTF8" with StandardCharsets.UTF_8

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiBaselineManager.java, apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ApiBaseline.java
Also remove unused method ApiBaseline.getVisibleDependentComponents().
@merks you often looked into the API-baseline tooling. Do you want to review this?
I assume `ApiBaselineManager.createWorkspaceBaseline()` used to be so complicated because it grew historically.
=> Simplify and clean-up API baseline initialization

build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/Utils.java, build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/BuildTimeSiteContentProvider.java, build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/BuildTimeSiteFactory.java, build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/P2Utils.java, build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PluginPathFinder.java
This avoids unnecessary conversations that also use deprecated methods like File.toURL()
=> [PDE-Build] Use File instead of URL to represent local files

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ArchiveApiTypeContainer.java
@merks you implemented to method in https://github.com/eclipse-pde/eclipse.pde/pull/357, do you have any objection?
=> [API-Tools] Use JDT's JRT-FileSystem cache

apitools/org.eclipse.pde.api.tools.tests/pom.xml, apitools/pom.xml, build/org.eclipse.pde.build.tests/pom.xml, build/org.eclipse.pde.build.tests/test-sdk.product, build/pom.xml, ds/org.eclipse.pde.ds.tck/pom.xml, ds/pom.xml, e4tools/bundles/org.eclipse.e4.tools.emf.ui/pom.xml, e4tools/pom.xml, e4tools/tests/org.eclipse.e4.tools.compatibility.migration.tests/pom.xml, e4tools/tests/org.eclipse.e4.tools.persistence.tests/pom.xml, org.eclipse.pde.doc.user/pom.xml, pom.xml, ua/org.eclipse.pde.ua.tests/pom.xml, ua/pom.xml, ui/org.eclipse.pde.genericeditor.extension.tests/pom.xml, ui/org.eclipse.pde.junit.runtime.tests/pom.xml, ui/org.eclipse.pde.ui.templates.tests/pom.xml, ui/org.eclipse.pde.ui.tests/pom.xml, ui/org.eclipse.pde/pom.xml, ui/pom.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2286
=> POM and product version changes for 4.34 release

build/org.eclipse.pde.build.tests/META-INF/MANIFEST.MF, build/org.eclipse.pde.build.tests/pom.xml, features/org.eclipse.pde-feature/feature.xml, org.eclipse.pde.doc.user/META-INF/MANIFEST.MF, org.eclipse.pde.doc.user/pom.xml, ui/org.eclipse.pde/META-INF/MANIFEST.MF, ui/org.eclipse.pde/pom.xml
Contributes to
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2299
=> Version bumps for 4.34 stream

features/org.eclipse.pde.spies-feature/feature.xml, ui/org.eclipse.pde.core/.settings/.api_filters, ui/org.eclipse.pde.core/META-INF/MANIFEST.MF, ui/org.eclipse.pde.spy.css/META-INF/MANIFEST.MF, ui/org.eclipse.pde.spy.css/src/org/eclipse/pde/spy/css/WidgetTreeProvider.java
for items that can not be styled with CSS
https://github.com/eclipse-pde/eclipse.pde/issues/1381
=> CSS Spy: fix NPE in WidgetTreeProvider #1381

.github/workflows/pr-checks.yml
As stated in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5043#note_2825431.
=> [Build] Fix pde-bot mail passed to 'checkVersions' workflow

ui/org.eclipse.pde.core/META-INF/MANIFEST.MF, ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/MinimalState.java
Backporting fix to 4_31 Maintenance Branch.
=> Backport : Do not build unrelated projects #1214

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java
Additionally consider the value of the 'followRepositoryReferences' property.
This is extracted from https://github.com/eclipse-pde/eclipse.pde/pull/1245 (currently its second commit).
=> [TP] Consider empty versions, repos and referenced targets in sync-check

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/IUBundleContainer.java
Currently when caching IUs it's not ensured that the latest version matching the declaration is selected. This could have the consequence that for a '0.0.0'-version not the latest version of an IU is selected, if multiple versions are in the profile/container.
=> [TP] Ensure the latest matching IU is queried when caching artifacts

ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/autocomplete/processors/AttributeValueCompletionProcessor.java, ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/model/RepositoryCache.java, ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/p2/P2Fetcher.java
This simplifies to select specific nested children of a composite repository:
=> [TP-Editor] Propose children of composite repositories

org.eclipse.pde.doc.user/forceQualifierUpdate.txt
https://download.eclipse.org/eclipse/downloads/drops4/I20241031-0310/testResults.php
=> Fix comparator issue in I-build

docs/User_Guide.md
Removes a few long outdating TODOs.
Clarifies that PDE build is not actively enhanced
=> Minor clean-up of the PDE user guide

ui/org.eclipse.pde.ui.templates/templates_3.1/browserView/java/$className$.java
Switched to SWT.DEFAULT to activate default browser
=> Browser templates view should not use SWT.WEBKIT as browser style #1509

Jenkinsfile, org.eclipse.pde.doc.user/forceQualifierUpdate.txt
Needed for
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2654#
=> Build with Java 21

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/targetdefinition/TargetEditor.java
=> TargetEditor.TargetChangedListener appears to expect to run on the UI thread #1505

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsInitializer.java
Currently if the JobManager suspended all kind of unwanted effects might happen, especially the joining of a scheduled job will not work but PDE use that here to init the PluginModelManager.
The only feasible situation here is to schedule a new job (that will be executed once the manager is enabled again) and then perform the required action. this will the possibly trigger a rebuild if required or notify other listeners.
=> If JobManager is suspended delay init to a later time

.github/workflows/checkDependencies.yml
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/.github/workflows#checkdependenciesyml
=> Add dependency check workflow

ui/org.eclipse.pde.core/META-INF/MANIFEST.MF
See https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3728 
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2884
=> Touch org.eclipse.pde.core after compiler change

apitools/org.eclipse.pde.api.tools.tests/forceQualifierUpdate.txt
Update forceQualifierUpdate.txt
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2935
=> Comparator errors in I20250319-0330 #2935

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/TargetWeaver.java
https://github.com/eclipse-pde/eclipse.pde/issues/1708
=> Fix TargetWeaver.getDevProperties() to decode fgDevPropertiesURL

ui/org.eclipse.pde.core/forceQualifierUpdate.txt
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2972
=> Touch org.eclipse.pde.core to reflect compiler changes

apitools/org.eclipse.pde.api.tools/forceQualifierUpdate.txt, ds/org.eclipse.pde.ds.annotations/forceQualifierUpdate.txt, ui/org.eclipse.pde.bnd.ui/forceQualifierUpdate.txt, ui/org.eclipse.pde.core/forceQualifierUpdate.txt, ui/org.eclipse.pde.genericeditor.extension/forceQualifierUpdate.txt, ui/org.eclipse.pde.ui/forceQualifierUpdate.txt
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2995
=> Touch bundles affected by compiler changes

build/org.eclipse.pde.build.tests/test-sdk.product
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/3100
=> Remove source features from the org.eclipse.sdk.test.ide product
