eclipse-pde/eclipse.pde

releng/org.eclipse.pde.ui.setup/PDE.setup
releng/org.eclipse.pde.ui.setup/PDEConfiguration.setup

https://github.com/eclipse-pde/eclipse.pde.ui/issues/4

Provide a configuration for PDE.setup

---

ui/org.eclipse.pde.ui.templates/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/core/tests/internal/WorkspaceModelManagerTest.java

This was not done in PR #3 and likely not discovered due to the then missing verification build.

Bump version of o.e.pde.ui.templates

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/correction/java/FindClassResolutionsOperation.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/search/dependencies/AddNewDependenciesOperation.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/search/dependencies/DependencyExtentOperation.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/search/dependencies/GatherUnusedDependenciesOperation.java

SearchPattern.createPattern() can return null pattern if the input is
not valid. So don't pass null patterns down to the Search engine, it
doesn't like that.

Bug 579635 - NPE in MatchLocator.findIndexMatches(MatchLocator.java:306)

---

.github/workflows/verifyFreezePeriod.yml
Jenkinsfile

Perform the code freeze period check in a dedicated reusable workflow instead of in the Jenkins-Build-Pipeline.
The workflow being called was created in:
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/206

[RelEng] Perform code freeze periode check in GitHub workflow

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/util/TarFile.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/util/Util.java
ds/org.eclipse.pde.ds.core/META-INF/MANIFEST.MF
ds/org.eclipse.pde.ds.core/src/org/eclipse/pde/internal/ds/core/builders/DefaultSAXParser.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/DefaultSAXParser.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/schema/Schema.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/SAXParserWrapper.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/SchemaUtil.java
ui/org.eclipse.pde.core/src_ant/org/eclipse/pde/internal/core/ant/ConvertSchemaToHTML.java
ui/org.eclipse.pde.core/text/org/eclipse/pde/internal/core/text/XMLEditingModel.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/performance/parts/SchemaTraversePerfTest.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/util/xml/ParserWrapperTestCase.java

Finalization is deprecated for removal since [Java-18](https://openjdk.java.net/jeps/421) and there are already better alternatives with Java-11.
Together with PR #18 this removes all overwrites of Object.finalize in the PDE code base.

Replace Finalization by try-with-resource

---

features/org.eclipse.pde-feature/feature.xml

ASM comes transitively from Required-Bundle of API Tools. So let's
remove it from feature to facilitate upgrades to newer version without
having to touch the feature.

Remove asm from feature.xml

---

ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/RequirementHelper.java

This fixes #30.
`RequirementHelper.addApplicationLaunchRequirements()` now returns true if
all requirements are satisfied and false if requirements are missing.
Instead of reverting the return value of `addApplicationLaunchRequirements()` the if-condition in the callers could be reverted, but I think it is more meaningful and does align better e.g. with Java-standard Collection if true is returned in case all requirements are satisfied.

Fix #30: fix check on missing requirements in Equinox preLaunchCheck()

---

apitools/org.eclipse.pde.api.tools/META-INF/MANIFEST.MF

Fix https://github.com/eclipse-pde/eclipse.pde/issues/42
FYI @bjhargrave @jonahgraham

APi tools should import package ASM instead of require bundle it

---

ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/BundleLauncherHelper.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/RequirementHelper.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/EquinoxLaunchConfiguration.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/ui/launcher/EquinoxLaunchConfiguration.java

This PR aims to fix https://github.com/eclipse-pde/eclipse.pde.ui/issues/32.
My first attempt was to add the requirements associated to a launch-configuration-type to all sub-classes of the corresponding LaunchConfigurationDelegate. But besides the the launch-configuration this would also require the launche's mode to obtain the correct delegate and this is not always trivial and would require a medium amount of changes.
Furthermore it is not correct because just because a launch-delegate extends EclipseApplicationLaunchConfiguration it does not mean that the launch-type of the sub-class has the same requirements.
So I have limited this fix to the previous specialty of the Equinox-Launch to add the required o.e.osgi and ensured that it is added.
If there is a demand to register own …

Add required o.e.osgi bundle for subclasses of EquinoxLaunchConfig too

---

ui/org.eclipse.pde.ui.templates.tests/src/org/eclipse/pde/ui/templates/tests/TestPDETemplates.java

* Stop using assertThat(message, variable equalTo(constant). It's just
complicated way to write assertEquals(message, constant, variable) which
even calls out to yet another library.
* Remove needless throws declaration.
Seen while investigating #55
Change-Id: If4b7a6937a9ec9acac88e435c21c52f7e7e6f1d8

Minor changes to TestPDETemplates

---

ui/org.eclipse.pde.ui.templates.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.templates.tests/pom.xml
ui/org.eclipse.pde.ui.templates.tests/src/org/eclipse/pde/ui/templates/tests/TestPDETemplates.java
ui/org.eclipse.pde.ui.templates/templates_3.5/E4Application/$pluginId$.product

With the latest changes in Equinox o.e.osgi.util was replaced by the
corresponding 'original' OSGi-reference bundles that are
required+reexported by o.e.osgi.util. Unfortunately the re-export does
not help in this product launch. Therefore o.e.osgi.util is replaced by
the actually needed plugins.
And apply one minor code improvement in TestPDETemplates.
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/55

Replace o.e.osgi.util in PDE E4-app template product

---

releng/org.eclipse.pde.setup/PDE.setup
releng/org.eclipse.pde.setup/PDEConfiguration.setup

This PR inlines the `PDE Core` Project and adds a `PDE Build` Working-Set.
Furthermore it removes the 'core' element from ids.
Just like for the renaming of the project from PDE UI to PDE Core we have to provide a way to inform users that they have to update the Project-stream referenced in their workspace setup. Otherwise the setup is broken.
@merks can you please review this?

Fully reflect merge of pde.build in PDE's Oomph setup

---

ui/org.eclipse.pde.ui.templates/templates_3.5/E4Application/$pluginId$.product

With the latest changes in Equinox o.e.equinox.preferences was replaced
by the
corresponding 'original' OSGi-reference bundles that are
required+reexported by it. Unfortunately the re-export does
not help in this product launch. Therefore o.osgi.service.prefs is
actually added to needed plug-ins.

Add o.osgi.service.prefs in PDE E4-app template product

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/IUBundleContainer.java

An error during this step causes the number of available artifacts to be
empty. So the error log should reflect that something went wrong.

Log the exception when failing to update the target profile cache

---

ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/AbstractPDELaunchConfiguration.java

fixes https://github.com/eclipse-pde/eclipse.pde/issues/49

Use PDEState target models to compare version to set security manager allow flag

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/LaunchAction.java

If a user has created a launch-configuration for a feature-based product and changes that feature to be based on plug-ins and then launches the product from the product-editor, the attribute to use features or plug-ins is not updated so the launch-config is still based on feature.
This PR fixes that and also makes the order in which the launch-config attributes are set more meaning full.

Update launch-config when switching from feature to plug-in product

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/LaunchAction.java

To create similar applications like when build with Tycho, optional-requirements should be ignored by default when assembling the bundles that are included in a plug-in based product-application launched from the IDE.
If a user want's to include optional dependencies it can be re-enabled in the launch-config dialog by checking the corresponding box. 
The attribute is only set for newly created launch-configs to not change the value of existing configs that were set manually.
@jhonnen what do you think? This changes the default behavior for plug-in based products and should then be mentioned in the N&N.

Ignore optional-requirements by default for plugin-product launches

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/DependencyManager.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/core/tests/internal/DependencyManagerTest.java

In rare cases fragments provide new packages to their host wiring.
In such case those fragments have to be included into the requirements closure, otherwise the resolution of the final set of bundles will fail.
One real world example from Eclipse is `o.e.egit.core`.
This bundle imports the package `o.e.jgit.gpg.bc` that is provided by the fragment with the same name. Its host is `o.e.jgit`, which does not export such package.
If one creates a product or launch config that includes (or requires) `o.e.egit.core` but not `o.e.jgit.gpg.bc` and enables automatic inclusion of requirements the pre-launch validation fails because for `o.e.egit.core` the package-import `o.e.jgit.gpg.bc` is not satisfied.
When a corresponding product is build with Tycho, the fragment that is the only …

Include package-providing fragments when computing requirements closure

---

ui/org.eclipse.pde.junit.runtime.tests/src/org/eclipse/pde/junit/runtime/tests/JUnit5SuiteExecutionTest.java
ui/org.eclipse.pde.junit.runtime/src/org/eclipse/pde/internal/junit/runtime/RemotePluginTestRunner.java

- add org.eclipse.jdt.junit5.runtime bundle to JUnit5 bundles so that
the MethodOrderer class for running JUnit5 failures first can be
accessed by the platform engine
- modify JUnit5SuiteExecutionTest to assert that the bundle is added
- fixes #117

New feature to run JUnit5 failures needs RemotePluginTestRunner change

---

ui/org.eclipse.pde.junit.runtime/src/org/eclipse/pde/internal/junit/runtime/RemotePluginTestRunner.java

change to RemotePluginTestRunner
Change-Id: I596221951aec54cff3690e5084077b2e817c5cce

Fix NPE -New 4.24 JDT feature to run JUnit5 failures first requires

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetDefinition.java

These exceptions are recorded by IUBundleContainer.synchronizerChanged
but TargetDefinition.resolve(IProgressMonitor) only notices exceptions
that are thrown and does not consider the status that recorded in the
IContainerLocation.
No logging is needed because the exception was already logged when it
was recorded.
https://github.com/eclipse-pde/eclipse.pde/issues/126

Exceptions thrown by IUBundleContainer.cacheIUs are lost

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/target/TargetDefinitionContentPage.java

TargetDefinitionContentPage.initializeListeners() should also listen to reloads.
https://github.com/eclipse-pde/eclipse.pde/issues/128

The Reload button in the target platform Edit... wizard is a no-op

---

apitools/org.eclipse.pde.api.tools/META-INF/MANIFEST.MF
apitools/org.eclipse.pde.api.tools/pom.xml
ui/org.eclipse.pde.launching/META-INF/MANIFEST.MF

Fixes comparator issues due to lambda order jdt bug.
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/313

Version bumps for 4.25 stream

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetReferenceBundleContainer.java

Otherwise Eclipse will use the old, (potentially outdated) profiles to resolve their artifacts.
If one or more artifacts are not contained in the old profile, resolving the file fails until the metadata folder is cleared.
I've tried out some ideas to reuse the code for deleting the profiles in the TargetEditor class, but so far without success.
Resolves issue #90

Delete the profile of nested target files on reload.

---

ui/org.eclipse.pde.core/META-INF/MANIFEST.MF
ui/org.eclipse.pde.core/pom.xml
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/sourcelookup/PDESourceLookupDirector.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/sourcelookup/PDESourceLookupQuery.java
ui/org.eclipse.pde.ui.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.tests/pom.xml
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/classpathresolver/ClasspathResolverTest.java

Fixes https://github.com/eclipse-pde/eclipse.pde/issues/133
Since the problem likely exists for a while I suggest to consider this for the next release.

Handle missing plug-ins in source-lookup and use List instead of arrays

---

ui/org.eclipse.pde.ui/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/feature/FeatureFormPage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties

Publishing a feature can be done via multiple means, for command line
publishing Tycho is frequently used and the latest Tycho version stopped
supporting update sites. Therefore, remove the "advertisement" of using
update sites from the feature editor, an editor should not promote an
publishing alternative which is not supported anymore by the most
popular build tool.

Stop promoting update site creation via the feature editor

---

CONTRIBUTING
README.md

https://wiki.eclipse.org/PDE/Contributor_Guide has been updated to point
to https://github.com/eclipse-pde/eclipse.pde/blob/master/CONTRIBUTING
Fixes #12

Update of Contribution guide

---

ui/org.eclipse.pde.ui.templates/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.templates/templates_3.5/E4Application/$pluginId$.product

They were embedded in equinox bundles but not anymore.
Fixes:
```
java.lang.AssertionError:
Generated product fails validation:
[Missing Constraint: Import-Package: org.osgi.service.event;
version="1.3.0", Missing Constraint: Require-Bundle:
org.osgi.service.metatype; bundle-version="[1.4.0,1.5.0)", Missing
Constraint: Require-Bundle: org.osgi.service.upnp;
bundle-version="[1.2.0,1.3.0)", Missing Constraint: Require-Bundle:
org.osgi.service.wireadmin; bundle-version="[1.0.0,1.1.0)", Missing
Constraint: Import-Package: org.osgi.service.event;
version="[1.3.0,1.5.0)", Missing Constraint: Import-Package:
org.osgi.service.component.runtime; version="[1.5.0,1.6.0)", Missing
Constraint: Require-Bundle: org.osgi.service.cm;
bundle-version="[1.6.0,1.7.0)", Missing Constraint: Require-Bundle: …
```

Fix E4 template to include osgi jars

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/ProductOutlinePage.java

The product editor outline has been unsorted since the very first commit
by overriding the sort() method as empty code. By removing the empty
override everything works well again, because the super class uses the
viewer comparator, and that uses the label provider.

Sort product editor outline view (fixes #172)

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/EditTargetContainerPage.java

Don't list target files that are directly added in a target (.target) while adding (fixes #159)
Change-Id: If2edf9fbdfc1961b9379936936ad5886e1a05af3

Don't list target files that are directly added in a target (.target) while adding

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/product/Product.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/product/RepositoryInfo.java

Fixes https://github.com/eclipse-pde/eclipse.pde/issues/167
The list of fRepositories is changed to be a LinkedHashSet to avoid
multiple entries with the same URL. If multiple entries with the same
URL exists they are merged into one that is enabled if any of those
entries with that URL is enabled.
FYI @laeubi

Stabilize content of configuration- and repo-section in product-files

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/EditDirectoryContainerPage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/EditTargetContainerPage.java

If a file or directory doesnt exist while adding a target, make it an error (fixes #187)
Change-Id: I06216a81a29930086e2941f1cc73e940bb6c3f25

If a file or directory doesnt exist while adding a target, make it an

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/AbstractProblemDetector.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ApiBaseline.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/provisional/comparator/ApiComparator.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/search/UseScanReferenceVisitor.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/search/XmlReferenceDescriptorWriter.java

Using JDT cleanup, the unnecessary assignments were removed to have
shorter code.

Unnecessary local variable assignment removed in api.tools

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/EditDirectoryContainerPage.java

Fix copyright year
Change-Id: I2448d4ce143ae171901f5d6cf252f4c554798c0d

Fix copyright year wrongly introduced in last commit

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/TargetPlatformHelper.java

While fixing https://github.com/eclipse-jdt/eclipse.jdt.core/pull/245
I've noticed that TargetPlatformHelper is the only caller of
ClasspathJrt.getModule() that does not check for null return, which is
however fully valid result.
Simply added a NP check to avoid NPE in
TargetPlatformHelper.querySystemPackages()

Don't unconditionally dereference ClasspathJrt.getModule()

---

ui/org.eclipse.pde.core/plugin.xml
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/OSGiAnnotationsClasspathContributor.java

OSGi has support for annotations that are only retained at the class
file (but not on the runtime) to help tools generating meta-data or
perform several checks.
This adding them to the compile-classpath without requiring the bundle
developer to import them (what would create an undesired runtime binding
to those packages) if they are found in the target platform.
This is part of https://github.com/eclipse-pde/eclipse.pde/issues/69
1. Start an Eclipse with this patch
2. download https://mvnrepository.com/artifact/org.osgi/org.osgi.annotation.versioning/1.1.2 and https://mvnrepository.com/artifact/org.osgi/org.osgi.annotation.bundle/2.0.0
3. create a simple project named "target", create a folder lib, put both files in and add the following target
```
<?xml version="1.0" encoding="UTF-8" …
```

Add support for the OSGi Bundle and Versioning Annotations

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/TargetPlatformHelper.java

This reverts commit 063f6862855c37835ebfe8c7b83f2ab1a7531126.
To see if that causes failures on Jenkins (see #232)

Revert "Don't unconditionally dereference ClasspathJrt.getModule()"

---

features/org.eclipse.pde-feature/feature.xml

If found in the repository then include the optional bundle/version annotation bundles so they are available when choosing the "The running platform" as a target, this will also include them in update-sites so people can install them from the SDK.

Require the bundle/version annotation bundles when installing PDE

---

.github/workflows/build.yml

Windows is an important development platform for PDE we should also test
a PR on these platforms as it has shown to having issues (e.g. different
path handling) in the past.

Enable matrix build for windows

---

ui/org.eclipse.pde.core/text/org/eclipse/pde/internal/core/text/AbstractEditingModel.java
ui/org.eclipse.pde.core/text/org/eclipse/pde/internal/core/text/bundle/BundleModel.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/context/InputContext.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/BundleInputContext.java

Currently, when adding a manifest header the new value is always placed
at the bottom. This has the disadvantage, that the order of manifest
headers is determined by the order of inserts.
Especially if headers are added/removed (e.g. DS) automatically this can
lead to modified manifest that are semantically equivalent.
To prevent this, but still keep user-order of manifest headers, the
following algorithm is applied to have always the same insertion place:
1) All headers of the manifest are fetched
2) Special headers, that need to be retained at the top are ignored
3) All remaining headers are sorted ignoring their case
4) The header that is before the header to insert in this alphabetical
list is chosen as the insertion point
5) if the is no predecessor, the Bundle-ManifestVersion header …

Enforce a deterministic Manifest-Header order when inserting new keys

---

ui/org.eclipse.pde.core/META-INF/MANIFEST.MF
ui/org.eclipse.pde.core/plugin.xml
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/annotations/CustomHeaderAnnotationProcessor.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/annotations/ExportPackageAnnotationProcessor.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/annotations/OSGiAnnotationProcessor.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/annotations/OSGiAnnotations.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/annotations/OSGiAnnotationsClasspathContributor.java
ui/org.eclipse.pde.ui/plugin.xml
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/annotations/OSGiAnnotationsASTRequestor.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/annotations/OSGiAnnotationsASTVisitor.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/annotations/OSGiAnnotationsCompilationParticipant.java

Now we have support in PDE to use the OSGi annotations, we can start to
process them by the tooling.
This adds support for Version/Export/Header annotations and updates the
manifest accordingly.
Part of https://github.com/eclipse-pde/eclipse.pde/issues/69

Update manifest header by given OSGi annotations

---

ui/org.eclipse.pde.unittest.junit/.project

This causes errors in the workspace's pom.xml when m2e is installed.

Remove m2e nature and builder from org.eclipse.pde.unittest.junit

---

features/org.eclipse.pde-feature/feature.xml
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/annotations/OSGiAnnotationsClasspathContributor.java

Currently PDE ships an (outdated) version of the DS annotations, like
with the bunde/version annotations it would be better to simply fetch
the latest version from the given users target.

Always provide the official annotations if present in target

---

.github/matcher.json

Thanks to
- https://github.com/eclipse-pde/eclipse.pde/pull/264
we can now greatly simplify the matcher and get full annotation support for API problems withing GH action builds:

Update the matcher for new ApiTools output

---

build/org.eclipse.pde.build/META-INF/MANIFEST.MF
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/TargetPlatformHelper.java

As reported in https://github.com/eclipse-pde/eclipse.pde/pull/221#issuecomment-1198011695 #194 can also occur when exporting Products.
This applies the same fix to PDE-build. In my little test-case that worked.
Since pde.core depends on pde.build I had to copy the code from `TargetPlatformHelper` to PDE build. Looking at other places this is not the first time the dependency issue was solved like that.
Additionally this applies a minor shortcut for `TargetPlatformHelper.querySystemPackages()`

Use the actual system-packages from the JVM for Product/Site export

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/TargetPlatformHelper.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/DependenciesPage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/IntroSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/PluginConfigurationSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/ProductInfoSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/ProductValidateAction.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/LaunchAction.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties

Clean up Product LaunchAction: format, use braces and minor clean-ups
+ Replace arrays by collections
Simplify Product LaunchAction and associated classes
- Make recursive collection of child features iterative
- Reuse code to collect plugin-models from LaunchAction in other places

Clean up product launching

---

ui/org.eclipse.pde.ui/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEPlugin.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEPluginImages.java

Images need to be initialized in Display tread.
ManifestContentAssistProcessor runs in background thread and use images.

PDEPluginImages: fix NullPointerException #297

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEPlugin.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEPluginImages.java

This reverts commit 6dd163d3eb45e587b04ff32796dbb804e69105de.
See https://github.com/eclipse-pde/eclipse.pde/issues/297#issuecomment-1236603988

Revert "PDEPluginImages: fix NullPointerException #297"

---

ui/org.eclipse.pde.launching/forceQualifierUpdate.txt

The issue is with lambda order

4.26 I-Build: I20220915-0110 - Comparator Errors Found

---

ui/org.eclipse.pde.ui.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.tests/pom.xml
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/PDETestCase.java

- don't swallow resource exceptions on teardown - they might hide fails in following tests
- don't open message or error dialogs to avoid test hangs
See https://github.com/eclipse-pde/eclipse.pde/issues/355

Test fixes to uncover hidden test failures

---

apitools/org.eclipse.pde.api.tools.tests/META-INF/MANIFEST.MF
apitools/org.eclipse.pde.api.tools.tests/pom.xml
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/model/tests/ApiBaselineTests.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ApiModelCache.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ArchiveApiTypeContainer.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/SystemLibraryApiComponent.java

Instead of assuming that modules are represented as *.jmod, which is only the case for a JDK but not for a JRE, the jrt file system should be used.  In addition, jar files should  use the jar file system, to uniformly handle both cases.  The JRT approach also allows loading all the modules of the JDK/JRE not just the java.base module.
https://github.com/eclipse-pde/eclipse.pde/issues/356

ArchiveApiTypeContainer should properly load classes from modules

---

ui/org.eclipse.pde.runtime/src/org/eclipse/pde/internal/runtime/PDERuntimeMessages.java
ui/org.eclipse.pde.runtime/src/org/eclipse/pde/internal/runtime/pderuntimeresources.properties
ui/org.eclipse.pde.runtime/src/org/eclipse/pde/internal/runtime/registry/RegistryBrowser.java
ui/org.eclipse.pde.runtime/src/org/eclipse/pde/internal/runtime/registry/RegistryBrowserLabelProvider.java
ui/org.eclipse.pde.runtime/src/org/eclipse/pde/internal/runtime/registry/model/Bundle.java
ui/org.eclipse.pde.runtime/src/org/eclipse/pde/internal/runtime/registry/model/LocalRegistryBackend.java
ui/org.eclipse.pde.runtime/src/org/eclipse/pde/internal/runtime/registry/model/RegistryBackend.java

As described in [Bug 579310](https://bugs.eclipse.org/bugs/show_bug.cgi?id=579310) the `Enable/Disable` action of the `Plug-in Registry` is broken because the compatibility implementation of the `org.eclipse.osgi.service.resolver.PlatformAdmin` does not support addition/removal of `DisableInfo`.
This is broken for a while already and since nobody has complained I suggest to simply remove those actions and the whole disable/enable story.
If the others I agree I have to check that I didn't miss to remove anything related and didn't remove too much.

Bug 579310 - Remove broken "Enable/Disable" action from Plug-in Registry

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/exports/FeatureExportOperation.java

The install location might be null for workspace resources. In this case, it is no longer possible to export plugins via the export wizard. Instead, those features are skipped with a warning.
Example: Synthetic features derived from Maven poms via m2e.

Fix: Issue 366 - NPE when exporting plug-ins via the export wizard

---

ui/org.eclipse.pde.core/META-INF/MANIFEST.MF
ui/org.eclipse.pde.core/plugin.xml
ui/org.eclipse.pde.core/schema/dynamicSource.exsd
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/IPluginSourcePathLocator.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/ClasspathUtilCore.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/EclipsePluginSourcePathLocator.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/LocalMavenPluginSourcePathLocator.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/SourceLocationManager.java

Currently a plugin can contribute source locations inside the plugin itself through the extension point
org.eclipse.pde.core.source
this has the limitation that the source must be embedded and known in advance. In some situations it would be required to provide external locations dynamically e.g. maven has the concept of source artifacts that could be queried, if a bundle contains a Bundle-Source-Location one could checkout one could have a "source-repository" and so on.
This adds the necessary parts for a new extension point
org.eclipse.pde.core.dynamicSource
and a extracts the implementation that search for Eclipse/Maven co-located source bundles.
Part of #202

Add support for dynamically contribute bundle source locations

---

features/org.eclipse.pde-feature/feature.xml
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/annotations/OSGiAnnotationsClasspathContributor.java

The Metatype Service Specification defines a set of annotations to allow defining possible configuration options of a service as code.
These annotations are only retained at class level and can the used at build time to generate the proper XML definition, we should enable PDE users to use these annotations as well, so this information can then be used for example in Tycho or BND builds.
This depends on
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/653

Also take metatype annotations into account

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/LocalMavenPluginSourcePathLocator.java

A plugin's install location can be a folder.
Also ".jar" may appear elsewhere in the name not just at the end.
https://github.com/eclipse-pde/eclipse.pde/pull/379

LocalMavenPluginSourcePathLocator should not assume all plugins are jars

---

ui/org.eclipse.pde.spy.event/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui/META-INF/MANIFEST.MF

OSGi services should really not be imported by requiring a specific provider, replacing the require-bundle with the appropriate import decouples the plugin from a specific implementation detail.

Import the service.event package instead of require the equinox bundle

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiAnalysisApplication.java

Rely on project-specific or IDE defaults to be consistent with workspace.

Remove enforced settings for the API analysis application

---

ui/org.eclipse.pde.core/plugin.xml
ui/org.eclipse.pde.core/schema/dynamicSource.exsd

This enables dynamic source providers to state how complex there computation is so the using code can decide to query faster ones first, or even decide if showing some progress or scheduling jobs is suitable.
@vik-chand I'd like to get approval for this to be included in RC2 because of the following reasons:
1. The extension point was only added in this release (and relative late) so there are no consumers we can break or where there are issues
2. this intentionally do not contain any code changes (what could be done in 2023-03 release) but possible implements should be forced to define this property from day-1 so we have the information available.

Add complexity attribute for source locators

---

ui/org.eclipse.pde.ui.templates/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.templates/src/org/eclipse/pde/internal/ui/templates/e4/E4ToolbarContributionTemplate.java

Currently the E4 toolbar template uses 	element.setAttribute("apply", "apply") which is incorrect, apply is not a valid entry, we should use always.

E4 toolbar contribution template fixed

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiFileGenerationApplication.java

Eclipse platform migrated to Tycho for generating the API baseline. Yon also also add the generation to your Tycho build. Also platform is not using this application anymore it is now deprecated and may be deleted in the future-
</plugin>
<plugin>
<groupId>org.eclipse.tycho</groupId>
<artifactId>tycho-apitools-plugin</artifactId>
<version>${tycho.version}</version>
<executions>
<execution>
<id>generate</id>
<goals>
<goal>generate</goal>
</goals>
<configuration>
<skip>${skipAPIDescription}</skip>
<projectName>${project.artifactId}_${qualifiedVersion}</projectName>
laeubi marked this conversation as resolved.
</configuration>
</execution>
</executions>
</plugin>

Deprecate ApiFileGenerationApplication

---

ui/org.eclipse.pde.ui.tests.smartimport/.classpath
ui/org.eclipse.pde.ui.tests.smartimport/.settings/org.eclipse.jdt.core.prefs
ui/org.eclipse.pde.ui.tests.smartimport/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.tests.smartimport/pom.xml

It uses RedDeer which itself moved to require Java 17. Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/648

Move o.e.pde.ui.tests.smartimport to Java 17 BREE

---

ui/org.eclipse.pde.core/META-INF/MANIFEST.MF
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/BundleManifestSourceLocationManager.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PDEState.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/SourceLocationManager.java

Currently a "source bundle" is required to have a special header so PDE can discover it, but actually certain location types (e.g. P2 Sites and maven) have other ways to identify/discover the source bundle. Even the Targetplatform model already has the concept of a location that knows about the source for a bundle.
This adds a sourcepath locator that is capable of discovering such native source bundles from the target platform location and implements an ordered lookup that first queries lower complexity locators.

Lookup source bundles in the current target platform

---

ui/org.eclipse.pde.ui.templates.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.templates.tests/pom.xml
ui/org.eclipse.pde.ui.templates.tests/src/org/eclipse/pde/ui/templates/tests/TestPDETemplates.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/ProductValidateAction.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/LaunchAction.java

The Validation provided in the Product-Editor only considered the Set of Plug-ins/Bundles directly contained in the product and did not consider transitive dependencies included in launches of the product. With this change this is fixed so that the Validation in the Product-Editor sees the same set of Bundles like the validation when the product is really being launched.
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/306
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/343
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/437
Required for https://github.com/eclipse-pde/eclipse.pde/pull/434

[Editor] Consider complete Set of launched Bundles in Product-validation

---

ui/org.eclipse.pde.ui.templates/templates_3.5/E4Application/$pluginId$.product

Nothing requires it directly and Maven central and Orbit had different symbolic names so better let the tooling resolve whatever it needs(if at all).

Do not explicitly include commons-io in template

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/preferences/TargetPlatformPreferencePage.java

The null-case was forgotten in 2f33eea55a4af1fb858a4ce2ac98feb6cd74f723
CC @iloveeclipsesince since you usually discover such bugs quite quickly. :)

Fix NPE in TargetPlatformPreferencePage

---

apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/ApiBuilderTest.java

Also ensure it initializes the ApiTestingEnvironment's target platform.

Ensure that ApiBuilderTest disables RUN_API_ANALYSIS_AS_JOB

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/TypeScope.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/AbstractApiTypeContainer.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/DirectoryApiTypeContainer.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ProjectTypeContainer.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/StubArchiveApiTypeContainer.java

and ensure the names are always unique and sorted.

Simplify implementations of IApiTypeContainer.getPackageNames()

---

ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/LaunchConfigurationHelper.java
ui/org.eclipse.pde.ui.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/launcher/PluginBasedLaunchTest.java

Do not consider only bundle id when generating the runtime metadata, resolving to actually configured bundle as soon as possible.
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/433

Honor multiple versions of same bundle in launch config

---

ui/org.eclipse.pde.ui.templates/plugin.properties

the information on the actual extensions used in the browser plugin template was missed out in the help text associated with the plugin template selection view, for some reason. incorporate that info, so that the help page reflects the actuals.
**generated plugin.xml:**
**template wizard help text:**

complete the help text content of the browser plugin template

---

apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/ApiTestingEnvironment.java
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/OSGiLessAnalysisTests.java
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/compatibility/BundleMergeSplitTests.java
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/compatibility/BundleVersionTests.java
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/performance/PerformanceTest.java
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/usage/DependentUsageTests.java
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/comparator/tests/DeltaTestSetup.java
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/model/tests/ApiDescriptionTests.java
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/model/tests/ComponentManifestTests.java
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/search/tests/SearchTest.java
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/tests/AbstractApiTest.java
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/util/tests/ApiBaselineManagerTests.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiBaselineManager.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/WorkspaceDeltaProcessor.java

Disable auto builds to reduce background activities.

Dispose baselines more carefully, especially workspace baselines.

---

.github/workflows/build.yml
.gitignore
.mvn/maven.config
Jenkinsfile
README.md

Add a .mvn/maven.config that contains the maven arguments shared in the Jenkins-CI, GitHub workflow and for a local build. This also enables the 'build-individual-bundles' profile for all of the mentioned scenarios, so that one does not have to specify it manually anymore.
The profile 'bree-libs' is never definied in any pom.xml and therefore removed as CLI argument.
The property 'project.build.sourceEncoding=UTF-8' is already defined in the 'eclipse-platform-parent' pom and is therefore unnecessary.
In the Jenkins build additionally define the
properties'maven.test.error.ignore=true' and
'maven.test.failure.ignore=true' in order to only mark the build as unstable if there are test-failures/errors so that it is simpler to distinguish from other failures in the build.
In Jenkins not …

Unify Maven build arguments into maven.config and remove unnecessary

---

ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/project/PluginRegistryTests.java

Instead of using hardcoded version or the bundle version (which should match the one in OSGi container) fetch the version from OSGi and use that version for quering the plugin registry.

Fix PluginRegistryTests

---

build/README.md

Recommending Tycho as a standalone build and giving clear message about state of this part of the code.
This should have been done in 2016 as per March 29, 2016 [PMC discussion](https://wiki.eclipse.org/Eclipse/PMC/Minutes_2016 ) .
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/469

Add pde.build readme

---

ui/org.eclipse.pde.ui/plugin.properties

The name of the compiler under the plug-in development property page is appearing differently in different contexts. Since we are already under the plugin development tab, just the name `Compiler` should suffice.
Eclipse preference property page:
Quick-fix property page:

Standardize name of the compiler in different property sheets

---

ui/org.eclipse.pde.core/META-INF/MANIFEST.MF
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/FileResource.java
ui/org.eclipse.pde.ui/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/tools/IOrganizeManifestsSettings.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/tools/OrganizeManifest.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/tools/OrganizeManifestsProcessor.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/tools/OrganizeManifestsWizardPage.java

Currently there is no convient way to convert a bundle from using Require-Bundle to Import-Package (what is recommended to use).
This adds a new option in the OrganizeManifest action to do this conversion automatically in the follwoing way:
- Automatic Managed Dependencies are set to using Import-Package
- Current Require-Bundles are converted to Automatic Managed Dependencies
- the package imports are recalculated and updated
Fix https://github.com/eclipse-pde/eclipse.pde/issues/362

Add an action to convert a bundle import into a package import

---

features/org.eclipse.pde-feature/feature.xml
features/org.eclipse.pde.spies-feature/.project
features/org.eclipse.pde.spies-feature/.settings/org.eclipse.core.resources.prefs
features/org.eclipse.pde.spies-feature/.settings/org.eclipse.core.runtime.prefs
features/org.eclipse.pde.spies-feature/build.properties
features/org.eclipse.pde.spies-feature/feature.properties
features/org.eclipse.pde.spies-feature/feature.xml

Fixes https://github.com/eclipse-pde/eclipse.pde/issues/472
When this is merged we have to make sure that the new feature ends up in the Eclipse-SDK repo.
Can someone tell me where to do this?
The SimRel contribution has to be adjusted too in https://git.eclipse.org/c/simrel/org.eclipse.simrel.build.git/tree/ep.aggrcon
Alternatively we could simply add it to the org.eclipse.sdk feature. Then it should end in both of the mentioned repos automatically. But I'm not sure if this is the right place.
@akurtakov should we consider this for RC1? Or better wait for 4.28?

Move PDE spies to dedicated new Feature 'o.e.pde.spies'

---

ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/BundleLauncherHelper.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/launcher/PluginBasedLaunchTest.java

Fixes https://github.com/eclipse-pde/eclipse.pde/issues/68
For example JUnit Plug-in tests that usually include all available bundles (Plug-ins and Fragments) when being launched often suffer from messages about unresolved bundles due to unsatisfied environment constraints (e.g. when having platform specific fragments for multiple different platforms there are always some unsatisfied on the current platform).
Only exclude fragments because sometimes unresolved bundles (non-fragments) are wanted in the launched application.
I verified that unresolved fragments (may it be due to wrong environment or missing dependencies) are excluded, but I was not yet able to reproduce the failed resolution messages from the launched application in my minimal reproducer, although I have seen them before.

Exclude unresolved fragments when launching with all active plug-ins

---

ui/org.eclipse.pde.spy.bundle/META-INF/MANIFEST.MF
ui/org.eclipse.pde.spy.context/META-INF/MANIFEST.MF
ui/org.eclipse.pde.spy.core/META-INF/MANIFEST.MF
ui/org.eclipse.pde.spy.css/META-INF/MANIFEST.MF
ui/org.eclipse.pde.spy.event/META-INF/MANIFEST.MF
ui/org.eclipse.pde.spy.model/META-INF/MANIFEST.MF
ui/org.eclipse.pde.spy.preferences/META-INF/MANIFEST.MF

When the PDE spies were moved into their own feature they have not been included into the I-builds repo in time and where temporarily removed. Therefore there is now a baseline discrepancy which is fixed by bumping their version.
See for example https://github.com/eclipse-pde/eclipse.pde/pull/497#issuecomment-1467730236

Bump PDE Spy version to fix baseline-issues due to their interim removal

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiAnalysisApplication.java

Currently there is the case that the provided baseline file does not exits at all, in such a case the default baseline is silently returned what is not what we want here.
Fix https://github.com/eclipse-pde/eclipse.pde/issues/511

Check if the provided baseline actually exits

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/SourceLocationKey.java

Currently the SourceLocationKey will produce a NPE if the bundle symbolic name is null but the constructor never ensures that it is not null.
This replace the hand written hascode / equals with eclipse generated Java 1.7+ variant that can savly accept nulls.
Fix https://github.com/eclipse-pde/eclipse.pde/issues/507

Fix hasCode / equals to scope will null values in SourceLocationKey

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/BaseApiAnalyzer.java

Spurious API tool error may occur if a new bundle added ( with same

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/build/BuildSourceViewerConfiguration.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/contentassist/BuildPropertiesContentAssistProcessor.java

A rudimentary implementation of the auto-complete feature for the build.properties file editor for features, plugins and fragments. Searches and auto-fills valid property names.
Pending items would be to handle corner cases (if any), provide a help text, provide potential suggestions for the values. But I prefer to handle one item at a time - I am still learning things!
Fixes: https://github.com/eclipse-pde/eclipse.pde/issues/503

autocomplete for build.properties

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/parts/FormBrowser.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/BaseWizardSelectionPage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/plugin/TemplateListSelectionPage.java

The plug-in template selector has two components - template list, and the help text (FormBrowser). While the first widget follows the toggle button properly, the formbrowser does not. Fix that by toggling between enabled and disabled states following the template selector button.
Before the change: when the template selector is off, the template list is disabled, but the form browser is not.
After the change: both the template list as well as the form browser is disabled.

synchronise both the views with the template selector

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ApiBaseline.java

Currently one gets a lots of lingering files named:
```
/tmp/eed17021414477589663537.ee
/tmp/eed15599516348791254164.ee
/tmp/eed10981864096532456217.ee
/tmp/eed9998009589164187122.ee
/tmp/eed2679993409650199583.ee
```
in the temp directory of the system even though after the file is read it is never used anywhere.

Delete the temporary file after being parsed

---

ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/ProjectClasspathPreferenceChangeListener.java
ui/org.eclipse.pde.core/.project
ui/org.eclipse.pde.core/.settings/org.eclipse.pde.ds.annotations.prefs
ui/org.eclipse.pde.core/META-INF/MANIFEST.MF
ui/org.eclipse.pde.core/OSGI-INF/.gitignore
ui/org.eclipse.pde.core/build.properties
ui/org.eclipse.pde.core/plugin.properties
ui/org.eclipse.pde.core/plugin.xml
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PDECoreMessages.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PluginModelManager.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsClasspathContainer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsInitializer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/annotations/OSGiAnnotationsClasspathContributor.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndBuilder.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndProjectManager.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndResourceChangeListener.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/FileResource.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/ProjectJar.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/TargetRepository.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/natures/BndProject.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/pderesources.properties
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/project/PDEProject.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/core/tests/internal/classpath/ClasspathResolutionTest.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/RequiredPluginsContainerPage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/tools/OrganizeManifest.java

Currently PDE only supports a "Manifest-First" approach whne building plugins, but actually most of the data in a manifest can be derived from the compiled class files and sources.
This adds a very basic aproach to support "Code-First" but still retain the basic concepts of PDE like a target platform and the integration with the existing PDE ecosystem.
1. create a new java project
2. create a file `bnd.bnd` in the root of the project (see below for an example)
3. add the nature `org.eclipse.pde.BndNature` (this should automatically add the
```
<buildCommand>
<name>org.eclipse.pde.BndBuilder</name>
</buildCommand> 
```
You can now configure the project in the BND file, for example similar to this:
```
Bundle-SymbolicName: my.first.bnd.test
Bundle-Name: This is a test showing the new …
```

Add support for building plugins with using bnd as manifest generator

---

ui/org.eclipse.pde.ui.tests/META-INF/p2.inf

jdt.launcher requires special treatment to find jvms on MacOS that is handeled with an additional bundle and the pde.ui test depend on the launching framework.
This adds a p2.inf that pulls in this additional depenedency using a p2.inf for the test framework resoloution.
Lets see if this helps for PDE as well @HannesWell

Use p2.inf to pull in depedency to org.eclipse.jdt.launching.macosx

---

ui/org.eclipse.pde.genericeditor.extension.tests/pom.xml

Bundle o.e.pde.genericeditor.extension.tests no longer requires o.e.osgi.compatibility.state bundles or it was even copy-paste from somewhere.
This reduces possible differences between I-build tests and Maven testing.

Remove manual tycho-surefire dependency

---

ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/core/tests/internal/WorkspaceModelManagerTest.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/core/tests/internal/WorkspaceProductModelManagerTest.java

... due to race conditions and not thread-safe but concurrently accessed models.
In this first attempt it uses the big hammers: await all jobs, refresh-workspace and disable auto-build. If this initial attempt is successful I'll try to use less to reduce the test runtime.
This hopefully
- Fixes https://github.com/eclipse-pde/eclipse.pde/issues/21 
- Fixes https://github.com/eclipse-pde/eclipse.pde/issues/125 
- Fixes https://github.com/eclipse-pde/eclipse.pde/issues/255 
- Fixes https://github.com/eclipse-pde/eclipse.pde/issues/300 
- Fixes https://github.com/eclipse-pde/eclipse.pde/issues/375 
- Fixes https://github.com/eclipse-pde/eclipse.pde/issues/359 
- Fixes https://github.com/eclipse-pde/eclipse.pde/issues/494

Fix intermittent test failures in Workspace(Product)ModelManagerTest

---

ui/org.eclipse.pde.ui/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui/plugin.xml

Currently only items are shown in the package-explorer or in the file menu but not in project explorer:
This adds the missing items to the project explorer as well.

Add missing shortcuts for the project explorer

---

ui/org.eclipse.pde.core/plugin.properties
ui/org.eclipse.pde.core/plugin.xml
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/FileAdapter.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndBuilder.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndProjectManager.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndResourceChangeListener.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/natures/BndProject.java
ui/org.eclipse.pde.ui/plugin.xml
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/bnd/BndInputContext.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/bnd/BndModel.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ExecutionEnvironmentSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ExportPackageSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ImportPackageSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/LibrarySection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ManifestEditor.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ManifestOutlinePage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/OverviewPage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/PluginGeneralInfoSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/RequiresSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/RuntimePage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/plugin/NewProjectCreationOperation.java

Currently the bnd instructions file is only displayed in a raw text editor, but this is very inconvenient as the user is not able to inspect the final results.
This connects the bnd instruction file with the usual manifest editor to edit the file and inspect the results in a way PDE users are familiar with.

Display generated manifest and bnd instructions in manifest editor

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/SearchablePluginsManager.java

SearchablePluginsManager saves the state of the resources in the workspace without acquiring a lock, or not scheduling the job asynchronously.
Fix it by employing the WorkspaceJob scheduler.
Fixes: #64

synchronise resource tree modification

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndBuilder.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndProjectManager.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/ProjectJar.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/natures/BndProject.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/project/PDEProject.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/dialogs/PluginSelectionDialog.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/PDEFormEditor.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/bnd/BndBadLocationException.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/bnd/BndDocument.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/bnd/BndInputContext.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/bnd/BndModel.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/bnd/BndRegion.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/BundleInputContext.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/DependenciesPage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/DependencyAnalysisSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/GeneralInfoSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/LibrarySection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/LibraryVisibilitySection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ManifestEditor.java

Currently one can edit the instructions file and after safe the manifest is updated (and thus also the editor), but the other way does not work, if one for example edit the name in the overview page the changes are just overwritten on the next compile.
This installs listeners and implements a very basic model for the instructions so changes are mirrored to the instructions file as it already happens for the MANIFEST.MF source tab.

Synchronize values changed in the Overview with the instructions file

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/parts/ConditionalListSelectionDialog.java

There are potential race conditions that are happening between the dialog creation with empty list and the thread that populates the list and fires selection change events.
An easy hack is to make sure the button is enabled whenever there are items in the list. This always
works, as the default behavior of list makes sure
that there is at least one item selected in a
non-empty list.
Fixes: https://github.com/eclipse-pde/eclipse.pde/issues/534

make export dialog add button follow list selection

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/plugin/TemplateListSelectionPage.java

The "automatic" flag is actually bound to the enablement of an OSGi Framework project type, so we need to disable it when OSGI is not selected.
@HannesWell @vik-chand this should be easy enough to be included in current M1?
Fix https://github.com/eclipse-pde/eclipse.pde/issues/566

Automatic flag in TemplateListSelectionPage must check if OSGi is active

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/views/imagebrowser/filter/SizeFilter.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/templates/PreprocessorParser.java

replace legacy switch block with java 17 semantics:
1. short-circuit initialization in the switch expression
2. default case match with the original initialization
3. reduce complex boolean expression to an elegant form
Refs: https://github.com/eclipse-pde/eclipse.pde/pull/570#pullrequestreview-1379419914
/cc @HannesWell

migrate to Java 17 switch semantics: extras

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PreferenceInitializer.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/preferences/MainPreferencePage.java

Remove all references to the UI preference for running API analysis in parallel to the builder, as a scheduled job, While retaining the underlying boolean ICoreConstants.RUN_API_ANALYSIS_AS_JOB so that the tests that depend on it are unaffected, though it is false always.
Fixes: https://github.com/eclipse-pde/eclipse.pde/issues/307

remove RunAPIAnalysisBuilderAsJob option from perferences UI

---

ui/org.eclipse.pde.spy.bundle/META-INF/MANIFEST.MF
ui/org.eclipse.pde.spy.context/META-INF/MANIFEST.MF
ui/org.eclipse.pde.spy.core/META-INF/MANIFEST.MF
ui/org.eclipse.pde.spy.css/META-INF/MANIFEST.MF
ui/org.eclipse.pde.spy.event/META-INF/MANIFEST.MF
ui/org.eclipse.pde.spy.model/META-INF/MANIFEST.MF
ui/org.eclipse.pde.spy.preferences/META-INF/MANIFEST.MF
ui/org.eclipse.tools.layout.spy/META-INF/MANIFEST.MF

- Only use Import-Package to for javax.annotation and javax.inject
- Always use closed version ranges [1.X,2) with a minor lower bound
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1056

Improve OSGi metadata about dependency to javax.inject/annotations

---

Jenkinsfile

The required Github apps have been requested and installed in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2920.

Enable publication of Jenkins build code metrics as Github checks

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiAccess.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiAnalysisApplication.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiDescription.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiDescriptionManager.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiDescriptionProcessor.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiDescriptionXmlCreator.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/CRCVisitor.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/NonApiProjectDescription.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ProjectApiDescription.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/IncrementalApiBuilder.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/Reference.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/ReferenceExtractor.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/ReferenceResolver.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/SystemApiDetector.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/TagValidator.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/Validator.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/search/ApiDescriptionModifier.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/search/ConsumerReportConvertor.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/search/MissingRefReportConverter.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/search/ReferenceDescriptor.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/search/ReferenceLookupVisitor.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/search/UseReportConverter.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/search/UseScanParser.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/search/UseSearchRequestor.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/search/XmlReferenceDescriptorWriter.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/util/Signatures.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/util/SinceTagVersion.java

Replace legacy switch block with java 17 semantics
ref: https://openjdk.org/jeps/361
PS: This is my first PR in eclipse-pde.

Migrate to Java 17 switch 

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEPluginImages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/contentassist/BuildPropertiesContentAssistProcessor.java

Refs: https://github.com/eclipse-pde/eclipse.pde/pull/508
This PR addresses one of the pending items in the referenced PR. The auto-complete feature attaches most relevant image icons to the properties listing, so that the user is able to associate meaning of the property intuitively. 
The work is incomplete. I have taken some assumptions here, and would like to get some reviews before proceeding further. 
- Classified the headers of the build.properties specification
- Identified and attached the most meaningful existing images
- Provided a generic image for the default case(when the work completes I expect only very few items under this category.)
Please let me know what you think of the general approach.

Auto-complete for build.properties: Image Icons

---

ui/org.eclipse.pde.ui.tests/pom.xml

This is necessary to not fail after https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1059.

Remove unnecessary javax-bundle dependencies in tycho-surefire config

---

ui/org.eclipse.pde.ui.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/launcher/FeatureBasedLaunchTest.java

As mentioned in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1056#issuecomment-1541421660 the test needs adjustments.

Adapt tests to migration to javax-bundles provided by Jakarta

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/feature/Feature.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/ifeature/IFeature.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/feature/RequiresSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties

Two points:
1. `IFeature` has a `computeImports` method, which I didn't touch because that - even if unused in this project - would be a breaking API change.
2. The help content doesn't explain what the _Compute_ button or _Recompute when..._ checkbox do, but the image example is outdated.
Closes: eclipse-pde#37

Remove compute button and sync checkbox from the feature editor

---

apitools/org.eclipse.pde.api.tools/META-INF/MANIFEST.MF
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ApiElement.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/StubArchiveApiTypeContainer.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/util/Util.java
ui/org.eclipse.pde.core/META-INF/MANIFEST.MF
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/TargetDefinitionManager.java
ui/org.eclipse.pde.core/src_ant/org/eclipse/pde/internal/core/ant/ConvertSchemaToHTML.java
ui/org.eclipse.pde.ui/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ManifestEditor.java

use try-with-resource

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/FeatureBlock.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/nls/InternationalizeWizard.java

Avoiding type-casts makes code easier to read.

Use typed for-each loop

---

build/org.eclipse.pde.build.tests/src/org/eclipse/pde/build/tests/PDETestCase.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/plugin/ExternalPluginModelBase.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/core/tests/internal/WorkspaceModelManagerTest.java

Now that PDE does not use `o.e.core.runtime.Path` anymore, the usage of `java.nio.file.Path` can be simplfied.

Simplify usage of java.nio.file.Path

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/AbstractProductContentSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/FeatureSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/PluginSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties

Unify the Product Editor's `PluginSection` and `FeatureSection`, so that it can be re-used in https://github.com/eclipse-pde/eclipse.pde/pull/291 for a future `MixedSection` too.
Removes unused code like the implementation of `IPluginModelListener` in `PluginSection`.

Unify and clean-up Product Editor's PluginSection and FeatureSection

---

ui/org.eclipse.pde.ui.templates/templates_3.5/E4Application/$pluginId$.product

As soon as [Bug 325614](https://bugs.eclipse.org/bugs/show_bug.cgi?id=325614) is resolved, the E4Application template product can be simplified by leveraging that feature.
I could not yet test if the `org.eclipse.e4.rcp` is sufficient but a coarse comparison looks promising.

Leverage mixed products in E4-App template product

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PDECore.java

Cleaning is not an operation that should fail the saving and show an error to the user therefore we only write a warning to the log.
Fix https://github.com/eclipse-pde/eclipse.pde/issues/628

Do not fail if cleaning orphan targets fails on shutdown

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/DependencyAnalysisSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/views/dependencies/DependenciesView.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/views/plugins/PluginsView.java

This fixes the issue that in the `Dependencies` section of the Manifest-Editor if one called one of the following actions only the 'Plugin-Dependencies' of the latest version of all Bundles with the same Bundle-SymbolicName was displayed:
For Plug-ins:
- `Show the plug-in dependency hierarchy`
- `Show dependent plug-ins and fragments`
For Fragments:
- `Find this fragment's host plug-in`
In a separate(first) commit this PR contains clean-ups in code associated with Plug-in Dependency Analysis

Consider Bundle-Version when opening 'Plugin-Dependencies' from Manifest Editor

---

ui/org.eclipse.pde.spy.preferences/src/org/eclipse/pde/spy/preferences/handler/ToggleLayoutControl.java
ui/org.eclipse.pde.spy.preferences/src/org/eclipse/pde/spy/preferences/handler/TogglePreferenceTraceControl.java
ui/org.eclipse.pde.spy.preferences/src/org/eclipse/pde/spy/preferences/viewer/PreferenceMapLabelProvider.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/compare/PluginStructureCreator.java
ui/org.eclipse.tools.layout.spy/src/org/eclipse/tools/layout/spy/internal/dialogs/ControlSelector.java
ui/org.eclipse.tools.layout.spy/src/org/eclipse/tools/layout/spy/internal/dialogs/LayoutSpyDialog.java

Replace `ResourceManager` methods deprecated since https://github.com/eclipse-platform/eclipse.platform.ui/pull/838.
Create Colors directly, because SWT Color instances don't need to be disposed.

Replace deprecated ResourceManager methods and create colors directly

---

apitools/org.eclipse.pde.api.tools.ui/META-INF/MANIFEST.MF
apitools/org.eclipse.pde.api.tools/META-INF/MANIFEST.MF
ui/org.eclipse.pde.core/META-INF/MANIFEST.MF
ui/org.eclipse.pde.genericeditor.extension.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.runtime/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui/META-INF/MANIFEST.MF

Replace the use of the legacy and Eclipse-specific MANIFEST.MF header 'Eclipse-LazyStart: true' by the OSGi standard compliant header 'Bundle-ActivationPolicy: lazy' (which is already used in most cases.
@tjwatson do you know any reason to keep the old 'Eclipse-LazyStart: true' header?

Remove 'Eclipse-LazyStart' headers in favor of 'Bundle-ActivationPolicy'

---

apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/actions/ExportSessionAction.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/search/UseReportConverter.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/util/Util.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/IUBundleContainer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetDefinitionPersistenceHelper.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetPersistence38Helper.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/XmlTransformerFactory.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/core/tests/internal/AllPDECoreTests.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/core/tests/internal/XmlTransformerTest.java

External entity resolution is not supported by PDE (see PDECoreMessages.XMLErrorReporter_ExternalEntityResolution). PDE should not contact or even inject external sources into formatted xml.

Format xml without external entity resolution

---

build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java

For eager return on manifestStream == null jarFile was not closed.

PDEState: unconditionally close stream

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/APIFileGenerator.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/BundleComponent.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/search/UseReportConverter.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/search/UseScanParser.java
apitools/org.eclipse.pde.api.tools/src_ant/org/eclipse/pde/api/tools/internal/tasks/APIDeprecationReportConversionTask.java
apitools/org.eclipse.pde.api.tools/src_ant/org/eclipse/pde/api/tools/internal/tasks/APIFreezeReportConversionTask.java
apitools/org.eclipse.pde.api.tools/src_ant/org/eclipse/pde/api/tools/internal/tasks/AnalysisReportConversionTask.java
build/org.eclipse.pde.build/src_ant/org/eclipse/pde/internal/build/tasks/JNLPGenerator.java
build/org.eclipse.pde.build/src_ant/org/eclipse/pde/internal/build/tasks/XmlParserFactory.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/AbstractModel.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/plugin/AbstractExtensions.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/plugin/PluginBase.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/update/configurator/ConfigurationParser.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/update/configurator/FeatureParser.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/PDEXMLHelper.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/SAXParserWrapper.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/XmlParserFactory.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/core/tests/internal/AllPDECoreTests.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/core/tests/internal/XmlParserFactoryTest.java

External entity resolution is not supported by PDE (see PDECoreMessages.XMLErrorReporter_ExternalEntityResolution) but still the SAXParser did follow external links where DefaultHandler.resolveEntity was not overwritten.
At many places PDE already overwrote DefaultHandler.resolveEntity to prevent external resolution. With the new configuration that method is not even called anymore.
This change offers and uses a configuration that
* reports an Exception if .xml contains DOCTYPE or
* does just ignore external references (as a fall back if the exception would show up to cause trouble).
Also the caching of used parsers in possibly other threads is removed because the SAXParser is not guaranteed to be thread-safe. Only the factory is reused, because that is effectively final after creation. …

Factory for SAXParser parsing XML without DOCTYPE

---

build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/ProductGenerator.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/Utils.java

fixes regressions from a2612ef2a43488c4c71632c56a240b8f022f1c09 
for example:
"FileAlreadyExistsException: license.html" in
org.eclipse.pde.build.internal.tests.p2.PublishingTests.testBug266488()
"p2.inf doesn't exist" in
org.eclipse.pde.build.internal.tests.p2.PublishingTests.testBug271373()

fix file Utils regression #661

---

ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/model/Node.java

The Node.childNodes is not guaranteed to be set, same as Node.nodeTag.
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/670

UpdateUnitVersionsCommandTests.confirmVersionUpdates fails randomly with NPE

---

build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/ProductGenerator.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/Utils.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/builder/SourceGenerator.java

Simplifies the code and also makes it a little bit faster.

Replace use-cases of internal PDE build Utils by standard Java methods

---

apitools/org.eclipse.pde.api.tools.tests/META-INF/MANIFEST.MF
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/util/tests/UtilTests.java
build/org.eclipse.pde.build.tests/META-INF/MANIFEST.MF
ds/org.eclipse.pde.ds.annotations.tests/META-INF/MANIFEST.MF
ds/org.eclipse.pde.ds.tests/META-INF/MANIFEST.MF
ua/org.eclipse.pde.ua.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsClasspathContainer.java
ui/org.eclipse.pde.genericeditor.extension.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.junit.runtime.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.templates.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.tests.smartimport/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/performance/parts/TargetPlatformPerfTest.java

This PR does two things, mainly with the goal to not require a specific hamcrest bundle name:
1. Compute junit5 runtime Plug-ins dynamically in RequiredPlugins-Container
And add support for old junit bundle names from Orbit.
2. Reference junit and hamcrest only via Import-Package
This requires to import the hamcrest packages, if they are used and those test-plugins don't rely on the re-export of hamcrest by org.junit anymore.
Additionally only use junit-4 assertion methods and replace use of junit-3 assertions.
And remove unnecessary hard-coded references to the hamcrest bundle name.
@merks what do you think?

Compute junit5 runtime Plug-ins dynamically in RequiredPlugins-Container and reference junit and hamcrest only via Import-Package

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ApiBaseline.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/MinimalState.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/TargetPlatformHelper.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/LaunchValidationOperation.java
ui/org.eclipse.pde.ui.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/core/tests/internal/classpath/ClasspathResolutionTest.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/core/tests/internal/core/builders/BundleErrorReporterTest.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/ee/ExecutionEnvironmentTests.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/target/TargetEnvironmentTestCase.java

Fixes https://github.com/eclipse-pde/eclipse.pde/issues/429
- Only consider EE of running VM in launch validation to match the behavior later at runtime
- For the PDEState the EE's system-package is computed with the following distinction:
- for a EE that corresponds to a Java-9 or higher release, get the 'best matching' VMInstall and query the system-packages for the EE's   java release version (which is possible for modular JVMs)
- for a Java-8 or lower release check if there is a VMInstall selected/strictly compatible to that version and query the system-packages from that VM (i.e. its rt.jar and other libraries)
- if there is no VMInstall for a for a Java-8 or lower release, combine the hard-coded list of 'java.*' packages with the set of
non-java packages provided by the default …

Enhance computation of system-package provided by a ExecutionEnvironment

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiAnalysisApplication.java

As part of the build probabbly other jobs are sceduled, the ApiAnalysisApplication should wait for all jobs to complete before investigate error markers to prevent problems with outdated states.
Currently the ApiAnalysisApplication seem flaky as discovered here:
- https://github.com/eclipse-equinox/equinox/pull/246#issuecomment-1658189309
@HannesWell @vik-chand please give approval for M3 this should not affect any IDE users but can improve the situation for Tycho users.

ApiAnalysisApplication should wait until jobs are done

---

ui/org.eclipse.pde.core/META-INF/MANIFEST.MF
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndBadLocationException.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndBuilder.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndDocument.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndErrorReporter.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndRegion.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/bnd/BndModel.java

Currently if one has an error in the pde.bnd file there is no feedback for the user about the problem.
This adds a validator that reads the errors/warning and display them to the user as error markers mapping the error to a line number if possible.
Fix https://github.com/eclipse-pde/eclipse.pde/issues/699
@HannesWell @vik-chand I'd like to include this into M3 as it is otherwise very hard for users to notice that something is wrong (beside from getting annoyed that 'something' seems not working)

Show warnings/errors from the BND build

---

build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java

Fixes https://github.com/eclipse-pde/eclipse.pde/issues/709
@laeubi can you test this with your 'bad' vm installation?

Query others suitable VMs for system-packages if one cannot be read

---

build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java

Fixes https://github.com/eclipse-pde/eclipse.pde/issues/721
This handles the case that `JavaRuntime.getDefaultVMInstall()` returns null, which according to the docs happens
`when no defaultVM was set or when the default VM has been disposed.`
I also considered to just select any of the available VMs, maybe the 'latest' one, but since no default JRE should actually not happen (at least I get an error in the preferences if I don't select one), for me it seems to be better to warn the user about that instead of selecting just any VM.
@akurtakov should we merge this now to have this in RC1 or better wait for RC2?

Handle missing default VMInstall when querying JVM system-packages

---

build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java

Don't try to map class files in the root directories and catch whatever obscure exception may be thrown to avoid basic functionality to be broken.
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/724

StringIndexOutOfBoundsException when creating a new PDE project

---

build/org.eclipse.pde.build/META-INF/MANIFEST.MF
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/FeatureGenerator.java

Even though Entry.equals(String) was defined String.equals(Entry) == false. It's pure implementation detail of the Set created in FeatureGenerator.createSet(String[]) if s.equals(e) or e.equals(s) is called and also Entry.hashCode() does not match String.hashCode();

fix FeatureGenerator.addLauncher()

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/AbstractPluginBlock.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/CachedCheckboxTreeViewer.java

In Run/Debug configurations when changing Start Level/ Auto-Start for some plug-ins and apply the changes,
and closing and reopening the popup will make changes to disappear provided "Only show selected" is selected.
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/311

Run/ Debug Configurations tab Plug-ins issue #311

---

ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/classpathupdater/ClasspathUpdaterTest.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/ee/ExecutionEnvironmentTests.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/tools/UpdateBuildpathWizard.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/tools/UpdateClasspathJob.java

Leverage the implicit cancellation checks and progress reporting of `SubMonitor.split()`.
@haubi since you worked on the `ClasspathUpdate` recently, maybe you are interested in this as well?

Simplify UpdateClasspathJob

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java

Currently referenced repositories are ignored, that prevents sharing of items that are already available in the referenced repository.
This enables searching references (if possible) to find IUs and dependencies in these referenced repositories as well.
Fix https://github.com/eclipse-pde/eclipse.pde/issues/720

Enable referenced repositories when resolving the target content

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/PDEJavaHelper.java

findPackageFragmentRoot() searches through all PackageFragment Roots and is called for every libPaths. This can be slow due to involved file access.
see https://github.com/eclipse-jdt/eclipse.jdt.core/issues/303
Instead call getAllPackageFragmentRoots() only once, index the result and use O(1) hash access.

performance: avoid O(n^2) in PDEJavaHelper

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/BaseApiAnalyzer.java

Currently there is no way to pass the project to the analyzer without having an project ProjectComponent, but users of BaseApiAnalyzer might have other means to find the project in question.
This makes the BaseApiAnalyzer#getJavaProject() protected so implementors can override this (e.g. Tycho).
This relates to
- https://github.com/eclipse-pde/eclipse.pde/issues/785

Make BaseApiAnalyzer#getJavaProject protected

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/BundleComponent.java

Currently BundleComponent do not propagate errors but only log them, this can lead to a situation where it is unclear what calls fails.
This changes the init method to throw an CoreException in all cases where it encounters a problem and instead use dedicated catch whenever it seems suitable.
See https://github.com/eclipse-pde/eclipse.pde/issues/553

Do not hide init errors in BundleComponent

---

apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/ApiBuilderTest.java
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/compatibility/BundleMergeSplitTests.java
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/compatibility/BundleVersionTests.java
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/compatibility/CompatibilityTest.java

Currently exporting the API description sometimes fails because there could be a race between a resource change event and disposal of the api component.
This changes the following things:
- the API description is performed as the very first step
- if generation fails wait until all running jobs are done
- then retry up to three times
This should fix https://github.com/eclipse-pde/eclipse.pde/issues/553

Wait for jobs to complete and perform up to three retries

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/project/PDEProject.java

Currently one must either specify a folder or delete the preference BUNDLE_ROOT_PATH or PDE gives an error message.
Instead we should interpret an empty BUNDLE_ROOT_PATH as the explicit intend of the user to use the project as a bundle root.

Setting BUNDLE_ROOT_PATH preference to an empty string gives an error

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/TracingOptionsManager.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/LaunchArgumentsHelper.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/AbstractPDELaunchConfiguration.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/JUnitLaunchConfigurationDelegate.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/TracingBlock.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/TracingPropertySource.java
ui/org.eclipse.pde.unittest.junit/src/org/eclipse/pde/unittest/junit/launcher/JUnitPluginLaunchConfigurationDelegate.java

@fedejeanne these are the clean-ups I mentioned in https://github.com/eclipse-pde/eclipse.pde/pull/674#pullrequestreview-1577719920.
Since you are probably using tracing more often than I do, do you want to try/review the changes?

Clean-up and simplify Tracing-Options processing

---

ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/classpathupdater/ClasspathUpdaterTest.java

Currently the ClasspathUpdaterTest just complains that the update has failed but the user has no chance to see what's wrong.
Thats especially annoying as the test randomly fails.

Add better error feddback to ClasspathUpdaterTest

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetReferenceBundleContainer.java

Currently URIs are not discovered when they are defined in a referenced target location.
This now also look into referenced target for locations that are suitable to supply additional URIs.
This relates to https://github.com/eclipse-pde/eclipse.pde/issues/207

Discover URIs from referenced target locations

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/ProjectJar.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/project/PDEProject.java

Currently we have only the option to set the bundleroot to a different folder (what the will become the outputfolder). In some cases one might want to set the bundle root also to the project root.
This now adds special handling for the case where bundle root != output folder.
Fix https://github.com/eclipse-pde/eclipse.pde/issues/803
@merks if you like to try this out do the follwoing:
1. Create a project with automatic manifest generation:  https://newsroom.eclipse.org/eclipse-newsletter/2023/june/notable-improvements-eclipse-ide#Support-for-Automatic-Manifest-Generation
2. Now goto `.settings/org.eclipse.jdt.core.prefs`
3. Add the follwoing line: `BUNDLE_ROOT_PATH=`
4. You should now see the `META-INF/MANIFEST.MF` created at the root of the project for your for your convenience and …

Support setting the bundleroot for manifest generated projects

---

ui/org.eclipse.pde.core/META-INF/MANIFEST.MF
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/target/TargetBundle.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/InstallableUnitGenerator.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java

Currently the IULocation can only consider units from other locations if these are also of type IU location but other target types might be able to supply items in a way not know to the IULocation.
This adds the necessary infrastructure to support this usecase by using the adapter pattern.
Fix https://github.com/eclipse-pde/eclipse.pde/issues/207
Requires https://github.com/eclipse-equinox/p2/pull/348

Consider other locations when resolving IUs from updatesites

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/FileResource.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/ProjectJar.java

Currently we copy everything that would normally go to the jar into the output folder, but if on the next build the resource is not put anymore we have some orphan files.
This records what resources are created as part of the project build and finally deletes any orphans on close.
Fix https://github.com/eclipse-pde/eclipse.pde/issues/587

Delete orphan files that are copied/generated by bnd automatic manifest

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/PDESourcePage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/bnd/BndAutoCompleteProcessor.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/bnd/BndInputContext.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/bnd/BndSourcePage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ManifestEditor.java

Currently there is no autocompletion at all, this adds the basic infrastructure to allow autocompletion for at least the -buildpath where it suggest bundles from the target platform state.
Fix https://github.com/eclipse-pde/eclipse.pde/issues/700
https://github.com/eclipse-pde/eclipse.pde/assets/1331477/1fcb9bfb-9dcf-4c89-ad83-e3fbdf568330

Add basic autocompletion support for pde.bnd files buildpath

---

ui/org.eclipse.pde.ui/plugin.xml
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/MultiSourceEditor.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/bnd/BndSourcePage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/feature/FeatureEditor.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ManifestEditor.java

Currently a plain TextEditor is used, but the ExtensionBasedTextEditor is much more powerful.
@mickaelistria I was able  to use `ExtensionBasedTextEditor` now and register the completion proposals via extension registry so it seems to work at the basics, can you take a look if it looks sane or I'm doing anything wrong here/not recommended?
Relates to https://github.com/eclipse-pde/eclipse.pde/issues/701

Use the generic editor as the source editor for bnd instructions

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/plugin/NewProjectCreationOperation.java

Currently if the "generate automatic manifest" is checked it still creates one if a user later choose to create a traditional one.
This enhance the check in the wizard to make sure it is actually a valid choice.
Fix https://github.com/eclipse-pde/eclipse.pde/issues/798

Correctly determine if automatic manifest option is valid

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/iproduct/IRepositoryInfo.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/isite/IRepositoryReference.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/product/RepositoryInfo.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/site/RepositoryReference.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/dialogs/RepositoryDialog.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/category/RepositoryReferenceSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/UpdatesSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties

2 editors are changed: product file editor and then the repository section but also the category editor which uses the same stuff (code is very simular)
UI part for https://github.com/eclipse-equinox/p2/issues/345

Support names for Updates repositories in product definition

---

ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/model/xml/ManifestEditorSpellCheckTestCase.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/PDEFormEditor.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/PDEFormPage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/context/InputContextManager.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ManifestEditor.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/OverviewPage.java

Currently the manifest editor shows an error when one opens a plain bnd file. This is because no "manifest first" parts are found and the bnd form page is only added for pde.bnd files.
This now fixes the issue by making manifest-first files completely optional and show a plain bnd editor instead in case of only a bnd file.

Show only single editor when open plain BND files

---

ds/org.eclipse.pde.ds.ui/META-INF/MANIFEST.MF
ua/org.eclipse.pde.ua.ui/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/PDESourcePage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/bnd/BndSourcePage.java

Actually all PDE source pages can benefit from Generic Editor also some functionality relies on the PDESourcePage as a base.
This makes the PDESourcePage extend the ExtensionBasedTextEditor to account for this.

Use ExtensionBasedTextEditor as the base instead of TextEditor

---

ua/org.eclipse.pde.ua.tests/META-INF/MANIFEST.MF
ua/org.eclipse.pde.ua.tests/pom.xml

Without this, there is a compile error calling PDESourcePage.getDocumentProvider.

The pde.ua.tests requires org.eclipse.ui.genericeditor

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/schema/PathSchemaProvider.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/schema/Schema.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/schema/SchemaDescriptor.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/schema/SchemaInclude.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/schema/SchemaProvider.java
ui/org.eclipse.pde.core/src_ant/org/eclipse/pde/internal/core/ant/ConvertSchemaToHTML.java

Currently the lookup of additional schemas is hardcoded to use a list of absolute pathes. this has the drawback that other ways are not supported (e.g. schemas from a jar file or whatever source).
This adds an abstraction for the lookup that can be used to plugin additional strategies.

Abstract the lookup of included schemas

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/schema/SchemaToHTMLConverter.java
ui/org.eclipse.pde.core/src_ant/org/eclipse/pde/internal/core/ant/ConvertSchemaToHTML.java

Currently non trivial work is done inside the ConvertSchemaToHTML ant task.
This extract that parts into SchemaToHTMLConverter so it can be reused by other build frameworks (e.g. maven/tycho)

Extract code from ConvertSchemaToHTML Ant Task into reusable PDE class

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/MinimalState.java

The exception is an attempt to shed some light in the real cause of the problem that's causing some tests fail and it simply replaces an obscure NPE that's happening anyway. It logs the name of the model for which the method would have failed with a NPE.
This PR does **not** solve the underlying problem, it merely helps identifying it.
Contributes to https://github.com/eclipse-pde/eclipse.pde/issues/554
FWIW by looking at the rest of the code in the class, I'm pretty sure it should be safe to simply skip such plug-ins by changing the `if` statement at the beginning of the method to 
```java
if (model == null || model.getInstallLocation() == null) {
return;
}
```
... what do you guys think?

Throw exception in MinimalState::addBundle if the model wasn't installed

---

Jenkinsfile

Currently javadoc is not generated as part of the build making javadoc errors hard to discover.

Enable Javadoc generation in build

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/schema/SchemaInclude.java

It is allowed to not specify any schema provider in that case no additional search is performed.
Fix https://github.com/eclipse-platform/.github/issues/167

Schema provider is optional in SchemaInclude

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/exports/PluginExportWizardPage.java

The commit fixes OSGi plugins (that have been created using standard OSGi framework with 'Generate OSGi metadata automatically' feature) not being displayed in the export dialog box. This happens because an OSGi project has a pde.bnd file, unlike the eclipse plugins, which has build.properties. Therefore the previous behaviour was to check for the presence of a build.properties file for validating a plugin project. This assumption breaks with the new type.
The commit relies on the following assumptions in case of OSGi template projects:
- The location of the pde.bnd file is always under the root folder of the plugin project
- The filename is always constant, namely, pde.bnd.
Fixes: #600

List OSGI plugins in the export list

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/FeatureErrorReporter.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/exports/FeatureExportOperation.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/exports/PluginExportOperation.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/exports/ProductExportOperation.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/feature/FeatureData.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/feature/FeaturePlugin.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/ifeature/IFeatureEntry.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/ifeature/IFeaturePlugin.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/CoreUtility.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/core/tests/internal/feature/FeatureDataTestCase.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/util/ProjectUtils.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/feature/PluginDetailsSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/feature/PluginSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/feature/CreateFeatureProjectOperation.java

This commit removes some of the unused attributes of plugin element, which are redundant and are never read from a feature.xml file: install-size, download size and unpack attributes.
Fixes: [730](https://github.com/eclipse-pde/eclipse.pde/issues/730)

Remove unused attributes in auto-generated feature.xml

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/product/BaseProductCreationOperation.java

Uses 1.0.0.qualifier a version for a newly created product configuration file, as this is required for a pomless Tycho build and other PDE artifacts are also using this number.
Fixes #851

Adds a version for a newly created product configuration file

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/ProductEditor.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties

Mixed products can not be exported from the workspace (at the moment).
In order to avoid later errors, disable the export action in the Product-Editor for mixed products.
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/825

Disable workspace export action for mixed products

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsClasspathContainer.java

Currently we rely on the Manifest to discover all required items but that do not work for items that are not referenced inside the manifest.
This handles the BND Buildpath/Testpath as if it was part of the traditional Secondary Dependencies.

Consider the BND Buildpath/Testpath as extra items in the container

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/iproduct/IProductPlugin.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/product/ProductPlugin.java

The PDE Product Editor used to add a `fragment` attribute to plugin elements in `*.product` files, but the attribute is unused for a long time.
Relates to https://github.com/eclipse-equinox/p2/pull/378

Remove unnecessary 'fragment' attribute of plugin-elements in products

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java

https://github.com/eclipse-pde/eclipse.pde/issues/875

Add Oomph's bundle pools to PDE's artifact repositories for resolution

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java

Fixes https://github.com/eclipse-pde/eclipse.pde/issues/881

Add local artifact repositories for resolution

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/TracingOptionsManager.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/TracingBlock.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties
ui/org.eclipse.pde.ui/src/org/eclipse/pde/ui/launcher/TracingTab.java

The progress indicator uses `IProgressMonitor.UNKNOWN` as the total amount of work because the (sometimes) long running operation is deep in the call stack: it goes all the way down to the `TracingOptionsManager` in `org.eclipse.pde.core` (dependency issues).
The operation can **not** be canceled.
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/679

Show a progress indicator when opening a PDE run configuration.

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/schema/SchemaInclude.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/schema/SchemaEditor.java

Even though no search path is provided we need to decode the URL and see if we can find the schema in the current workspace.
Also fixes an issue where schema can't be opened by double click on linux.
Fix https://github.com/eclipse-pde/eclipse.pde/issues/890

Use a default schema provider without path in case none is supplied

---

build/org.eclipse.pde.build.tests/META-INF/MANIFEST.MF
build/org.eclipse.pde.build.tests/src/org/eclipse/pde/build/internal/tests/p2/P2Tests.java
build/org.eclipse.pde.build.tests/src/org/eclipse/pde/build/tests/PDETestCase.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/FeatureGenerator.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/ShapeAdvisor.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/Utils.java

- set PDE generator to assume "unpack" attribute from bundles to be "false" by default.
- additionally adopted testBug263272() to ignore "unpack=false" instructions from the feature.
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/884

Assume bundle shape as jar by default

---

ui/org.eclipse.pde.ui/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui/plugin.xml
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/bndtools/BndCompletionProcessor.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/bndtools/BndScanner.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/bndtools/MacroRule.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/bnd/BNDPresentationReconciler.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/bnd/BndBuildPathAutoCompleteProcessor.java

Currently there is no syntax-highlight when PDE shows the bnd instruction files.
This connects the highlight/code completion form the bndtools project with the source page to provide completion and syntax coloring.
This is how this looks like:
Fix https://github.com/eclipse-pde/eclipse.pde/issues/701
I'll open an CQ now to get further assistance on if/how we can (temporary) copy/use the code from bndtools.

Add syntax highlight from adapted from bnd-tools

---

build/org.eclipse.pde.build.tests/src/org/eclipse/pde/build/internal/tests/AssembleTests.java
build/org.eclipse.pde.build.tests/src/org/eclipse/pde/build/internal/tests/ProductTests.java
build/org.eclipse.pde.build.tests/src/org/eclipse/pde/build/internal/tests/ScriptGenerationTests.java
build/org.eclipse.pde.build.tests/src/org/eclipse/pde/build/internal/tests/SourceTests.java
build/org.eclipse.pde.build.tests/src/org/eclipse/pde/build/tests/PDETestCase.java

Adopted test expectations to changes made in
1765416677a731a710a9eb43524b4bd88f89b752, where PDE exports bundles as jars by default (unless "Eclipse-BundleShape: dir" is specified in manifest or other preconditions force bundle to be a directory).
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/884

New PDE test fails since I20231105-1800

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/FeatureErrorReporter.java

The validator currently produces an error when it find the referenced plugin but the plugin is a fragment. This is wrong behavior for the latest implementation that makes no distinction between plugins versus fragments.
https://github.com/eclipse-pde/eclipse.pde/issues/915

FeatureErrorReporter.validatePluginExists should recognized fragments

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/ProductInfoSection.java

Reported in #907 that loading of target platform and de-selecting it in the preference can lead to a deadlock. With this change the update of the ProductInfoSection happens with async.

Async update in product editor to prevent deadlock

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/TracingOptionsManager.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/TracingBlock.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties
ui/org.eclipse.pde.ui/src/org/eclipse/pde/ui/launcher/TracingTab.java

See https://github.com/eclipse-platform/eclipse.platform/issues/859 and in particular https://github.com/eclipse-platform/eclipse.platform/issues/859#issuecomment-1814650741.
This reverts commit 7c1f0ed1479916ffe425a87e2fae689dbb72975a from #674. The change introduced a regression causing Tracing tabs not to be initialized properly in specific situation. It requires an update to the Eclipse platform, which will not be integrated into the upcoming release anymore. Therefore, the change is reverted for the release to be reapplied after the next release.
The effect of reverting the change will be a loss of the performance improvement in the launch configurations dialog that was gained by the change.

Revert "Postpone long-running operations to the activation of the "Tracing" tab."

---

org.eclipse.pde.doc.user/pom.xml

As the javadoc changes every build because of timestamp we can not reliable baseline compare it.

Add ignore pattern for the javadoc parts of the doc bundle

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/provisional/ApiPlugin.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/provisional/ISessionManager.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/provisional/problems/IApiProblem.java
apitools/org.eclipse.pde.api.tools/src_ant/org/eclipse/pde/api/tools/internal/tasks/APIToolsAnalysisTask.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java
ui/org.eclipse.pde.core/src_ant/org/eclipse/pde/internal/core/ant/ConvertSchemaToHTML.java

The commit attempts to fix the broken code tags in Javadocs across various files in eclipse.pde.
Inspired by: #928

Fixing broken code tags in Javadoc

---

ui/org.eclipse.pde.core/META-INF/MANIFEST.MF
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndBuilder.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndErrorReporter.java

Currently PDE only builds the "main bundle" but not sub-bundles, this adds support for building these as well.

Support sub bundles build

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/AbstractPluginBlock.java

While configuring launch/debug, the number of plugins selected (under plug-ins tab) is not updated when
i) only show selected option is on,
ii) top level checkbox is used instead of individual checkboxes for plugins.
This PR identifies the check state of the top level controls and makes sure the 
plugin count is computed / reset appropriately.
Fixes: [668](https://github.com/eclipse-pde/eclipse.pde/issues/668)

Display correct plugin selection count under only-show-selected option

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/TracingOptionsManager.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/TracingBlock.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties
ui/org.eclipse.pde.ui/src/org/eclipse/pde/ui/launcher/TracingTab.java

Recreate #674 which was reverted in #925.
Needs:
Fixes to https://github.com/eclipse-pde/eclipse.pde/issues/679

Recreate #674: Postpone long-running operations to the activation of the "Tracing" tab.

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/AddBundleContainerSelectionPage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/WizardElement.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/extension/NewExtensionRegistryReader.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/plugin/NewLibraryPluginProjectWizard.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/plugin/NewPluginProjectWizard.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/ui/templates/NewPluginProjectFromTemplateWizard.java

Currently WizardElement are created based on slightly different precondition checks, beside that, there is even one factory method but only used in one place.
This unify the access to always using the factory method and instead passing the required attributes to check as parameters.

Unify creation of WizardElements

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PDECore.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndWorkspaceServiceFactory.java

Some shared component want to discover the available workspace and do so by searching for Workspace in the service registry.
This adds a service factory that supply the PDE Bnd Workspace in case it is requested by a component.

Add Bnd Workspace ServiceFactory

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndBuilder.java

If subbundles are not specified bnd includes the main builder in the list and then an additional jar is created in the root of the project.
This now skip the subbundle if the builder equals the project builder.

Fix subbundles build

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/TargetRepository.java

Currently we return the raw BundleDescription (Resource) but the spec requires that all Resource in a Repository needs to implement RepositoryContent, beside that each resource should provide a content capability.
This now wraps all BundleDescription in a class that implements Resource and RepositoryContent and enhances the BundleDescription with a content capability.

Supply RepositoryContent / Content Capability

---

.github/workflows/licensecheck.yml

FYI @akurtakov @merks @HannesWell

Enable License Check for PDE

---

build/org.eclipse.pde.build.tests/META-INF/MANIFEST.MF
build/org.eclipse.pde.build.tests/META-INF/p2.inf
build/org.eclipse.pde.build.tests/build.properties
build/org.eclipse.pde.build.tests/pom.xml
build/org.eclipse.pde.build.tests/src/org/eclipse/pde/build/internal/tests/Utils.java

This is a fresh attempt based on
- https://github.com/eclipse-pde/eclipse.pde/pull/927
with some progress made here
- https://github.com/eclipse-pde/eclipse.pde/pull/933
but that was a dead end I think instead one should try to add a `category.xml` with another execution that mirrors into the "deltapack folder" so if the test executes in `target/work` the goal would be to have a folder `target/deltapack/eclipse` that mirrors everything needed as the "deltapack".

Run some pde.build tests with Tycho (second attempt)

---

build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/AbstractScriptGenerator.java

https://github.com/eclipse-pde/eclipse.pde/issues/967

AbstractScriptGenerator.newAntScript: revert close stream #967

---

.github/workflows/ci.yml
.github/workflows/licensecheck.yml

and fix project id...
the review part needs to be merged to master to be fully tested.
now it nicely integrates with the other checks.

Separate the license checks in a check and and review part

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/InstallableUnitGenerator.java

A call to BundlesAction.createBundleDescription() returns null, if the manifest of the current bundle contains invalid headers (e.g. the same package is imported twice).
If left unchecked, this causes an unhandled NullPointerException a few lines further down. Add an explicit null, in order to simply skip this invalid bundle.

Skip target bundles with invalid manifest during IU generation #996

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/VirtualArtifactRepository.java

The implementation currently assumes all bundles are jars, but bundles from the shared bundle pool may be unpacked as folders.
https://github.com/eclipse-pde/eclipse.pde/pull/962

Handle bundle folders in VirtualArtifactRepository.transferArtifact

---

ui/org.eclipse.pde.core/META-INF/p2.inf

PDE effectively requires the org.eclipse.osgi.compatibility.state fragment but has no way to declare this requirement in a provisioned install setup so it must be given manually or by a feature.
This adds a p2.inf to ensure it is always included when installing pde.core bundle.

Add a requirement to the org.eclipse.osgi.compatibility.state fragment

---

ui/org.eclipse.pde.ui.templates/templates_3.1/preferences/java/$pageClassName$.java
ui/org.eclipse.pde.ui.templates/templates_3.1/preferences/java/PreferenceInitializer.java

The current template assumes that the plug-in has an activator. As we do not use activators anymore in the default plug-in template, we should also adjust this template.
Plus getting rid of NON-Javadoc

Fixes PDE preference page template

---

ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/launcher/AllLauncherTests.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/launcher/ValidationDialogTest.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/PluginStatusDialog.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/PluginValidationStatusHandler.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties

Introduced a new link in validation dialog to open the current launch configuration.
Fixes: https://github.com/eclipse-pde/eclipse.pde/issues/305

Validation dialog - Edit launch configuration link

---

ui/org.eclipse.pde.core/text/org/eclipse/pde/internal/core/text/bundle/ImportPackageObject.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/correction/java/JavaResolutionFactory.java

 This commit resets the micro-version to ‘0’ while importing packages as part of quick fix, as it is not relevant. 
Fixes: https://github.com/eclipse-pde/eclipse.pde/issues/401

Strip micro-version and add upper bound when adding package imports

---

ds/org.eclipse.pde.ds.annotations/.gitignore

pde.ds.annotations has main and test sources, which have 2 separate bin directories. The second bin directory should be gitignored.

Gitignore test classes directory

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/IUBundleContainer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/IULocationFactory.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetPersistence35Helper.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetPersistence36Helper.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetPlatformService.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/IUFactory.java

Currently the IU location is updated in-place that has several drawbacks:
- we need to synchronize a to not mess up things
- cached items in the object can getting stale and drip into new state
- equals and hasCode can become unstable over time
to overcome this the code is changed in a way that an update is performed on a copy of the current state and a new object is returned and used to perform the update.

Fixup IU location update handling

---

apitools/org.eclipse.pde.api.tools/src_ant/org/eclipse/pde/api/tools/internal/tasks/APIToolsAnalysisTask.java
apitools/org.eclipse.pde.api.tools/src_ant/org/eclipse/pde/api/tools/internal/tasks/AnalysisReportConversionTask.java
apitools/org.eclipse.pde.api.tools/src_ant/org/eclipse/pde/api/tools/internal/tasks/MissingRefProblemsTask.java

As reported at https://download.eclipse.org/eclipse/downloads/drops4/I20240103-1800/compilelogs/plugins/org.eclipse.pde.api.tools_1.3.300.v20231213-1508/lib_apitooling-ant.jar.html#OTHER_WARNINGS

Fix compiler warnings in pde apitools tasks

---

Jenkinsfile
org.eclipse.pde.doc.user/pom.xml

Currently the api directory is not cleaned so it can potentially contain stale data. Beside that javadoc and copy goal where bound to the same phases what can have odering side effects in maven.

Clean the api directory and bind javadoc and copy to different phases

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java

Guard the use such that -Dpde.usePoolsInfo=false can be used to disable the behavior.
https://github.com/eclipse-equinox/p2/issues/410

Use RepositoryHelper.getWorkspaceBundlePools to find all workspace pools

---

ui/org.eclipse.pde.genericeditor.extension.tests/src/org/eclipse/pde/genericeditor/extension/tests/AbstractTargetEditorTest.java

Use try with resources and actually mark the class as abstract so it's not considered for running by JUnit.
Warning reported in I-builds like
https://download.eclipse.org/eclipse/downloads/drops4/I20240112-1800/compilelogs/plugins/org.eclipse.pde.genericeditor.extension.tests_1.2.300.v20231214-1521/@dot.html#OTHER_WARNINGS

Fix warnings in AbstractTargetEditorTest

---

ds/org.eclipse.pde.ds.tck/pom.xml

Currently there are validation errors because of
https://github.com/osgi/osgi/issues/636
This disables the output to not pollute the log with messages not realted to the test.

Don't print markers to not pollute the maven logs

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ManifestEditor.java

Currently if the ManifestEditor is opened on an input that does not match a local file a NPE can occur seen with JGit and open from staging view a pde.bnd file.

Fix NPE in ManifestEditor if none match

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiAnnotationsClasspathContributor.java
ui/org.eclipse.pde.core/.settings/.api_filters
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/plugin/PluginRegistry.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/ClasspathUtilCore.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/annotations/OSGiAnnotationsClasspathContributor.java

Currently, if a annotation project is part of the workspace (most notable (org.eclipse.pde.api.tools.annotations) it currently does not resolve the binary folders correctly.
This fixes the conversion of plugin models to classpath entries by check if a build model is available and if found uses the binary folders as classpath entries instead of the base location.

Fix lookup of workspace located annotation providers

---

ui/org.eclipse.pde.core/.settings/.api_filters
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsClasspathContainer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndProjectManager.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/correction/java/AddPdeClasspathContainerClasspathFixProposal.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/correction/java/UnresolvedImportFixProcessor.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties

Currently if one imports a blain bnd-project the classpath is not setup unless one have some other tooling installed (e.g. bndtools)
This now adds support for evaluate the bnd project in case it is a "plain" bnd workspace project and adds the required items to the classpath container if it was added to the project.
To effectively use this feature one would additionally need:

Add support for using classpath of plain bnd projects

---

ui/org.eclipse.pde.ui/plugin.properties
ui/org.eclipse.pde.ui/plugin.xml

removes warnings like "The value for attribute 'name' is not externalized.  The value must begin with %"

externalize plugin.xml strings

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/P2Utils.java
ui/org.eclipse.pde.launching/META-INF/MANIFEST.MF
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/BundleLauncherHelper.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/LaunchConfigurationHelper.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/EclipseApplicationLaunchConfiguration.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/IPDELauncherConstants.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/JUnitLaunchConfigurationDelegate.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/LaunchAction.java

Currently if one selects the option to allow installation of new software there is the problem that only plugins are available in the generated profiles. This makes testing of install scenarios possible but updates can not be tested because effectively nothing user visible is installed.
This now do two things:
1) generates feature group IUs and install them into the profile
2) if started from a product derive the root features from it

Install features into the profile

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/exports/ProductExportOperation.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/iproduct/IProduct.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/product/Product.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/GeneralInfoSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties

Currently if one wants to include a JRE it is needed to specify a concrete EE for each of the linux/win/mac what is quite cumbersome and could easily forgotten to update.
Instead this adds a new flag "includeJRE" in the product that enables this for all os at once and always uses the default vm (what is the one from the target platform or user chosen default).
This will also make it easier for Tools like Tycho that already investigate the 'includeLaunchers' flag.

Add an option to the product editor to flag it contain a JRE

---

releng/org.eclipse.pde.setup/PDE.setup

Follow-up of https://github.com/eclipse-pde/eclipse.pde/pull/1081.
@merks can you tell why the e4.tools project are not imported in the WS? I actually assumed that the targlet task should do that without adjustments.

Adapt PDE's Oomph setupt to e4.tools merge

---

Jenkinsfile

... currently no baseline compare errors so have to wait for the problem to reoccur.

Capture comparator errors and compile logs

---

ui/org.eclipse.pde.junit.runtime/META-INF/MANIFEST.MF
ui/org.eclipse.pde.junit.runtime/src/org/eclipse/pde/internal/junit/runtime/RemotePluginTestRunner.java

Currently, it is possible that the `RemotePluginTestRunner` loads bundles with "incompatible" test engines. This means, the engine is version-incompatible with the `TestEngine` interface. In such a case, the execution will fail,  because the `ServiceLoader` tries to load this engine as a provider for the `TestEngine` service but fails because it cannot assign the engine to the `TestEngine` interface. One such case is the execution of tests with Tycho, which can use a different JUnit version than the one used in the JDT test bundles. 
This change ensures that bundles providing incompatible engines are not added to the class loader used for executing the test to ensure that service loading for the engines does not fail.
An example for the error is the execution of session tests with JUnit …

Provide only compatible JUnit 5 test engines in RemotePluginTestRunner

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiBaselineManager.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ApiBaseline.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/provisional/comparator/ApiComparator.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/util/Util.java

Before the change ApiBaseline.resolveSystemLibrary() did following: 
1) Collected all JVM installs matching all given execution environments id's
2) Iterated over all found installs **in random order** 
3) For every JVM install ApiBaseline tried to initialize itself from that install
4) The condition used to stop the loop (almost) never worked as it always compared either null or previously initialized JVM with the current one, so for all **different** JVM's ApiBaseline  initialized itself from that JVM - and that in random order.
5) The **last** iterated JVM install defined the maximal "supported" execution environment. In case of installed Java 1.8, 11, 17, 21 it could be **any one** if the target platform contained bundles required different execution environments.
With that, SWT …

API tooling reports 300 false positive errors on SWT

---

Jenkinsfile
e4tools/features/org.eclipse.e4.tools.persistence.feature/forceQualifierUpdate.txt
repository/category.xml

Using https://download.eclipse.org/pde/builds/master/ as destination so it can be tested more broadly.
Mainly motivated to have a permanent download space which wasn't there as discovered in
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4172

Write latest master build to downloads.eclipse.org

---

ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/core/tests/internal/classpath/ClasspathResolutionTest.java

.testImportSystemPackageDoesntAddExtraBundleJava11() to use public API instead of type cast.
Failing since I20240130-1800
Java nature and java project are now implemented as separate instances https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1916

fix ClasspathResolutionTest

---

ui/org.eclipse.pde.bnd.ui/META-INF/MANIFEST.MF
ui/org.eclipse.pde.bnd.ui/plugin.xml
ui/org.eclipse.pde.bnd.ui/src/org/eclipse/pde/bnd/ui/OSGiPropertyTester.java
ui/org.eclipse.pde.bnd.ui/src/org/eclipse/pde/bnd/ui/Resources.java
ui/org.eclipse.pde.ui/plugin.xml

Currently the UnresolvedImportFixProcessor can only work on a project if it has the org.eclipse.pde.PluginNature but actually we can work on many different kind of projects independent of the nature.
This now adds a new property tester that evaluates the project if it matches a certain layout than a nature and allows to enable the classpath container on them on demand.
Assume you have imported a project that previously required bndtools to work and want to perform some small changes, at the moment you need to install another tooling, configure it and hope it does not interfere with your existing Eclipse install.
Now the following is possible, you just go to the compile problem and choose "Fix Project Setup..."
then you are presented with adding a Plugin-Dependencies Container (from pde …

Add an OSGi property tester to check if action should apply

---

ui/org.eclipse.pde.spy.model/forceQualifierUpdate.txt

After https://github.com/eclipse-pde/eclipse.pde/pull/1060 got merged the build failed due to signing. This is similar issue like eclipse-platform/eclipse.platform.releng.aggregator#1673 so this is a simple check whether a "touch" would be enough.

Touch o.e.pde.spy.model

---

pom.xml
repository/category.xml

The repository is not really useful for the aggregator build therefore it can be moved to the individual bundles, also sources don't need to be specified directly in the category.xml

Move the repository module to the individual bundles build

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PDECore.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsClasspathContainer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndResourceChangeListener.java

Currently we check for a fixed combination of filename and project nature but the RequiredPluginsClasspathContainer can be used in other context as well.
To mitigate this, the classpath container sets a session property when it has used a bnd file to update the classpath that is then checked in the resource listener to decide if the classpath container needs to be updated.

Update the classpath based on a session property

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/P2Utils.java

When features include os-specific fragments, those included bundles may not be present in the map of plug-ins.  In general it's good to avoid an NPE if/when a map entry is missing.

P2Utils.createFeatureIUs should guard against missing map entries

---

org.eclipse.pde.doc.user/forceQualifierUpdate.txt
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/IClasspathContributor.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PDECore.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsClasspathContainer.java

Currently IClasspathContributor can only be contributed by an extension point, this is often not very flexible and one can't use OSGi DI techniques like declarative services.
This adds support for contribute IClasspathContributor as OSGi services as well.

Add support to contribute IClasspathContributor as an OSGi service

---

ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/DSAnnotationCompilationParticipant.java
ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/DSAnnotationPropertyPage.java
ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/DSAnnotationVersion.java
ds/org.eclipse.pde.ds.core/src/org/eclipse/pde/internal/ds/core/text/DSComponent.java

Currently if only the namespace (or prefix) changes this is not considered a change in the DS generator and the changes are discarded.
This checks if there is a change in then fires a change event.
Fix https://github.com/eclipse-pde/eclipse.pde/issues/1112

Fire change event when the namespace (prefix) changes

---

apitools/org.eclipse.pde.api.tools.annotations/src/org/eclipse/pde/api/tools/annotations/NoExtend.java
apitools/org.eclipse.pde.api.tools.annotations/src/org/eclipse/pde/api/tools/annotations/NoImplement.java
apitools/org.eclipse.pde.api.tools.annotations/src/org/eclipse/pde/api/tools/annotations/NoInstantiate.java
apitools/org.eclipse.pde.api.tools.annotations/src/org/eclipse/pde/api/tools/annotations/NoOverride.java
apitools/org.eclipse.pde.api.tools.annotations/src/org/eclipse/pde/api/tools/annotations/NoReference.java
org.eclipse.pde.doc.user/forceQualifierUpdate.txt

This allows users of the annotations to provide contextual information to clients about why the annotations is applied.
This is common for users of the javadoc-annotations, but at the moment not possible when using the java-annotations.
Later PDE's API-Tools could also provide that information to developers of clients.
Instead of
```
/**
* The doc.
* @noextend This class is not intended to be sub-classed by clients.
*/
public abstract class MyClass {
```
one can use 
```
/**
* The doc.
*/
@NoExtend("This class is not intended to be sub-classed by clients.")
public abstract class MyClass {
```

Add message value to API-tools annotations

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetDefinition.java

Implementations of ITargetLocation may have an equals() implementation that does not compare all their serialized attributes. In particular, this is true for MavenTargetLocation, causing any check for redundancy upon the 'Apply' button in the Target Platform Preferences Editor to fail, causing each time:
- the .target file to be rewritten
- the Target Platform State to be re-evaluated
Instead, we compare along the serialized value of ITargetLocation, ignoring any particular order of target locations as well.
This originates in the discussion at https://github.com/eclipse-m2e/m2e-core/pull/1649#issuecomment-1926831214

TargetDefinition: compare target locations along serialized value

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndResourceChangeListener.java

which is the case in Tests like BasicAliasTest

Avoid silent CoreExceptions while project is closed

---

build/org.eclipse.pde.build.tests/src/org/eclipse/pde/build/internal/tests/ScriptGenerationTests.java

The test fails on some linux systems for unknown reasons.
Fix https://github.com/eclipse-pde/eclipse.pde/issues/1119

Disable ScriptGenerationTests#testBug238177

---

build/org.eclipse.pde.build.tests/pom.xml

Currently we use an extra director step to provision the installation of the test runtime, with the new option to specify additional units and repositories in Tycho we can combine the step into the test execution.

Use extra repository + extra install units to provision the test runtime

---

build/org.eclipse.pde.build.tests/src/org/eclipse/pde/build/internal/tests/ScriptGenerationTests.java

using Junit's Assume facility.
Relates to https://github.com/eclipse-pde/eclipse.pde/issues/1119

Disable ScriptGenerationTests#testBug238177 only on Linux

---

apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/actions/DeltaSession.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/APIFileGenerator.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/BaseApiAnalyzer.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/BundleComponent.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/provisional/comparator/ApiComparator.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/util/Util.java

Now that https://github.com/eclipse-platform/eclipse.platform.swt/pull/1008 is submitted, I think we can remove the special treatment of SWT and its fragments, since they should simply be compared against the baseline as they are.
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/1084

Remove special treatment of org.eclipse.swt in API-Tools

---

build/org.eclipse.pde.build.tests/pom.xml
build/org.eclipse.pde.build.tests/test-sdk.product

Currently we use the sdk product to create the test runtime, this has the drawback that we can not use the current build pde code but always using the latest from the ibuilds,
This uses an own copy of the sdk product to setup the necessary
test runtime so we can customize this as required.

Use a dedicated test project that allows updating pde feature

---

ui/org.eclipse.pde.bnd.ui/META-INF/MANIFEST.MF
ui/org.eclipse.pde.bnd.ui/plugin.xml
ui/org.eclipse.pde.bnd.ui/src/org/eclipse/pde/bnd/ui/autocomplete/AddBundleCompletionProposal.java
ui/org.eclipse.pde.bnd.ui/src/org/eclipse/pde/bnd/ui/quickfix/BuildpathQuickFixProcessor.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/correction/java/QuickFixProcessor.java

Now we have more and more features in this bundle it seems good to structure its packages more as we have already done for the other imported parts.
This moves the bundle completion proposal and buildpath quickfix to their own packages and removes the export of org.eclipse.pde.bnd.ui what should only be used internally.

Move the AddBundleCompletionProposal and BuildpathQuickFixProcessor

---

ui/org.eclipse.pde.core/META-INF/MANIFEST.MF
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/ManifestConsistencyChecker.java

but log a IllegalStateException() to find out how that happens.
https://github.com/eclipse-pde/eclipse.pde/issues/1185

Do not create "build.properties does not exist" marker on non-PDE #1185

---

ui/org.eclipse.pde.ui/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/views/imagebrowser/ImageElement.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/views/imagebrowser/repositories/AbstractRepository.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/views/imagebrowser/repositories/WorkspaceRepository.java

The WorkspaceRepository class used by this view initializes the image data for all images that are found in the workspace. This approach doesn't scale very well and may cause OutOfMemory errors on large projects.
By using those soft references in combination with a lazy initialization, we can reduce the overall footprint on low-memory systems, without losing most of the benefits gained by caching.
~~Note that this approach doesn't work for images retrieved from jar files, as the image data can't be reloaded once the archive has been closed again which is why hard references are mandatory here.~~
One noteworthy difference to the old implementation that invalid/broken images are no longer skipped. Instead, the default image data of the ImageDescriptor (also used by e.g. the …

Use soft references to cache image data in Plug-in Image Browser

---

apitools/org.eclipse.pde.api.tools/build.properties
apitools/org.eclipse.pde.api.tools/fixed_api_descriptions/org.eclipse.swt.cocoa.macosx.aarch64_3.125.0.v20240227-1638.api_description
apitools/org.eclipse.pde.api.tools/fixed_api_descriptions/org.eclipse.swt.cocoa.macosx.x86_64_3.125.0.v20240227-1638.api_description
apitools/org.eclipse.pde.api.tools/fixed_api_descriptions/org.eclipse.swt.gtk.linux.aarch64_3.125.0.v20240227-1638.api_description
apitools/org.eclipse.pde.api.tools/fixed_api_descriptions/org.eclipse.swt.gtk.linux.ppc64le_3.125.0.v20240227-1638.api_description
apitools/org.eclipse.pde.api.tools/fixed_api_descriptions/org.eclipse.swt.gtk.linux.x86_64_3.125.0.v20240227-1638.api_description
apitools/org.eclipse.pde.api.tools/fixed_api_descriptions/org.eclipse.swt.win32.win32.x86_64_3.125.0.v20240227-1638.api_description
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/BundleComponent.java

Added SWT API description files from last good 4.31 build I20240207-0610 https://download.eclipse.org/eclipse/updates/4.31-I-builds/I20240207-0610/plugins/
The files will be loaded instead of "empty" SWT API description files shipped with 4.31 RC2 build (3.125.0.v20240227-1638).
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/1187

Workaround for missing 4.31 SWT API descriptions

---

apitools/org.eclipse.pde.api.tools/build.properties

Forgotten in https://github.com/eclipse-pde/eclipse.pde/pull/1116.

Fix escaping of line-break in api.tools/build.properties

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/FilterStore.java

See https://github.com/eclipse-pde/eclipse.pde/pull/1199/files#r1527617764

Restore internal FilterStore.fFilterMap field to un-break Tycho's api-analysis

---

ui/org.eclipse.pde.ui.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.tests/pom.xml
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/core/tests/internal/classpath/ClasspathResolutionTest.java

Currently the tests are missing some indirect requirements defined in the feature on their test, this adds the org.eclipse.pde.feature to make sure all declared items are pulled in.
See 
- https://github.com/eclipse-pde/eclipse.pde/issues/1205

Add org.eclipse.pde.feature dependency to pull additional requirements

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/search/UseReportConverter.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/search/UseScanManager.java

In UseScanManager.isValidArchive() the jar/zip-file was closed too early making it impossible to read from it.
And in UseReportConverter.getXML() the default look up looked not at the wrong file when computing the filtered-counts.
Since especially the former seems to be broken for some time I wonder if API use-scans are a  used feature?
Does anybody know if the is used for the Eclipse SDK or SimRel? With that I could verify if this really is fixed (at the moment this is just an anticipated fix from looking at the code). Maybe @merks or @iloveeclipse?

Fix UseScanManager.isValidArchive() and UseReportConverter

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/MinimalState.java

Do not force PDE builder on projects without PDE nature.
Fixes #1214.

Do not build unrelated projects #1214

---

ui/org.eclipse.pde.ui/plugin.xml

This enables syntax highlighting for .target files in compare editor.
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/1222

Register PluginContentMergeViewerCreator for .target content type

---

ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/reconciler/folding/FoldingReconcilerStrategy.java

The exception below is printed to standard error every time a generic editor diff contribution is used in compare editor for target files. I assume it never worked as designed with TargetPlatformFoldingReconciler, so just add a NPE guard to prevent unhandled exceptions / printouts.
```
Exception in thread
"org.eclipse.pde.internal.genericeditor.target.extension.reconciler.folding.TargetPlatformFoldingReconciler"
java.lang.NullPointerException: Cannot invoke
"org.eclipse.jface.text.source.projection.ProjectionViewer.getProjectionAnnotationModel()"
because "this.projectionViewer" is null
at org.eclipse.pde.internal.genericeditor.target.extension.reconciler.folding.FoldingReconcilerStrategy.initialReconcile(FoldingReconcilerStrategy.java:63)
at …
```

Avoid unhandled NPEs in FoldingReconcilerStrategy

---

e4tools/bundles/org.eclipse.e4.tools/src/org/eclipse/e4/internal/tools/wizards/classes/AbstractNewClassPage.java

The replacement one has one more parameter previewEnabled but it's fine to pass null to have it disabled as per javadoc.

Stop using deprecated JavaConventions.validateJavaTypeName method

---

build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java

With https://github.com/eclipse-equinox/equinox/pull/596 the JRE-1.1 profile embedded in Equinox was updated to have the expected system-packages.
Therefore the hard-coded ones in PDE can be removed.
See also https://github.com/eclipse-pde/eclipse.pde/issues/1231#issuecomment-2057561119.

Rely on system-packages of Equinox JRE-1.1 profile

---

ui/org.eclipse.pde.unittest.junit/plugin.xml
ui/org.eclipse.pde.unittest.junit/src/org/eclipse/pde/unittest/junit/internal/launcher/JUnitPluginTabGroup.java
ui/org.eclipse.pde.unittest.junit/src/org/eclipse/pde/unittest/junit/launcher/JUnitPluginTestTab.java

All the tabs are already hooked for prototype support (shared with other launch configs that support prototypes) thus only the final enable and show the configuration tab is needed.

Allow launch prototypes in JUnit Plug-in Test (generic Test view)

---

ui/org.eclipse.pde.unittest.junit/plugin.properties

"(generic Test view)" looks very bad in the UI.

Improve Generic Test view label capitalization

---

org.eclipse.pde.doc.user/META-INF/MANIFEST.MF
org.eclipse.pde.doc.user/pom.xml
ui/org.eclipse.pde.ui/src/org/eclipse/pde/ui/launcher/PluginsTab.java

Move the long running operations in the `PluginsTab` from `initializeFrom` to `activated`. Only run these operations the first time the tab is activated in order to:
a. Only run them when the tab is actually selected
b. Not run them again if the tab is deselected and selected again (without leaving the current launch configuration)
* Create 2 **new** launch configurations from inside the _Run Configurations_ dialog: one _Eclipse Application_ (1) and one _JUnit-Plugin Test_ (2)
* Select the `Plugins` tab in one of them and make some changes (save them)
* Move to the other configuration --> The `Plugins` tab should be selected and it should look fine. The activation should **not** be skipped _i.e._ it should **not** hit the `return;` in line 167
* Move back to the first configuration --> …

Move long running operations to the activation of the PluginsTab

---

org.eclipse.pde.doc.user/forceQualifierUpdate.txt
ui/org.eclipse.pde.core/META-INF/MANIFEST.MF
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/P2Utils.java
ui/org.eclipse.pde.launching/META-INF/MANIFEST.MF
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/LaunchConfigurationHelper.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/IPDELauncherConstants.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/LaunchAction.java

Currently PDE published already root-feature what is already a great win. But in a usual product install there is also one unit for the product and because that is missing it can't be updated in a launched product from the IDE.
This adds a very bare unit to the profile by just publish the product id/version/name, but already allows that P2 pick up the unit when an update is requested.

Publish a product IU into the PDE launch profile

---

org.eclipse.pde.doc.user/forceQualifierUpdate.txt
ui/org.eclipse.pde.ui/src/org/eclipse/pde/ui/launcher/PluginsTab.java

This change reverts main change from commit 98a58656a74bd163c8f4ad8f7a36dc492ac67e1c because it caused a severe regression.
See https://github.com/eclipse-pde/eclipse.pde/pull/1233
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/1250

Revert "Move long running operations to the activation of the PluginsTab"

---

org.eclipse.pde.doc.user/guide/tools/target_shared/location_edit_site_wizard.htm
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/IUBundleContainer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/IULocationFactory.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetDefinitionPersistenceHelper.java
ui/org.eclipse.pde.genericeditor.extension.tests/src/org/eclipse/pde/genericeditor/extension/tests/AttributeNameCompletionTests.java
ui/org.eclipse.pde.genericeditor.extension.tests/testing-files/target-files/AttributeNamesFullTestCaseTarget.txt
ui/org.eclipse.pde.genericeditor.extension.tests/testing-files/target-files/ContainerContentsTestCaseTarget.txt
ui/org.eclipse.pde.genericeditor.extension.tests/testing-files/target-files/MultipleContainersSameRepoTestCaseTarget.txt
ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/autocomplete/processors/AttributeNameCompletionProcessor.java
ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/model/ITargetConstants.java
ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/reconciler/presentation/TargetPlatformAttributeRule.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/EditIUContainerPage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/Messages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/messages.properties

Note: there might be another way to do this, as I found a few half-wired up places. However,  I couldn't find one while investigating my use case, so I added somewhat simple code that implements my use case.
I'm trying to proxy an entire target platform through an artifact repository, i.e., Nexus. As such, I've defined the software sites in my target platform to point to proxies of my own server. Sadly, it seems like p2 software sites are not necessarily self-contained. Namely, they can contain references to other repositories.
In our case, this causes us to load 122 external repos. Strikingly, most of these come from _disabled_ references. As such I've added some code that would skip over these, let me know if that isn't allowed for some reason.
Using only the enabled references, I still …

Add an option to ignore references

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java

Fix regression in P2TargetUtils

---

ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/AnnotationVisitor.java

Using the full name of the AST element representing a single-element property annotations to derive the property name, makes the generated annotation depend on the way a ComponentPropertyType annotation is applied. For example with fully-qualified name or with the outer-class if it's a inner class.
Instead the simple name of the resolved annotation class should be used as stated in the OSGi compendium spec in '112.8.2.1 Component Property Mapping' [1]:
```
However, if the component property type is a single-element annotation, see 9.7.3 in [7] The Java Language Specification,
Java SE 8 Edition, then the property name for the value method is derived from the name of the component property type
rather than the name of the method.
In this case, the simple name of the component property type, …
```

[DS] Use simple class name for single-element property annotations

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PluginModelManager.java
ui/org.eclipse.pde.ui.templates.tests/src/org/eclipse/pde/ui/templates/tests/TestPDETemplates.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/classpathcontributor/ClasspathContributorTest.java

Setting a classpath container to a project while the workspace tree is locked has the effect that the container is updated but the project is not build at all.
This overrides the hint to run async in such case to make sure the project is build appropriately.

Always run asnyc if the workspace tree is locked

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/ui/launcher/PluginsTab.java

The JavaDoc is outdates and the variable is a null value

Inline variable and remove JavaDoc in PluginsTab

---

build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java

The code in PDE(-build) usually only matches respectively is adapted to content of the profiles provided by the org.eclipse.osgi bundle of the same release and not necessarily of previous or even future releases. For example with https://github.com/eclipse-pde/eclipse.pde/pull/1239 PDE-build now relies on the system.packages provided by the JRE-1.1 profile in o.e.osgi since this release. Of course these profiles are missing in previous versions of o.e.osgi. This causes errors during PDE's product export if an earlier version of o.e.osgi is in the target-platform because the system.packages for the JRE-1.1 are then null/empty.

[PDE-Build] Always use the OSGi profiles provided by the runtime bundle

---

build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java

For wrapped OSGi States obtained from pde.core/ui the Manifest 'Eclipse-BundleShape' entries, besides others, were not copied into the bundle's user-object Properties. This had the consequence that in ShapeAdvisor.getUnpackClause() the value of that entry could never be considered.
https://github.com/eclipse-pde/eclipse.pde/blob/c2d4b0c101bbcb0697edd9b8edf2a1aeb8e71b16/build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/ShapeAdvisor.java#L110-L113
The method only used to return the expected boolean value because of corresponding unpack-attributes in 'plugin' entries of feature.xml files. But since the removal of that otherwise unused attribute in https://github.com/eclipse-pde/eclipse.pde/pull/770 this makeshift was gone and ShapeAdvisor.getUnpackClause() always return false …

[PDE-Build] Copy Eclipse-BundleShape and other headers in wrapped states

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/MinimalState.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/ManifestConsistencyChecker.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/PDEBuilderHelper.java

Currently MinimalState schedules a build for every project that has any PDE nature, this can lead to projects scanned that have no ManifestBuilder enabled at all and creating unrelated warnings.
This now checks if the builder is enabled for the project before scheduling a build. Also the check for possible invalid invocations is moved up so it is triggered even if a build.properties exits.
Fix https://github.com/eclipse-pde/eclipse.pde/issues/1185

Only schedule a build if manifest builder is enabled for project

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/LaunchTerminationStatusHandler.java

This prevents the dialogs to appear behind the possible opened progress dialog (or any other modal dialog).
See https://github.com/eclipse-platform/eclipse.platform/issues/1373

Use proper shell for modal dialogs

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetPlatformService.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/target/LocalTargetDefinitionTests.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/preferences/TargetPlatformPreferencePage.java

TargetPlatformHelper and TargetPlatformService keep separate caches for target definition, resulting in a leak of TargetDefinition objects.
The leak happens when TargetDefinition.resolve() caches data in TargetPlatformHelper.
Fixes #1246

Clean caches upon deletion of a Target Definition #1246

---

ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/target/LocalTargetDefinitionTests.java

And fix LocalTargetDefinitionTests.testDeleteCleansCaches failing in I-builds.
Follow-up on https://github.com/eclipse-pde/eclipse.pde/pull/1247#issuecomment-2119162437.

Enable most LocalTargetDefinitionTests in verification builds

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/product/Product.java

The property should be P_INCLUDE_JRE not P_INCLUDE_LAUNCHERS
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/1278

Fire the correct property in Product#setIncludeJre

---

apitools/org.eclipse.pde.api.tools/META-INF/MANIFEST.MF
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/ReferenceAnalyzer.java

https://github.com/eclipse-pde/eclipse.pde/issues/1289

fix NPE for ReferenceAnalyzer.fIndexedDetectors null #1289

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/BundleComponent.java

https://github.com/eclipse-pde/eclipse.pde/issues/1283

Track whether the manifest of a bundle component has an explicit EE

---

ui/org.eclipse.pde.ui/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/targetdefinition/TargetEditor.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties

This helps when a user wants to switch between target definitions without the need of either navigating to another target definition file or the preference page listing all Target Platforms.
Resolves #1281

Shortcut to Target Platform preferences in editor

---

ds/org.eclipse.pde.ds.ui/META-INF/MANIFEST.MF
ds/org.eclipse.pde.ds.ui/src/org/eclipse/pde/internal/ds/ui/editor/contentassist/DSContentAssistProcessor.java
ds/org.eclipse.pde.ds.ui/src/org/eclipse/pde/internal/ds/ui/parts/ComboPart.java
ua/org.eclipse.pde.ua.ui/META-INF/MANIFEST.MF
ua/org.eclipse.pde.ua.ui/src/org/eclipse/pde/internal/ua/ui/editor/cheatsheet/comp/CompCSMasterTreeSection.java
ua/org.eclipse.pde.ua.ui/src/org/eclipse/pde/internal/ua/ui/editor/cheatsheet/simple/details/SimpleCSCommandComboPart.java
ui/org.eclipse.pde.core/META-INF/MANIFEST.MF
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/ManifestErrorReporter.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/schema/SchemaAttribute.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/launcher/ValidationDialogTest.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/compare/ManifestContentMergeViewer.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/compare/PluginContentMergeViewer.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/build/BuildContentsSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/contentassist/XMLCompletionProposal.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/contentassist/XMLContentAssistProcessor.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/LauncherSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/schema/NewClassCreationWizard.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/text/PluginXMLTextHover.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/text/XMLUtil.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/parts/ComboPart.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/refactoring/PluginManifestChange.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/views/target/StateViewPage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/imports/PluginImportOperation.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/plugin/NewLibraryPluginCreationOperation.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/plugin/PluginContentPage.java

When https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2471 is merged, ecj will signal more casts as unnecessary.
With this PR I suggest to remove affected casts before new errors/warnings will show up in the build.

remove unnecessary casts

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/BundleComponent.java

Currently BundleComponent.isValidBundle() is used to check if a bundle is valid and should be considered for the baseline. If the location points to something that chase no manifest at all (or an invalid manifest) this currently an exception even though the API doc clearly states that "Validity is determined via the existence of a readable manifest file"
This now adds two checks
1) the location points to a file that exits and is larger than zero bytes
2) parsing the manifest from the location do not throw an exception
This error can be seen for example here:
https://ci.eclipse.org/equinox/job/p2/job/PR-524/8/console

BundleComponent.isValidBundle() should no throw if reading manifest fail

---

e4tools/bundles/org.eclipse.e4.tools.emf.ui/META-INF/MANIFEST.MF
e4tools/bundles/org.eclipse.e4.tools.emf.ui/pom.xml
e4tools/bundles/org.eclipse.e4.tools.emf.ui/src/org/eclipse/e4/tools/emf/ui/common/Util.java
e4tools/bundles/org.eclipse.e4.tools.emf.ui/src/org/eclipse/e4/tools/emf/ui/internal/common/component/ControlFactory.java
e4tools/bundles/org.eclipse.e4.tools.emf.ui/src/org/eclipse/e4/tools/emf/ui/internal/common/component/MenuEditor.java
e4tools/bundles/org.eclipse.e4.tools.emf.ui/src/org/eclipse/e4/tools/emf/ui/internal/common/component/MenuItemEditor.java
features/org.eclipse.e4.core.tools.feature/feature.xml

Fix "Unnecessary cast" warnings

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/AbstractProblemDetector.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/BaseApiAnalyzer.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/util/Util.java

https://github.com/eclipse-platform/eclipse.platform.swt/issues/1298

Bypass API analysis for classes from a test classpath entry

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ExecutionEnvironmentSection.java

Drag&drop support was introduced via [Bug 192890](https://bugs.eclipse.org/192890), but only supports reordering of required Execution-Environments in the same Plug-in project.
Because in the vast majority of cases Plug-ins only have one EE defined that feature is only rarely usable. And if a Plug-in project really defines multiple BREEs the Manifest Editor already provides an alternative with the 'Up' and 'Down' buttons next to the table.
While being only rarely usable support D&D support for required EEs makes it more difficult to support OSGi EE requirements in https://github.com/eclipse-pde/eclipse.pde/pull/1318.
Therefore I propose to remove it.
@laeubi, @merks or anbody else, do you have any objections?

Remove rarely usable Drag&Drop of EEs in Manifest-Editor Overview page

---

ui/org.eclipse.pde.core/text/org/eclipse/pde/internal/core/text/bundle/CompositeManifestHeader.java
ui/org.eclipse.pde.core/text/org/eclipse/pde/internal/core/text/bundle/RequiredExecutionEnvironmentHeader.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ExecutionEnvironmentSection.java

Also remove CompositeManifestHeader.removeManifestElement(), which is unused since https://github.com/eclipse-pde/eclipse.pde/pull/1321.

Further clean-up BREE and composite header handling in Manifest Editor

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/ManifestUtils.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/model/bundle/ExecutionEnvironmentTestCase.java

In general the strategy is to consider all osgi.ee requirements of a resource and parse their filter.
For the case of a simple filter like '(&(osgi.ee=JavaSE)(version=17)', probably the majority of cases, a fast-path is provided where the filter is just looked up in a map.
Otherwise each registered execution-environment is matched against the filter and the list of matching EEs is returned.
The new method is intended to support the migration from the Equinox resolver to the OSGi Resources/Wiring API.
It is required for https://github.com/eclipse-pde/eclipse.pde/pull/1302 and https://github.com/eclipse-pde/eclipse.pde/pull/1318

Add utility to derive the BREE of a resource from its EE requirements

---

apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/compatibility/ProjectTypeContainerTests.java
apitools/org.eclipse.pde.api.tools.tests/test-builder/baseline/bundle.b/.classpath
apitools/org.eclipse.pde.api.tools.tests/test-builder/baseline/bundle.b/.project
apitools/org.eclipse.pde.api.tools.tests/test-builder/baseline/bundle.b/META-INF/MANIFEST.MF
apitools/org.eclipse.pde.api.tools.tests/test-builder/baseline/bundle.b/build.properties
apitools/org.eclipse.pde.api.tools.tests/test-builder/baseline/bundle.b/src/test/Stub.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/BundleComponent.java

The API tool only checks the Bundle-RequiredExecutionEnvironment header when comparing the baseline with the workspace bundle. If the EE of the baseline bundle is described via the Require-Capability header, an empty string is compared to the workspace EE, which is treated as an incompatibility.
This also adds a simple test case where the execution environment of two bundles is checked. One bundle uses the  Require-Capability, the other one the Bundle-RequiredExecutionEnvironment header.
Resolves https://github.com/eclipse-pde/eclipse.pde/issues/1301

Fix: API tool reports fictitious changes to execution environment

---

features/org.eclipse.pde.unittest.junit-feature/feature.xml
ui/org.eclipse.pde.launching/META-INF/MANIFEST.MF
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/EclipsePluginValidationOperation.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/LaunchValidationOperation.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/LauncherUtils.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/ProductValidationOperation.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/AbstractPDELaunchConfiguration.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/EclipseApplicationLaunchConfiguration.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/EquinoxLaunchConfiguration.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/JUnitLaunchConfigurationDelegate.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/PluginStatusDialog.java
ui/org.eclipse.pde.unittest.junit/META-INF/MANIFEST.MF
ui/org.eclipse.pde.unittest.junit/src/org/eclipse/pde/unittest/junit/launcher/JUnitPluginLaunchConfigurationDelegate.java

When a launch fails validation, the user is given a link to Edit Launch Configuration. Previously, this link always opened the Edit Run Configurations dialog in Run mode, even if the user initially attempted to Debug. This change ensures that the edit dialog is opening using the original mode.

Open edit launch dialog using correct mode

---

docs/Execution_Environments.md

Removes examples for JRE which do not exist anymore and other very specific cases which also do not exit more, also remove old BREE listing and add one one which are still relevant these days.

Updating Execution_Environments.md to more recent examples

---

ui/org.eclipse.pde.bnd.ui/README.MD

This adds the following readme to explain the pde reusable osgi components
The [bndlib](https://github.com/bndtools/bnd) offers various ways to build better OSGi bundles, this is used in
- felix-bundle-plugin
- bnd-maven-plugin
- Tycho
-  bndtools
- PDE itself
- ...
This plugin offers a set of reusable UI components for these usecase to be integrated with Eclipse IDE in a way that is not specific to a given tooling (e.g. PDE, bndtools, m2e, ...)
and therefore can be shared across these to prevent duplicate efforts, see [here](https://bnd.discourse.group/t/announcement-bnd-and-pde-cooperation/372) for more details.
One problem for such a reusable component is that it usually needs to get holds of some objects in an specific way that is specific to a given tooling.
To mitigate we use the …

Add a readme that explains how to use the pde reusable osgi components

---

.github/workflows/ci.yml
.github/workflows/licensecheck.yml

See https://github.com/eclipse-dash/dash-licenses/issues/302

[Build] Adapt license-check to its move to own eclipse-dash organization

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ExecutionEnvironmentSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties

Fixes : #1178
A new "Modify" button that allows to select the new EE, removes all old ones and updates the classpath in one go.
As part of this, this dialog should then be sorted by EE in descending order (highest EE first):

Add a new "Modify" button to Execution Environment section

---

features/org.eclipse.pde-feature/feature.xml
org.eclipse.pde.doc.user/META-INF/MANIFEST.MF
org.eclipse.pde.doc.user/pom.xml
ui/org.eclipse.pde.core/META-INF/MANIFEST.MF
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/project/IBundleProjectService.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/project/IHostDescription.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/project/IPackageImportDescription.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/project/IRequiredBundleDescription.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/project/BundleProjectService.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/project/HostDescriptoin.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/project/PackageImportDescription.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/project/RequiredBundleDescription.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/project/RequirementSpecification.java

Provide alternatives that are using `org.osgi.framework.VersionRange` and deprecate the existing methods for removal.
This is extracted from https://github.com/eclipse-pde/eclipse.pde/pull/1163 handling only the `simple` cases.
Part of https://github.com/eclipse-pde/eclipse.pde/issues/1069.

Replace project APIs using antiquated Equinox resolver's VersionRange

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/VMUtil.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/PDEMigrationDelegate.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/VMHelper.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/JREBlock.java

This also leverages the changs from
https://github.com/eclipse-equinox/equinox/pull/655

Simplify and clean-up VMUtil

---

org.eclipse.pde.doc.user/forceQualifierUpdate.txt
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/project/IBundleProjectService.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/project/IHostDescription.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/project/IPackageImportDescription.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/project/IRequiredBundleDescription.java

The 'since' value was set wrong in https://github.com/eclipse-pde/eclipse.pde/pull/1340.
Having the earliest removal mentioned in the deprecation notice as SimRel date makes it simpler for consumers to understand when the actual removal will happen (earliest).

Fix @Deprecated tag's 'since' value and add removal date.

---

build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/builder/ModelBuildScriptGenerator.java

ECJ does not support Java versions below 1.8 anymore.
Contributes to fixing
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2197
Reference to https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2551.

[PDE-Build] Use 1.8 as default javac target/source-level in scripts

---

build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/AbstractScriptGenerator.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/BuildTimeSiteContentProvider.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/BuildTimeSiteFactory.java

And don't name variables that denote local files 'urls'.

[PDE-Build] Use File to represent file-system paths instead of String

---

build/org.eclipse.pde.build.tests/src/org/eclipse/pde/build/internal/tests/ScriptGenerationTests.java
build/org.eclipse.pde.build.tests/src/org/eclipse/pde/build/internal/tests/SourceTests.java
build/org.eclipse.pde.build.tests/src/org/eclipse/pde/build/internal/tests/p2/LicenseTests.java
build/org.eclipse.pde.build.tests/src/org/eclipse/pde/build/internal/tests/p2/PublishingTests.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/FetchScriptGenerator.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/IPDEBuildConstants.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/packager/PackageConfigScriptGenerator.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/BuildTimeFeature.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/BuildTimeFeatureFactory.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/BuildTimeFeatureParser.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/BuildTimeSite.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/BuildTimeSiteFactory.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/compatibility/FeatureReference.java
build/org.eclipse.pde.build/src_ant/org/eclipse/pde/internal/build/tasks/BuildManifestTask.java

This avoids unnecessary conversations that also uses deprecated methods like File.toURL()

[PDE-Build] Use Path instead of URL to represent local files

---

ui/org.eclipse.pde.junit.runtime.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.junit.runtime.tests/pom.xml
ui/org.eclipse.pde.junit.runtime.tests/src/org/eclipse/pde/junit/runtime/tests/JUnit5SuiteExecutionTest.java

Fixes https://github.com/eclipse-pde/eclipse.pde/issues/1360

Prevent multiple execution of junit.runtime.tests and always clear workspace

---

apitools/org.eclipse.pde.api.tools.tests/META-INF/MANIFEST.MF
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/tests/util/ProjectUtils.java
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/util/tests/ApiBaselineManagerTests.java
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/util/tests/ProjectCreationTests.java
e4tools/bundles/org.eclipse.e4.tools/src/org/eclipse/e4/internal/tools/wizards/classes/AbstractNewClassWizard.java
org.eclipse.pde.doc.user/forceQualifierUpdate.txt
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/project/IBundleProjectService.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/project/IHostDescription.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/project/IPackageExportDescription.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/project/IPackageImportDescription.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/project/IRequiredBundleDescription.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/project/BundleProjectDescription.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/project/BundleProjectService.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/project/ProjectModifyOperation.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/project/ProjectCreationTests.java

Based on the discussion in https://github.com/eclipse-pde/eclipse.pde/pull/1340, this is a draft to explore a possible modernization of the pde.project description API interfaces. The main changes are:
1. Rename getters starting with `getX()` by record-component style methods just naming what is returned (i.e. `X()`)
2. Use Lists instead of Arrays
This allows to simplify the implementations of these interfaces to be simple records where the required methods are implemented implicitly, which is also used in this PR.
Because point one does not have a great benefit for consumers, the existing methods are kept as deprecated (but not for removal) so consumers are not forced to update.
While the new methods are in a nice and modern style, I'm not sure if the change is worth the effort for …

Modernize pde.project description interfaces

---

ui/org.eclipse.pde.bnd.ui/src/org/eclipse/pde/bnd/ui/views/repository/AdvancedSearchDialog.java

When opening this dialog, the tab items are decorated with images created by the individual search panels. When the dialog is closed, those images are disposed again.
Problem arises because the search panels don't create new images, but instead use shared images. Meaning when the dialog is opened a second time, those images have already been disposed, preventing the dialog from showing up.
Reason for this regression is the switch from the Icons class of the bndtools project to the PDE Resources class. Former has an explicit "isDisposed()" check, which would've created a new image on-the-fly, while latter doesn't. Given that the images are not owned by this dialog, the solution to this problem is to simply not have them be disposed by the dialog.
See …

Fix: Unable to open Advanced Search Dialog more than once

---

build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/builder/ModelBuildScriptGenerator.java

Generalization of https://github.com/eclipse-pde/eclipse.pde/pull/1351
With https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2770 we could just use `JavaCore.getAllJavaSourceVersionsSupportedByCompiler().first()`

[PDE-Build] Use first supported version as default javac target/source

---

build/org.eclipse.pde.build/META-INF/MANIFEST.MF

The PDEState class is using JavaRuntime.getProvidedVMPackages(...), which has only been added with version 3.22. But the Manifest still only requires 3.21. This causes issues when installing the latest PDE in the Eclipse 4.31, as the JDT bundles are not updated, which therefore leads to a NoSuchMethodError.
See https://github.com/eclipse-windowbuilder/windowbuilder/issues/865 for a real-life example of this problem.
Amends 00c9caf09d4a5f5be92cbb3e628ef64fa73440f6

Adjust lower bound for dependency to JDT Launching in PDE Build

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/iproduct/ILauncherInfo.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/iproduct/IMacBundleUrlType.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/iproduct/IProductModelFactory.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/product/LauncherInfo.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/product/MacBundleUrlType.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/product/ProductModelFactory.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/LauncherSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties

Support editing of <launcher><macosx><bundleUrlTypes> entries in the product editor.
These are translated to CFBundleURLTypes entries in the Info.plist dictionary of the macOS app bundle.
Contributes to
https://github.com/eclipse-platform/eclipse.platform.ui/issues/1901.

Product file editor: Support for <bundleUrlTypes> on macOS

---

org.eclipse.pde.doc.user/forceQualifierUpdate.txt
ui/org.eclipse.pde.core/.settings/.api_filters
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/plugin/IMatchRules.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/plugin/PluginRegistry.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/plugin/VersionMatchRule.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/feature/FeatureImport.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/plugin/ImportObject.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/search/PluginJavaSearchUtil.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/VersionUtil.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/project/PluginRegistryTests.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDELabelProvider.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/category/CategoryLabelProvider.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/DependencyAnalysisSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/PluginSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/LaunchAction.java

Modernize the PluginRegistry API that contains the antiquated `org.eclipse.osgi.service.resolver.VersionRange` by providing alternatives using the `org.osgi.framework.VersionRange` and deprecating the existing methods for removal.
In conjunction with that also mark `PluginRegistry.PluginFilter` as deprecated for removal since it is effectively a `Predicate<IPluginModelBase>` and just use the latter in the new methods.
This is currently an early draft to discuss the overall direction. Since the intention is to focus on the API callers of the now deprecated methods are not replaced in this PR. I'll do that in a follow-up.
About the API I'm also contemplating to further modernize the methods in `PluginRegistry` that now return a List to return a Stream instead. Then we could also save the …

Rework PluginRegistry API and introduce VersionMatchRule enum

---

apitools/org.eclipse.pde.api.tools/META-INF/MANIFEST.MF
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiAnnotations.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/CompositeApiDescription.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/TypeAnnotations.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/provisional/IApiAnnotations.java

- CompositeApiDescription.resolveAnnotations should be able to properly find the best match annotation using IApiAnnotations.isExact which is now also implemented by TypeAnnotations.isExact.
https://github.com/eclipse-pde/eclipse.pde/issues/1386

IApiAnnotations.isExact for CompositeApiDescription.resolveAnnotations

---

ds/org.eclipse.pde.ds.ui/META-INF/MANIFEST.MF
ds/org.eclipse.pde.ds.ui/src/org/eclipse/pde/internal/ds/ui/editor/contentassist/TypeCompletionProposal.java
ds/org.eclipse.pde.ds.ui/src/org/eclipse/pde/internal/ds/ui/wizards/DSFileWizardPage.java
ui/org.eclipse.pde.ui/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/build/BaseBuildAction.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ExtensionsSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/targetdefinition/TargetEditor.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/StyledBundleLabelProvider.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/BundleProjectConfigurator.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/ui/launcher/JUnitTabGroup.java
ui/org.eclipse.pde.ui/src_samples/org/eclipse/pde/internal/ui/samples/ShowSampleAction.java

And apply minor clean-ups in ExtensionsSection.
The branch in `DSFileWizardPage.getProject(Object)` that checks if the passed object is a `ClassPathContainer` seems to be possible anymore.
In general creating OSGI Service Components through the UI is a quite uncommon nowdays since one can simply use the Decalarative service component annotations.

Fix more warnings in pde.ui and pde.ds.ui

---

org.eclipse.pde.doc.user/forceQualifierUpdate.txt
org.eclipse.pde.doc.user/pom.xml

Probably as part of https://github.com/apache/maven-javadoc-plugin/pull/204, the default output directory of the `maven-javadoc-plugin` changed when updating the `maven-javadoc-plugin` from `3.8.0` to `3.10.0`. This adapts the doc-bundle build accordingly.
In a local test the missing `reference/api` folder was generated in the project as expected, but the built jar still didn't contain it. So maybe more adaption is necessary.
Hopefully fixes https://github.com/eclipse-pde/eclipse.pde/issues/1392

Adapt to changed output directory in maven-javadoc-plugin 3.10.0

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/TargetPlatformHelper.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/IUBundleContainer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/IULocationFactory.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/InstallableUnitGenerator.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/Messages.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/Messages.properties
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetMetadataCollector.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/EditIUContainerPage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/IUContentProvider.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/IUFactory.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/StyledBundleLabelProvider.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/TargetLocationContentProvider.java

This is extracted from https://github.com/eclipse-pde/eclipse.pde/pull/1245 (currently its first commit).

Clean-up and modernize target-platform loading classes

---

org.eclipse.pde.doc.user/forceQualifierUpdate.txt

Something changed the result of the javadoc generation again and therefore the last master branch build failed due to comparator errors.

Enforce qualifier-update of o.e.pde.doc.user to pick up javadoch changes

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/IUBundleContainer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetPlatformService.java

This is extracted from https://github.com/eclipse-pde/eclipse.pde/pull/1245 (currently its second commit).

Simplify Installable-Unit handling in IUBundleContainer

---

Jenkinsfile
org.eclipse.pde.doc.user/forceQualifierUpdate.txt

centos-latest is deprecated as per:
https://github.com/eclipse-cbi/jiro-agents/blob/master/README.md

Build on ubuntu-latest

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/VersionUtil.java

Take same strategy as for a version string: Don't report an error for null values, assuming this just means absence of a version range.
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
at java.base/java.util.StringTokenizer.<init>(StringTokenizer.java:199)
at org.osgi.framework.VersionRange.<init>(VersionRange.java:137)
at org.eclipse.pde.internal.core.util.VersionUtil.validateVersionRange(VersionUtil.java:45)
at org.eclipse.pde.internal.core.builders.BundleErrorReporter.validateFragmentHost(BundleErrorReporter.java:480)
at org.eclipse.pde.internal.core.builders.BundleErrorReporter.validate(BundleErrorReporter.java:164)
at org.eclipse.pde.internal.core.builders.ErrorReporter.validateContent(ErrorReporter.java:109)
at …

NPE in VersionUtil

---

ui/org.eclipse.tools.layout.spy/META-INF/MANIFEST.MF
ui/org.eclipse.tools.layout.spy/plugin.xml

core and ui define this org.eclipse.pde.runtime.spy.commands.category category for their command. Copying over the solution for the layout spy.
Fixes #856

Adding a category for the layout spy

---

build/org.eclipse.pde.build/META-INF/MANIFEST.MF
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/BundleHelper.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/Utils.java

https://github.com/eclipse-equinox/p2/pull/550

Fix breakage caused by o.e.p.i.publishing.Utils changes

---

build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/FeatureGenerator.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/ProductGenerator.java

Fixes https://github.com/eclipse-pde/eclipse.pde/issues/1423

MacOS AArch64 launcher is its own fragment now.

---

ui/org.eclipse.pde.genericeditor.extension.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.genericeditor.extension.tests/pom.xml
ui/org.eclipse.pde.genericeditor.extension.tests/src/org/eclipse/pde/genericeditor/extension/tests/AbstractTargetEditorTest.java
ui/org.eclipse.pde.genericeditor.extension.tests/src/org/eclipse/pde/genericeditor/extension/tests/Bug528706CompletionWithMultilineTagsTest.java
ui/org.eclipse.pde.genericeditor.extension.tests/testing-files/target-files/MultilineTagTestCaseTarget.txt

Is probably failing due to the update of the supported architectures list in https://github.com/eclipse-platform/eclipse.platform/pull/1576.
And simplify `AbstractTargetEditorTest`.

Fix failing case in Bug528706CompletionWithMultilineTagsTest

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/product/ArgumentsInfo.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/core/tests/internal/util/PDESchemaHelperTest.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/ArgumentsSection.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/PropertiesSection.java

Silenced in code to allow targeting older versions. Replaced in tests.

Cleanup deprecated Platform.ARCH_X86 usage 

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/preferences/TargetPlatformPreferencePage.java

TargetPlatformPreferencePage: refresh Locations after Reload

---

ui/org.eclipse.pde.ui.templates.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.templates.tests/pom.xml
ui/org.eclipse.pde.ui.templates.tests/src/org/eclipse/pde/ui/templates/tests/TestPDETemplates.java

Use api rather than quering system property java.specification.version.

Simplify TestPDETemplates

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/IUBundleContainer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetDefinition.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/EditIUContainerPage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/IUContentProvider.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/IUFactory.java

This is extracted from https://github.com/eclipse-pde/eclipse.pde/pull/1245 (currently its first commit).

[TP] Remove declarations of Exception that are never thrown and clean-up

---

ui/org.eclipse.pde.ui.templates.tests/src/org/eclipse/pde/ui/templates/tests/TestPDETemplates.java

ECJ has been enhanced to warn about unused lambda parameters (https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3053 ) but templates are done for lowest Java version supported without an easy way to generate per JVM versioned code thus there is no easy way to change them.
Filter these warnings until Java 22 is the min required version for templates.
Fixes I-build tests
https://download.eclipse.org/eclipse/downloads/drops4/I20241015-1820/testresults/html/org.eclipse.pde.ui.templates.tests_ep434I-unit-cen64-gtk3-java23_linux.gtk.x86_64_23.html

Fix pde.ui.templates.tests failures on Java 23

---

ui/org.eclipse.pde.genericeditor.extension/META-INF/MANIFEST.MF
ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/autocomplete/TagCompletionProposal.java
ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/command/UpdateUnitVersions.java

- Remove 'version' attribute from 'unit' proposal
Now that PDE supports no versions in unit declarations it does not have to be proposed for all cases.
- Skip units with version-range in the 'UpdateUnitVersions' action from the context menu in the Source tab.
Follow-up on https://github.com/eclipse-pde/eclipse.pde/pull/1245.

[TP-Editor] Adapt content-assist to support of version-ranges/no-version

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/LauncherSection.java

Corner case (no <launcher> element present, yet) was missed in #1326.
Fixes #1443.

Product Editor: Fix NPE in launcher section / macOS bundle url types

---

ui/org.eclipse.pde.ui.tests/src/org/eclipse/ui/tests/smartimport/ProjectSmartImportTest.java

Have the actual file content in the failure message to analyze failures in I-build only like
https://download.eclipse.org/eclipse/downloads/drops4/I20241019-1800/testresults/html/org.eclipse.pde.ui.tests_ep434I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

Enhance ProjectSmartImportTest assertion

---

build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java

Hashtable does not store null values , so if systempackage comes as null it will throw null pointer exception
Fixes :- [#1453](https://github.com/eclipse-pde/eclipse.pde/issues/1453)

Null pointer check added for system package

---

apitools/org.eclipse.pde.api.tools/forceQualifierUpdate.txt

These are expected changes due to the compiler changes via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3254

Comparator errors in I20241106-1800

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetPlatformService.java

Instead of implementing an asynchronous event dispatching mechanism in TargetPlatformService, simply use IEventBroker.post().

Simplify event publication in TargetPlatformService

---

org.eclipse.pde.doc.user/forceQualifierUpdate.txt
ui/org.eclipse.pde.core/.settings/.api_filters
ui/org.eclipse.pde.core/META-INF/MANIFEST.MF
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/target/TargetEvents.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/AbstractTargetHandle.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/ExternalFileTargetHandle.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/LocalTargetHandle.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetPlatformService.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/WorkspaceFileTargetHandle.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/targetdefinition/TargetEditor.java

When building tools on top of PDE's target platform framework it's often necessary to be informed about state changes in targets. PDE already uses an IEventBroker to send "workspaceTargetChanged" events. This change is about sending two new events:
TARGET_SAVED and TARGET_DELETED
Please note that I also added the method TargetEditor.getAdapter(), which provides callers with the ITargetHandle of the editor.

Provide TARGET_SAVED and TARGET_DELETED events

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/build/BuildClasspathSection.java

Rewrote the initialize() function in BuildClasspathSection.java to make the 'Extra Classpath Entries' expanded by default
Before:
After:

Updated BuildClasspathSection.java

---

ui/org.eclipse.pde.genericeditor.extension.tests/src/org/eclipse/pde/genericeditor/extension/tests/UpdateUnitVersionsCommandTests.java

Test randomly fails, but it is unclear why. Hopefully the additional text will help to understand the reason.
https://github.com/eclipse-pde/eclipse.pde/issues/666

UpdateUnitVersionsCommandTests add information on fail

---

apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/tests/AbstractApiTest.java

Failing tests on windows. Since JDK sometimes keeps handles open until GC it is worth a retry.
https://github.com/eclipse-pde/eclipse.pde/issues/1483

AbstractApiTest: retry delete resource after GC #1483

---

e4tools/.gitignore

Because in PDE we have packages that contain an element named 'target' we cannot generally ignore 'target'-folders and the patterns have to be more specific than usual.

Ignore 'target' folders in e4tools

---

ui/org.eclipse.pde.ui.templates/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.templates/templates_3.5/E4View/java/parts/$className$.java

This change fixes a typo in the plugin-in template "View contribution using 4.x API".

Fix Typo in Plugin-in Template

---

ui/org.eclipse.pde.core/forceQualifierUpdate.txt

Changes to ecj are for handling of switch on String.
See: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2595

Updated bundles with comparator errors

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetDefinition.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/targetdefinition/ImplicitDependenciesSection.java

Currently editing the Implicit Plugin-Dpendencies only seem to work randomly (e.g. if one change some other property along with the change).
This now do not refresh the full target (what seem to reset the underlying model and remove the dirty flag before changes are applied) but only updates the UI so finally these thing appear in the target file.
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/451

Fix editing of Implicit Plugin-Dpendencies

---

build/org.eclipse.pde.build/META-INF/MANIFEST.MF
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java
features/org.eclipse.e4.tools.persistence.feature/feature.xml
features/org.eclipse.pde-feature/feature.xml
org.eclipse.pde.doc.user/META-INF/MANIFEST.MF
org.eclipse.pde.doc.user/pom.xml

Null pointer check added for system package
Hashtable does not store null values , so if systempackage comes as null it will throw null pointer exception
/cc @MohananRahul

back-port: Null pointer check added for system package (#1455)

---

features/org.eclipse.pde.unittest.junit-feature/feature.xml
ui/org.eclipse.pde.launching/META-INF/MANIFEST.MF
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/VMHelper.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/AbstractPDELaunchConfiguration.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/JUnitLaunchConfigurationDelegate.java
ui/org.eclipse.pde.unittest.junit/META-INF/MANIFEST.MF
ui/org.eclipse.pde.unittest.junit/src/org/eclipse/pde/unittest/junit/launcher/JUnitPluginLaunchConfigurationDelegate.java

Since Java-24 the security-manager cannot be used anymore and launching a Java-24 VM fails to launch if the VM-argument
`-Djava.security.manager=allow` is specified.
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2623
CC @merks
Depends on https://github.com/eclipse-pde/eclipse.pde/pull/1515.

[Launching] Don't add -Djava.security.manager=allow for Java-24 or later

---

build/org.eclipse.pde.build/META-INF/MANIFEST.MF
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/BuildScriptGenerator.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/builder/AbstractBuildScriptGenerator.java
build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/builder/DevClassPathHelper.java
build/org.eclipse.pde.build/src_ant/org/eclipse/pde/internal/build/tasks/BuildScriptGeneratorTask.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/ClasspathHelper.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/exports/FeatureExportOperation.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/EclipseApplicationLaunchConfiguration.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/EquinoxLaunchConfiguration.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/JUnitLaunchConfigurationDelegate.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/classpathresolver/ClasspathResolverTest.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/build/GenerateFeatureBuildFileAction.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/build/GeneratePluginBuildFileAction.java
ui/org.eclipse.pde.unittest.junit/src/org/eclipse/pde/unittest/junit/launcher/JUnitPluginLaunchConfigurationDelegate.java

Instead returning a file-URL in it's string representation better use the actual type of value, i.e. a Path.

Return Path instead of URL-String in ClasspathHelper.writeDevEntries()

---

ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/model/Node.java

The org.eclipse.pde.internal.genericeditor.target.extension.model.Node is accessed in a concurrent way but its internal implementation uses unsynchronized mutator methods.
This add synchronized to all methods and copy internal datastructures to make the class at least concurrent-safe and prevent unsyncronized data structures to escape the scope of a node.

Synchronize Target Node

---

org.eclipse.pde.doc.user/forceQualifierUpdate.txt

To fix comparator errors https://download.eclipse.org/eclipse/downloads/drops4/I20241229-0520/

Touch for javadoc switch to java 21

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/util/PDEModelUtility.java

**Summary Of Change**
Added a null guard to editor.getContextManager() to prevent NullPointerException (NPE).
**Why this Change is Needed**
An NPE occurs when too many processes are running and the user uses the context menu to close all tabs. This is caused by a race condition where dispose() is called while modifyEditorModel() is still running, resulting in getContextManager() returning null.
**Related Issue**
Fix #1404 
**Testing**
Testing is in progress. We are working on a test where dispose() is called followed by modifyEditorModel() to verify that the null guard resolves the issue.

WIP: Fix NPE in PDEModelUtility.java (line 415) by adding null check (Fix #1404)

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java

Currently it is assumed that a profile is up-to-date if the sequence number does not change, but this has some risk to produce strange errors if for some reason there is no number or it is not changed. And even if the number changed, we still perform a check for actual changes.
Because of the constant problems in inconsistent behavior this now completely removes the check for the sequence number from the profile.

Remove the check for sequence number from P2TargetUtils.checkProfile

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PDECoreMessages.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/BundleErrorReporter.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/pderesources.properties

OSGi recently has added support for a 'deprecated' directive that can be used by tools to inform users that the bundle supplier in one way or another has deprecated a capability and it will likely removed in the future.
This now adds support to PDE to show a deprecation warning if such a bundle is used in require bundles.

Add support for the 'deprecated' directive on required bundles

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/text/ColorManager.java

This change adjusts the check added for Eclipze bugzilla 546205 ticket. The check for running workbench is now done at the start of ColorManager.initializeDefaults(), to prevent the creation of an SWT Display object when in headless mode.
See: https://bugs.eclipse.org/bugs//show_bug.cgi?id=546205
Fixes: #1486

Move workbench running check in ColorManager to prevent SWT errors when headless

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetDefinition.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetDefinitionPersistenceHelper.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetPersistence36Helper.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetPersistence38Helper.java

As the sequence number is not persisted into a target file by the target editor, there is actually no point in loading it as it only can lead to inconsistent state.

Do not load sequence number from target files anymore

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PluginModelManager.java

In some cases it is good to wait for a certain type of jobs to complete, this now adds a family to UpdateClasspathsJob so it can be used to wait for such kind of jobs to complete (e.g. used in Tycho api-analysis-mojo).

Add a family to UpdateClasspathsJob

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetDefinition.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetPersistence36Helper.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetPersistence38Helper.java
ui/org.eclipse.pde.genericeditor.extension.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.genericeditor.extension.tests/pom.xml
ui/org.eclipse.pde.genericeditor.extension.tests/src/org/eclipse/pde/genericeditor/extension/tests/AttributeNameCompletionTests.java
ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/autocomplete/TagCompletionProposal.java
ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/autocomplete/processors/AttributeNameCompletionProcessor.java
ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/model/ITargetConstants.java
ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/reconciler/presentation/TargetPlatformAttributeRule.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/target/TargetDefinitionPersistenceTests.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/ToggleIncludeHandler.java

Currently there is an attribute `sequenceNumber` that should change 
> whenever something in the target that affects the set of features and bundles that would be resolved
but effectively this never worked very well and is nowhere used in such a way:
- A sequence number is not mandatory
- Target files are often edited by humans and it is easy to forget to increment those
- Updating it was never public API so only with some operations it was possible to implicitly change that
- it is only used to check if a P2 profile is up-to-date where the sequence number is a very bad indication as actually even things outside the target can influence it
- even if the sequence number does not matches, P2TargetUtils performed some other checks if maybe the profile has not changed, so P2TargetUtils is …

Remove usage of the sequence number from target files

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/plugin/TemplateListSelectionPage.java

This commit fixes the inconsistent graying out of template description for plug-in and rcp project.
Also to hide the checkbox for 'Create a plug-in using a template' when while creating a plug-in project with Rich client application as YES
Fixes: #1547

template description grayed out fix for plugin and rcp project

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetDefinition.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/TargetDefinitionDocumentTools.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/target/IUBundleContainerTests.java

Fixes https://github.com/eclipse-pde/eclipse.pde/issues/1255
@tivervac I tried to cherry pick your testcase from your PR here:
- https://github.com/eclipse-pde/eclipse.pde/pull/1256

Location attributes are not correctly updated

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/plugin/TemplateListSelectionPage.java

This commit fixes the bnd in templates while switching the plugin project type from bnd(with checked 'Generate OSGi metadata automatically' ) to standard equinox 
Fixes: https://github.com/eclipse-pde/eclipse.pde/issues/1500

Updated selection when switched from bnd to standard equinox

---

ds/org.eclipse.pde.ds.annotations/META-INF/MANIFEST.MF
ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/DSAnnotationCompilationParticipant.java

+ Use getJLSLatest instead of deprecated JLS4 constant to use latest AST Parser

DS processing crashes when Pattern matching is used in a switch statement

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/ApiBaselineManager.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/ApiAnalysisBuilder.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/IncrementalApiBuilder.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ApiBaseline.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/provisional/model/IApiBaseline.java

`ApiBaseline.getPrerequisiteComponents()` didn't consider multiple versions of a component.
Besides fixing that, this also unifies and simplifies the handling of multiple versions.
I noticed that while working on https://github.com/eclipse-pde/eclipse.pde/pull/1336.

[APITools] Handle multiple version correct when obtaining prerequisites

---

ui/org.eclipse.pde.ui/plugin.properties

Repository can mean p2 or source, let's disambiguate it. Also drop the "plug-in" part of importFromRepository labels as this action only shows up in the context of a plugin already.

Disambiguate "repository" in importFromRepository

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/BaseApiAnalyzer.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/RequiredPackageVersionChange.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/problems/ApiProblemFactory.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/problems/problemmessages.properties
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/provisional/problems/IApiProblem.java

Currently API tools only check for API changes on the bundle level, but even more important are checks on the exported packages. If the package version is not properly incremented this can lead to method not found or similar errors, also consumers of the package can not depend on the package version reliable to get new API.
This now adds some basic checks to check for API changes on the package level, compare it with the baseline and suggest a new version based on the resulting delta being a breaking or non breaking change.
This is a very basic first step. We need (see TODOs) and likely want to further improve this when we use it, for example currently all deltas are assumed to be important, we might discover places where it is actually not required to make a minor change but only a micro …

Add support for checking package exports for changed API

---

Jenkinsfile

That should prevent the need to manually reset the baseline when new warning is introduced by previous PR or even due to change outside of the project.

Make Jenkins complain on new warnings from the current PR

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/BaseApiAnalyzer.java

In some rare cases it can happen that duplicate exports are present (seen in org.eclipse.osgi with java.io package resolved from jre), in this case API tools fails with an error.
THis now simply always ever use the first declared package for analysis.

If there are duplicate packages use the first declaration

---

ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/EclipseApplicationLaunchConfiguration.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/EquinoxLaunchConfiguration.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/JUnitLaunchConfigurationDelegate.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/launcher/PluginBasedLaunchTest.java

Ensures that the parameter can always we be converted back to URI.
It's been already done for -dev param value.
Fixed PluginBasedLaunchTest to no longer try to "workaround"
-configuration values that can't be converted to URI.

Fix launch -configuration param to always be proper URI 

---

apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/preferences/ApiErrorsWarningsConfigurationBlock.java

Wiki is read only with multiple warnings being what one sees before figuring the redirects.

Fix link to current "Evolving Java-based APIs"

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/DependencyPropertiesDialog.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/parts/PluginVersionPart.java

The commit fixes Properties dialog of Imported packages showing version of matching packages. Implemented similar to required plugin properties section
Fixes #1501
@laeubi 
One questions here:-
1. Under what condition can the list contains plug-in or packages with same name and multiple version in respective Required Plug-ins and Imported Packages section?

Imported packages showing version of matching packages

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ApiBaseline.java

- Guard against fAllComponentsById.get(id) yielding null.
https://github.com/eclipse-pde/eclipse.pde/issues/1569

Prevent NPE in ApiBaseline.getApiComponent(String, Version)

---

apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/markers/FilterProblemResolution.java
apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/markers/FilterProblemWithCommentResolution.java
apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/markers/IApiToolProposalRelevance.java
apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/markers/RemoveFilterProblemResolution.java

Currently the suggestions are not always totally ordered (e.g. there are some with default of 0), even though Eclipse then fall back to comparing strings, it would be much better to have an explicit ordering.
This now:
- make creating a commented compatibility filter "more recommended"
- make removing an unused filter "more recommended"
- make configure the problem category "less recommended"

Making ordering of relevances more explicit

---

apitools/org.eclipse.pde.api.tools/META-INF/MANIFEST.MF
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/search/HTMLConvertor.java

The only reason for icu4j currently is to determine if a RTL language is used as the default locale on html exports.
This replaces the fat (12MB!) dependency by a simpler variant that seems suitable for the sake of generating html reports.
The list of codes is taken from https://raw.githubusercontent.com/shadiabuhilal/rtl-detect/2eed8a33276461a24e7033d1d3a115ee64aee3f5/lib/rtl-detect.js and adapted to java.

Remove dependency to icu4j for html exports

---

apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/tags/InvalidRecordTagTests.java
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/tags/TagTest.java
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/tags/ValidRecordTagTests.java
apitools/org.eclipse.pde.api.tools.tests/test-builder/tagprojects/java17tags/.classpath
apitools/org.eclipse.pde.api.tools.tests/test-builder/tagprojects/java17tags/.project
apitools/org.eclipse.pde.api.tools.tests/test-builder/tagprojects/java17tags/.settings/org.eclipse.jdt.core.prefs
apitools/org.eclipse.pde.api.tools.tests/test-builder/tagprojects/java17tags/META-INF/MANIFEST.MF
apitools/org.eclipse.pde.api.tools.tests/test-builder/tagprojects/java17tags/build.properties
apitools/org.eclipse.pde.api.tools.tests/test-builder/tags/record/test1.java
apitools/org.eclipse.pde.api.tools.tests/test-builder/tags/record/test10.java
apitools/org.eclipse.pde.api.tools.tests/test-builder/tags/record/test11.java
apitools/org.eclipse.pde.api.tools.tests/test-builder/tags/record/test3.java
apitools/org.eclipse.pde.api.tools.tests/test-builder/tags/record/test4.java
apitools/org.eclipse.pde.api.tools.tests/test-builder/tags/record/test5.java
apitools/org.eclipse.pde.api.tools.tests/test-builder/tags/record/test6.java
apitools/org.eclipse.pde.api.tools.tests/test-builder/tags/record/test7.java
apitools/org.eclipse.pde.api.tools.tests/test-builder/tags/record/test8.java
apitools/org.eclipse.pde.api.tools.tests/test-builder/tags/record/test9.java
apitools/org.eclipse.pde.api.tools.tests/test-builder/tags/record/valid/test1.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/CoreMessages.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/JavadocTagManager.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/BuilderMessages.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/TagValidator.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/Validator.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/builder/buildermessages.properties
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/coremessages.properties
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/provisional/IApiJavadocTag.java

* support `record` types
Fixes #1575

[#1575] EmptyStackException with javadoc on record method

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/ClasspathComputer.java

fixes random failing ClasspathUpdaterTest
When IJavaProject.setRawClasspath() is explicitly called with ClasspathEntries distinct from PDE (like in the Test), and then later PDEs UpdateClasspathJob is executed it can't compute the "oldEntry" and fails with "... is not on its projects build path". The Message is correct - it was manually removed from the projects build path. That state should just be ignored so that PDE continues to set the IClasspathEntries computed by PDE.
https://github.com/eclipse-pde/eclipse.pde/issues/820

fix ClasspathComputer: ignore if oldEntry not found  #820

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsClasspathContainer.java

Currently one can only reference an inner jar with extra-classpath but not the bundle itself.
As this is actually something useful and this is even used in platform builds (even though it seem not effective due to this bug), PDE should support it as well.

Support extra classpath with no inner jar specification

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsClasspathContainer.java

Fix https://github.com/eclipse-pde/eclipse.pde/issues/1605

If the target of the extra classpath is a project add CPE_PROJECT entry

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/rows/IdAttributeRow.java

This fixes a regression introduced in 34b8e38ef25242a4992f61c8676569a8dcffc7f7 When that commit was done some instanceof checks were removed. The result of removing the instanceof checks had the side effect of removing the implicit null check that instanceof essentially does.
This change restores the null check for when IConfigurationElement is null.
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/1608

Resolve NPE when Ids don't have associated configuration elements

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/util/Signatures.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java

This fixes a potential regression introduced in
34b8e38ef25242a4992f61c8676569a8dcffc7f7 When that commit was done some instanceof checks were removed.
The result of removing the instanceof checks had the side effect of removing the implicit null check that instanceof essentially does.
I reviewed all the removed instanceof checks in 34b8e38ef25242a4992f61c8676569a8dcffc7f7 and this PR, along with https://github.com/eclipse-pde/eclipse.pde/pull/1609 restores the null check.
I don't know how to trigger these potential NPEs.

Add potentially missing null checks

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/TracingBlock.java

Fixes https://github.com/eclipse-pde/eclipse.pde/issues/1621

Don't apply empty settings from not initialized TracingBlock

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/DependencyPropertiesDialog.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties

This changes the name of the OK button to "Close", to avoid any confusion with the similarly named "Cancel" button.
Closes https://github.com/eclipse-pde/eclipse.pde/issues/1632

Rename "Close" to "Apply" in DependencyPropertiesDialog

---

apitools/org.eclipse.pde.api.tools/META-INF/MANIFEST.MF
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ApiModelFactory.java
apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/model/ProjectComponent.java

Use the existing IProject, do not (incorrectly) derive it from the directory name.
Fixes #1687.

[API-Tools] Do not assume a project is named like its directory

---

Jenkinsfile

Also make sure the issues are published even in case of a failed build, as otherwise they are not visualized.

Jenkinsfile: Use Tycho 4.0.13 way to display api tools warnings

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/WorkspaceModelManager.java

The PreferenceChangeListener that is added when a project is created/opened or when the plugin is started needs to be removed when the project is deleted, in order to make it eligible for garbage collection.

Remove preference listener if manager is shut down or project is deleted

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsInitializer.java

- Collect deferred projects to be processed by a single job.
https://github.com/eclipse-pde/eclipse.pde/issues/1667

Improve RequiredPluginsInitializer.initialize

---

apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/util/TarFile.java

Currently we add a long to an int this can result in information loss and numeric errors such as overflows.
As we only skip an integer amount of bytes the result can also only be an int of bytes skipped, adding an explicit cast makes the security scanner happy here.

Fix Implicit narrowing conversion in compound assignment

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/parts/PluginVersionPart.java

Closes https://github.com/eclipse-pde/eclipse.pde/issues/1736

Add plugin/package distinction to double-click listener

---

docs/.project
docs/.settings/org.eclipse.core.resources.prefs
docs/API_Tools.md
docs/Execution_Environments.md
docs/FAQ.md
docs/Target_Definitions.md
docs/User_Guide.md

- Add a .project file to `docs` folder  for a project named `org.eclipse.pde.docs`
- Remove internal table of content entries.
- Fix broken links and avoid absolute raw links.

Improve and fix the markdown documentation

---

ui/org.eclipse.pde.unittest.junit/META-INF/MANIFEST.MF
ui/org.eclipse.pde.unittest.junit/icons/full/obj16/julaunchpgn.svg
ui/org.eclipse.pde.unittest.junit/icons/full/obj16/test.svg
ui/org.eclipse.pde.unittest.junit/plugin.xml
ui/org.eclipse.tools.layout.spy/META-INF/MANIFEST.MF
ui/org.eclipse.tools.layout.spy/icons/obj16/layoutspy_obj.svg
ui/org.eclipse.tools.layout.spy/icons/up_nav.svg
ui/org.eclipse.tools.layout.spy/plugin.xml
ui/org.eclipse.tools.layout.spy/src/org/eclipse/tools/layout/spy/internal/dialogs/LayoutSpyDialog.java

This commit adds SVGs for all icons in the bundle `org.eclipse.pde.unittest.junit` and `org.eclipse.tools.layout.spy`.
See also this [PR](https://github.com/eclipse-platform/eclipse.platform/pull/1797) for more information.

Add SVGs to org.eclipse.pde.unittest.junit and org.eclipse.tools.layout.spy

---

apitools/org.eclipse.pde.api.tools.ui/META-INF/MANIFEST.MF
apitools/org.eclipse.pde.api.tools.ui/icons/full/elcl16/compare_apis.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/elcl16/configure_problem_severity.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/elcl16/expandall.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/elcl16/export.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/elcl16/filter_ps.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/elcl16/help.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/elcl16/next_nav.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/elcl16/open_page.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/elcl16/prev_nav.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/elcl16/remove_exc.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/elcl16/text_edit.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/obj16/annotation_obj.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/obj16/api_tools.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/obj16/bundleversion.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/obj16/category_menu.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/obj16/correction_change.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/obj16/eclipse16.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/obj16/frgmt_obj.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/obj16/library_obj.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/obj16/plugin_obj.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/ovr16/error_ovr.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/ovr16/success_ovr.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/ovr16/warning_ovr.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/wizban/compare_wiz.svg
apitools/org.eclipse.pde.api.tools.ui/icons/full/wizban/profile_wiz.svg
apitools/org.eclipse.pde.api.tools.ui/plugin.xml
apitools/org.eclipse.pde.api.tools.ui/src/org/eclipse/pde/api/tools/ui/internal/ApiUIPlugin.java

This PR adds SVGs for all icons in the bundle `org.eclipse.pde.api.tools.ui` except for the following as it does not exist as SVG yet:
~~obj16/eclipse16.svg~~
See also this [PR](https://github.com/eclipse-platform/eclipse.platform/pull/1797) for more information.

Add SVGs to org.eclipse.pde.api.tools.ui

---

org.eclipse.pde.doc.user/forceQualifierUpdate.txt
ui/org.eclipse.pde.launching/.settings/.api_filters
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/LaunchArgumentsHelper.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/LaunchValidationOperation.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/VMHelper.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/AbstractPDELaunchConfiguration.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/EclipseApplicationLaunchConfiguration.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/EquinoxLaunchConfiguration.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/JUnitLaunchConfigurationDelegate.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/JREBlock.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/LaunchAction.java
ui/org.eclipse.pde.unittest.junit/src/org/eclipse/pde/unittest/junit/launcher/JUnitPluginLaunchConfigurationDelegate.java

This ensures consistency and reduces calls of `DependencyManager.findRequirementsClosure()`.

Reduce re-computation of plugins included in Eclipse/OSGi launches

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/DependencyManager.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/core/tests/internal/DependencyManagerTest.java

Fixes https://github.com/eclipse-pde/eclipse.pde/issues/1727

Consider dependencies of transitively included fragments

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/PDETextHelper.java

Some regular expressions take a long time to match certain input strings to the point where the time it takes to match a string of length n is proportional to nk or even 2n. Such regular expressions can negatively affect performance, or even allow a malicious user to perform a Denial of Service ("DoS") attack by crafting an expensive input string for the regular expression to match.
This replaces the problematic regular expression by a little parser that checks for the same results as the regular expression.

Fix Inefficient regular expression

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/DependencyManager.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/BundleLauncherHelper.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/classpathresolver/ClasspathResolverTest.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/launcher/FeatureBasedLaunchTest.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/launcher/LaunchConfigurationMigrationTest.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/launcher/PluginBasedLaunchTest.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/util/ProjectUtils.java

When launching an application create a new Equinox resolver state, where explicitly included plugins/bundles are preferred and compute the requirements closure from that state. This avoids adding other providers of a capability if another provider is already (explicitly) included in a launch, just because the former is wired to the requirement in the target-platform state. Potentially this also makes the set of launched plugins more compact.
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/1604
Alternative approach to https://github.com/eclipse-pde/eclipse.pde/pull/1618.
Requires (and currently includes)
- https://github.com/eclipse-pde/eclipse.pde/pull/1724

Prefer explicitly included plugins for Eclipse/OSGi launches

---

ui/org.eclipse.pde.bnd.ui/META-INF/MANIFEST.MF

- to be compatible with bndtools which uses Eclipse 2022-09

OSGI Repositories view: lower required version ranges for bndtools

---

ui/org.eclipse.pde.bnd.ui/src/org/eclipse/pde/bnd/ui/Workspaces.java

WIP
- find correct workspace for cnf
The current change has the following effect:
If you click in a project called "cnf" (which is kind of a marker project name for a bnd workspace) then the correct Bnd Workspace is returned. 
In the RepositoriesView this has the effect that the Bnd Workspace Repository and all other bnd repos are also shown if you click on "cnf" project. 
Before this change clicking on a "cnf" project did not show any of the Bnd Workspace repositories (just the PDE Target Repo).

BndWorkspace improvements

---

ui/org.eclipse.swt.tools.spies/META-INF/MANIFEST.MF
ui/org.eclipse.swt.tools.spies/fragment.e4xmi
ui/org.eclipse.swt.tools.spies/icons/sleak.svg
ui/org.eclipse.swt.tools.spies/icons/spy.svg
ui/org.eclipse.swt.tools.spies/plugin.xml

This adds SVGs for all icons in the bundle `org.eclipse.swt.tools.spies`.
This was originally proposed for SWT before moving the spies to PDE, i.e., it is equivalent to:
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/2094

Add SVGs to org.eclipse.swt.tools.spies

---

ui/org.eclipse.pde.ui/icons/etool16/eclipse.svg

- This was copied here https://github.com/eclipse-pde/eclipse.pde/blob/master/apitools/org.eclipse.pde.api.tools.ui/icons/full/obj16/eclipse16.svg
- The SVG is also missing here https://github.com/eclipse-platform/eclipse.platform.images/tree/master/org.eclipse.images/eclipse-svg/org.eclipse.pde.ui/icons/etool16
https://github.com/eclipse-pde/eclipse.pde/issues/1766

Add missing eclipse.svg

---

ui/org.eclipse.pde.ui/.settings/.api_filters
ui/org.eclipse.pde.ui/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/parts/CheckboxTablePart.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/parts/WizardCheckboxTablePart.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/CachedCheckboxTableViewer.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/FilteredCheckboxTable.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/exports/BaseExportWizardPage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/exports/CrossPlatformExportPage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/imports/PluginImportWizardExpressPage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/templates/TemplateSelectionPage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/tools/UpdateBuildpathWizardPage.java

By using the FilteredTable, we get a quick-filter for all extending parts for free. This includes:
- The Cross-platform page of the "Deployable features" export wizard.
- The Update Java Classpath page of the "Update classpath..." action
- The Selection page of the "Import Plug-ins and Fragments" wizard
- The Update Java Classpath page of the "Plug-in from Existing JAR Archives" wizard.
- The Template Selection page of the "Plug-in Project" page.
Together with the quick-filter comes a caching of the checked table items. Those elements remain checked, even if currently hidden by the filter and will be restored once they become visible again.
Furthermore, the PluginListPage has been adapted to use a CheckboxTablePart rather than a CheckboxTreePart (effectively reverting …

Wrap viewer in CheckboxTablePart within a FilteredTable

---

ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/AnnotationVisitor.java
ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/DSAnnotationVersion.java

Using the JDT clean-up for unnecessary whitespace

Whitespace clean-up in pde ds

---

ui/org.eclipse.pde.bnd.ui/META-INF/MANIFEST.MF
ui/org.eclipse.pde.bnd.ui/build.properties
ui/org.eclipse.pde.bnd.ui/plugin.properties
ui/org.eclipse.pde.bnd.ui/plugin.xml

Closes https://github.com/eclipse-pde/eclipse.pde/issues/1778
@merks @laeubi @HannesWell I kept the "OSGi" category as before, until we reach consensus. [See discussion](https://github.com/eclipse-pde/eclipse.pde/issues/1778#issuecomment-2879193174).

PDE Bnd UI: externalize strings in plugin.xml

---

ds/org.eclipse.pde.ds.annotations/OSGI-INF/l10n/bundle.properties

Adds OSGi and declarative service to the key words for the preference page to make it easier to find this setting.

Adds more keywords to the OSGi declarative service preference page

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/correction/ResolutionGenerator.java

This commit fixes the Quick fix option when 'Configure problem severity' is the only available options for the selected problem in the problems tab.
It in turns greys out the Quick fix option when there is no fix attached to the respective problem. This will into misleads developers into thinking that a quick fix is available for the problem when there is no available fix
Previously, it was showing a pop-up saying 'No quick fixes available.'
Attaching the screenshot of the fix
Fixes: #1614

Updating marker to disable Quick Fix option if 'Configure problem severity' is the only available options

---

ui/org.eclipse.pde.bnd.ui/META-INF/MANIFEST.MF
ui/org.eclipse.pde.bnd.ui/src/org/eclipse/pde/bnd/ui/tasks/ManifestCapReqLoader.java
ui/org.eclipse.pde.bnd.ui/src/org/eclipse/pde/bnd/ui/views/resolution/ResolutionView.java

Currently if one selects a MANIFEST.MF file nothing is shown in the ResolutionView but actually a manifest is what actually is a set of requirements and capabilities in an OSGi framework.
This now adds support for displaying a MANIFEST.MF in the ResolutionView by converting it into a Resource first and the use the existing ResourceCapReqLoader.
FYI @chrisrueger 
See:
- https://github.com/eclipse-pde/eclipse.pde/issues/1818

Support selection of MANIFEST.MF file in the ResolutionView

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/feature/FeatureImport.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/ifeature/IFeatureImport.java
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/BundleLauncherHelper.java

If a feature currently uses a 'filter' on an imported plugin this is not considered by PDE and possibly always included. This then leads to the situation that the product launch validation complains because the filter does not match and when running such a launch OSGi prints an error for this plugin as well.
This now checks if the plugin has a filter defined and only add it if it matches.
Fix https://github.com/eclipse-pde/eclipse.pde/issues/1820

Filter Feature Imports according to their specified filter property

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/search/dependencies/CalculateUsesAction.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/search/dependencies/CalculateUsesOperation.java

Currently the implementation for calculating uses uses a HashSet to collect all used packages. This leads to unstable behavior if the same cleanup is applied multiple times.
This now uses a TreeSet instead to ensure lexicographic order is used.

Ensure consistent order of calculated use-clause

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/search/dependencies/CalculateUsesOperation.java

Currently only private references are ignored, but in OSGi you can not use a package you export (as in this case either the import or the export is discarded via substitution) making package private types also not accessible except for fragments that share the same classloader anyways.
Because of this also package private members has to be ignored when calculating uses.
FYI @tjwatson

Do not consider package private references in calculate uses

---

features/org.eclipse.pde.osgitest.dependencies.feature/.project
features/org.eclipse.pde.osgitest.dependencies.feature/.settings/org.eclipse.core.resources.prefs
features/org.eclipse.pde.osgitest.dependencies.feature/build.properties
features/org.eclipse.pde.osgitest.dependencies.feature/feature.properties
features/org.eclipse.pde.osgitest.dependencies.feature/feature.xml

Currently consuming OSGi test dependencies in PDE is a bit cumbersome, providing a feature for easier consumption would help users to adopt this powerful technology and enables advanced use-cases in PDE.
This is a split-up from
- https://github.com/eclipse-pde/eclipse.pde/pull/1619
and could already be independently be used.

Add OSGi test dependencies feature for target consumption

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsClasspathContainer.java

Currently all entries are given in the insertion order, but for test entries they should come last as they are only accessible in the test code while other entries are accessible by both.
To prevent test entries from overriding regular ones, we sort them to be placed later in the classpath.
See
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/4133

Sort entries by test attribute

---

ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/target/TargetDefinitionResolutionTests.java

Test is supposed to verify that the corresponding source bundles are there and this should be independent of whether it's coming from source feature or not.
Test has been extended to actually check that there are source bundles for every bundle in the feature as it was only checking that there are target bundles for all source bundles but if a source bundle was missing that could have easily be missed.
Side effect assertion about non-source bundle in source feature is being dropped as source features are on their way out.
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/1838 .

Fix TargetDefinitionResolutionTests

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/ExtensionsErrorReporter.java

Support special IDREF validation via ExtensionsErrorReporter.isPresent
- The quicklinks.exsd defines two attributes that are specified as IDREFs to command IDs but they actually permit a command spec and even wildcards.
- This leads to warnings when those aspects are used and those warnings are impossible for the user to fix.
- If we disable the basedOn type for those, the extension attributes no longer support Browse... to find a command, which makes authoring very inconvenient.
- Ideally PDE is made aware of these special attribute so support specialized validation.
In EPP there are a bunch of quicklinks definitions, e.g., 
https://github.com/eclipse-packaging/packages/blob/d0d154a80c075e857dcf531396546686ec844dba/packages/org.eclipse.epp.package.committers/plugin.xml#L390-L439
So we …

Support special IDREF validation via ExtensionsErrorReporter.isPresent

---

README.md

https://www.eclipse.org/pde/ is returning 404 (and has been for a couple months according to the Wayback Machine). 
https://projects.eclipse.org/projects/eclipse.pde looks to be the current homepage for the project, is that correct? If so I'll search for other instances of the old link and update them accordingly.

Remove dead link in README

---

build/org.eclipse.pde.build.tests/src/org/eclipse/pde/build/internal/tests/Utils.java

Follow-up on
- https://github.com/eclipse-pde/eclipse.pde/pull/1841

Search for executable at old locations too in pde.build.tests

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/product/ProductInfoSection.java

Commit 863e7c4943731c776df56c88b75d4963effdd9c6 contained a copy and paste error (using fProductCombo instead of fAppCombo)

Prevent mouse wheel from changing selection application

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/DependencyManager.java

If the host is missing or does not build an NPE occurred (issue #1819)

Add null check when getting fragment host wire provider

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/search/dependencies/CalculateUsesOperation.java

If a method/field is from an interface it is public by default but currently is detected as a (package private) member.
This now check the parent of a member and if it is from an interface assume it as not being bundle private.

Interface methods/fields are not package private

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/search/dependencies/GatherUnusedDependenciesOperation.java

Currently if there are only test folders all dependencies are considered unused. While this is technically correct, the usage of test-fragments often is used to import additional requirements, so it seem more safe to not remove them.

Include Test Source folders when gathering unused dependencies

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/PdeProjectAnalyzer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/PdeTestProjectJar.java

If the only source folder in a project is a test folder it is allowed by JDT to use the standard output location. In such case currently nothing is added to the project jar.
This now checks for this case and also includes compile classfiles from there. It also makes sure that test-only classpath entries are not added if not include test is given.

Handle test projects that are using the default output location

---

ui/org.eclipse.pde.launching/src/org/eclipse/pde/launching/JUnitLaunchConfigurationDelegate.java

Currently with the new feature to only include what is minimally required this can lead to the strange situation that the test fails to startup, if one then adds the org.eclipse.osgi to the bundle list it works without a problem.
This now adds the "org.eclipse.osgi" as a requirement for plugin-test launches as it is mandatory anyways.

Equinox Framework is required for plugin-test launches

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/views/imagebrowser/ImageBrowserView.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/views/imagebrowser/repositories/AbstractRepository.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/views/imagebrowser/repositories/TargetPlatformRepository.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/views/imagebrowser/repositories/WorkspaceRepository.java

This PR enables the display of SVGs in the `ImageBrowser`. 
When both a PNG and an SVG version of an icon are present, only the SVG will be shown.
To allow this behavior a new filter `PNGReplacementFilter` is introduced which decides depending on the icons in the cache (future icons) and existing filters if a PNG should be added or suppressed. If an SVG with the same path exists in the cache and if it passes all active filters the PNG will be discarded.
Using the existing text pattern filter to only view specific icons (e.g. "*.png" for only PNGs) continues to work as expected with this implementation showing only PNGs for all available icons. 
For this change to work a new public method `public getElementsCache()` is added to `AbstractRepository`. This should be no problem as the package …

Add SVG support to ImageBrowser

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/search/dependencies/GatherUnusedDependenciesOperation.java

Currently there is one category of usages that are now no longer detected since we use bndlib to find referenced packages that is if something is only needed at compiletime because the compiler otherwise inline the value.
This now restores the previous java search but only for these packages that are selected to be removed. This is faster as we do not need to query all packages and discovers cases where an import is only needed for a compile time constant.

Add a final check for references of unused packages

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/search/dependencies/GatherUnusedDependenciesOperation.java

Currently the search is performed over the whole project (what might take long depending on project size), but actually we are only interested in any match.
THis now uses a ProgressMonitorWrapper that reports cancellation to the search once we found a first positive hit.

Cancel the search as soon as we have a match

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsInitializer.java

Currently there are some cases where an open JavaEditor is not updated, even though the build of the project is fine with that. Strange enough one can make it "work" by simply make some actions slower(!) e.g. setting breakpoints somewhere in the code that initialize classpath containers. The reason is that if initialize happens "too fast" it leads to missing classpath change notification because it looks like the saved to disk state is up-to-date with the new state and no event happens.
This now set an empty intermediate container state to the JDT model so that any code arising at this point in time will see something has changed (from n > empty), and if then at any later time an update is performed from empty > n.
**Special thanks and kudos** to @merks that debugged the case and lead me …

Update the project with an empty classpath container on initialize

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsInitializer.java

- Add ClasspathContainerInitializer.class to the test for families in belongsTo to allow a client to wait for classpath container initialization without knowing or caring about PDE specifically.

Improve DeferredClasspathContainerInitializerJob.belongsTo

---

ds/org.eclipse.pde.ds.annotations/META-INF/MANIFEST.MF
ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/DSAnnotationPreferenceListener.java
ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/DSLibPluginModelListener.java
ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/ProjectClasspathPreferenceChangeListener.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/ClasspathComputer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PluginModelManager.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsClasspathContainer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndResourceChangeListener.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/osgitest/OSGiTestClasspathContributor.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/core/tests/internal/classpath/ClasspathResolutionTest.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/RequiredPluginsContainerPage.java

Currently there a many slightly different access to the RequiredPluginsClasspathContainer when performing an update for the classpath, this makes it quite hard to control what happens when. Also then different jobs are fired to update the classpath and this also creates a lot of boilerplate code.
This now do the following:
- make RequiredPluginsClasspathContainer package protected to limit its visibility and scope
- let all code use ClasspathComputer for its access and to request an update to the container.

Unify access to RequiredPluginsClasspathContainer and classpath updates

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/SourceLocationManager.java

If the locator is unable to locate some sources due to a classlaoding problem this currently leads to an ugly exception window showing up.
This now adds NoClassDefFoundError to the catch clause to prevent annoy the user in such case.

Catch NoClassDefFoundError while locating sources

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/ClasspathComputer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PDECoreMessages.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsClasspathContainer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/pderesources.properties

Currently some checks are performed outside the update job, for example the model is fetched and the javanature. These values can change between submit the data to the job and it actually pick it up.
This now moves these check into the job itself and uses a concurrent queue to prevent the need for synchronized. Also results are collected inside a Map so if new update request are received in the meanwhile we discard the previous computed values.
Beside that, entries are now eagerly computed as they are required anyways when we set the classpath and we can catch problems that occur here instead of just swallow them.
Also the job now react to cancel request much better than before.

Do checks inside the job and compute the classpath entries

---

apitools/org.eclipse.pde.api.tools.tests/META-INF/MANIFEST.MF
apitools/org.eclipse.pde.api.tools.tests/pom.xml
apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/builder/tests/ApiBuilderTest.java

Currently the assertion only tell that there is a difference and print the problems to the system out. Instead it should better mention all details in the message itself.

Improve assert message in ApiBuilderTest

---

ui/org.eclipse.pde.core/.options
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/ClasspathComputer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PDEClasspathContainer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PDECore.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PluginModelManager.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsClasspathContainer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsInitializer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/PDEClasspathContainerSaveHelper.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/SerializableClasspathContainer.java

Computing the bundle plugin classpath can be an expensive operation for different reasons. In many cases these computation even yields the same results as before especially on workspace restart without target changes.
This now stores the last successful computed state per project and read it back on initialization of the classpath container, scheduling a check for actual changes in the background. Only if this check yields a different result or the update is requested as part of a change to the manifest or target state for example the current values are updated.
This yields faster startup times without the risk of blocking (other than file I/O) until PDE can deliver the classpath to consumers delaying the heavy work to a later time.

Save and restore the current plugin classpath container state from disk

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/tools/UpdateClasspathJob.java

Currently the UpdateBuildPathWizard updates some classpath settings but this does not mean the classpath is recomputed as values are cached.
To makes sure everything is up-to-date the UpdateClasspathJob of the wizard now also request an classpath Update for all processed projects.

Let UpdateBuildpathWizard request ClasspathUpdate

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/ClasspathComputer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsInitializer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/PDEClasspathContainerSaveHelper.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/SerializableClasspathContainer.java

Currently some messages about the state is logged in the initializer and some in the computer, also setting an empty classpath required an own inner class while it is actually equal to an empty state.
This now unifies the logging and handling of classpath containers.

Unify logging and setting the classpath container

---

ui/org.eclipse.pde.core/.options
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/ClasspathComputer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PDECore.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsInitializer.java

Currently PDE uses System.out to print trace messages, that has the problem that id the user has configured a trace file it does not show up there.
This now acquire a DebugTrace instance that can be used and use that in the ClasspathComputer.

Write trace messages to the trace log for ClasspathComputer

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsClasspathContainer.java

Currently Junit bundles and their closure is just returned in a quite random order. This leads to sometimes triggering a rebuild because classpath seems to have changed.
This now sort them by their bundle id to ensure to have always the same order.

Sort JUnit bundles by name to ensure a consistent ordering

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/ClasspathComputer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/ClasspathContainerState.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsClasspathContainer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/PDEClasspathContainerSaveHelper.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/util/SerializableClasspathContainer.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/wizards/RequiredPluginsContainerPage.java

Currently `RequiredPluginsClasspathContainer` itself implements `IClasspathContainer` but we actually only need that instance to compute the entries.
As the `RequiredPluginsClasspathContainer` retains some objects in its instance and to make handling more uniform (e.g. regarding equals and hashcode of container instances) this now removes the actual implementation of the interface and simply wraps the resulting entries in a `SerializableClasspathContainer` that only holds a reference to the entries produced itself.

Do not implement IClasspathContainer

---

ui/org.eclipse.pde.core/.options
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PDECore.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/ManifestConsistencyChecker.java

Currently the ManifestConsistencyChecker prints directly to System.out, not only loosing valuable information like current thread and source this also prevents its messages to be redirected to the trace log if requested.
This now adjust the code to use the DebugTrace instead of System.out.

Let ManifestConsistencyChecker use the DebugTrace instead of System.out

---

org.eclipse.pde.doc.user/forceQualifierUpdate.txt
ui/org.eclipse.pde.core/src/org/eclipse/pde/core/IClasspathContributor2.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsClasspathContainer.java

Currently, it is only possible to add classpath entries at the beginning of the calculation process. However, in order to properly take AccessRule.IgnoreIfBetter into account from all other entries, it is necessary to add entries at the end of the calculation.
This PR introduces a new method that allows classpath contributors to append additional entries at the end of the calculation process, enabling more accurate handling of access rules.

Add getAdditionalEntries to IClasspathContributor

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/search/dependencies/GatherUnusedDependenciesOperation.java

Similar to package-imports we need to search for referenced packages from source-only types in case of require bundle.
This also improves how searching is done in general by only create some objects once and have a more uniform handling through the Requestor class to avoid code duplication.
This should fix some issue we see in Equinox cleanups for example:
- https://github.com/eclipse-equinox/equinox/pull/1096

Search required bundles for references in sources

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/IUBundleContainer.java

Currently if there is one failing bundle the whole container resolution fails and throws an ugly error. In fact there is InvalidTargetBundle for that purpose already and the profile container is even using that.
THis one now constructs a InvalidTargetBundle whenever one bundle fails to be constructed from its file.

Do not let one erroneous bundle fail the whole IU container

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/IUBundleContainer.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/target/P2TargetUtils.java

Currently if there is a bad bundle in the bundle pool it is very hard to get rid of it. Deleting it directly will lead to a file not found exception and the pool is completely broken without deeper knowledge of the user p internal data structures.
This now checks if the bundle is currently loaded from the bundle pool and if it is failing evict it from the pool so it can be downloaded fresh on the next request.

Evict bad bundles from the bundle pool

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/JarManifestErrorReporter.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/PDEMarkerFactory.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/correction/ResolutionGenerator.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/correction/UpdateCorrectHeaderName.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties

This is to provide quick fix for invalid header name in MANIFEST.MF
It will provide fix by removing all the invalid characters (characters other than alpha numeric characters, '-' and '_')
for eg. in the below image, added a space after 'Require-Bundle' header
the added quick fix label is 'Remove invalid characters from header'. Once user clicks on 'Finish', it updates the header
Attaching another example

Quick fix added for invalid characters in MANIFEST header

---

ui/org.eclipse.pde.ui.templates.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.templates.tests/pom.xml
ui/org.eclipse.pde.ui.templates.tests/src/org/eclipse/pde/ui/templates/tests/TestPDETemplates.java

- The tests fail when running on Java 25 because that's not currently a supported execution environment.

TestPDETemplates.createProjectWithTemplate use only supported EE

---

ui/org.eclipse.swt.tools.spies/META-INF/MANIFEST.MF
ui/org.eclipse.swt.tools.spies/src/org/eclipse/swt/internal/tools/views/Sleak.java
ui/org.eclipse.swt.tools.spies/src/org/eclipse/swt/tools/views/SleakView.java

Move Sleak class to o.e.swt.internal.tools.views. It's more correct (or at least less wrong as per
https://github.com/eclipse-platform/eclipse.platform/blob/master/docs/Naming_Conventions.md ).
Removes the nasty problem of split packages signed with different certificates.

Fix split package between swt.spies and swt.tools

---

prepareNextDevCycle.sh

It will be called by the pipeline to prepare a new development cycle and automates the enforced qualifier update and clean-up of the 'forceQualifierUpdate.txt' files of the PDE doc bundle.
This will avoid doing it manually as done for the current cycle in
- https://github.com/eclipse-pde/eclipse.pde/pull/1948#issuecomment-3238182237

[RelEng] Add individual release preparation script for PDE

---

ui/org.eclipse.pde.core/META-INF/MANIFEST.MF
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/ClasspathUtilCore.java

In some case when a provider wiring is not available there can be a NPE when setting the PDE classpath, this now checks if a provider wiring is available before access the provider.

Prevent NPE in case no provider wiring is available

---

ui/org.eclipse.pde.ui/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/PDEUIMessages.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ManifestEditor.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/targetdefinition/StatePage.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/targetdefinition/TargetEditor.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/pderesources.properties
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/views/target/StateTree.java
ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/views/target/StateViewPage.java

Currently if one loads a target not using the planner mode there is no guarantee setting it will actually lead to a satisfiable solution. And even with planner mode there are cases where P2 can get to a different result than a real OSGi resolution or there are location types that do not resolve at all. So currently one is forced to actually set the target platform, then look at the target platform state view, identify the problem, change something and start again.
This aims to add a new tab "Resolved State" that shows the resolved state of the bundles that would be set as a result of activate the current target platform.

Showing a preview of the target state in the editor

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/ClasspathUtilCore.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PDEAuxiliaryState.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bundle/BundleFragment.java
ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bundle/BundlePlugin.java

Currently we can already access some additional data for a bundle from the state but the Eclipse-PlatformFilter is not.
This now adds support to also read that information if needed.

Make Platform-Filter available in Auxiliary State

---

ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/DependencyManager.java
ui/org.eclipse.pde.launching/META-INF/MANIFEST.MF
ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/BundleLauncherHelper.java
ui/org.eclipse.pde.ui.tests/META-INF/MANIFEST.MF
ui/org.eclipse.pde.ui.tests/pom.xml
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/launcher/FeatureBasedLaunchTest.java
ui/org.eclipse.pde.ui.tests/src/org/eclipse/pde/ui/tests/launcher/PluginBasedLaunchTest.java

Currently one can only choose to include all fragments or only non-test fragments. But we can already distinguish several other types of fragments, e.g. those that belong to extensible API or provide native code specialization.
This now enhances DependencyManager to support a new type (INCLUDE_PLATFORM_FRAGMENTS) and to make configurable the inclusion of extensible API (INCLUDE_EXTENSIBLE_FRAGMENTS). Also the BundleLauncherHelper was adjusted to be more uniform when handling plugin versus feature based launches reading and preparing for further customization through launch configs.

Support more fragment options in DependencyManager / unify LaunchHelper

---

build/org.eclipse.pde.build.tests/META-INF/MANIFEST.MF
build/org.eclipse.pde.build.tests/pom.xml
build/org.eclipse.pde.build.tests/src/org/eclipse/pde/build/internal/tests/p2/PublishingTests.java

- Add bundles that are transitively required by org.eclipse.core.contenttype's new required capability.
https://github.com/eclipse-platform/eclipse.platform/pull/2162

Add more bundle to PublishingTests.testPublishAndRunSimpleProduct()

---

ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/shared/target/TargetContentsGroup.java

The result of calling `fTargetDefinition.getBundles();` was not being checked for `null` and this exception occurred.
<details><summary>NPE</summary>
<p>
```java
[ERROR] An internal error has occurred.
java.lang.NullPointerException: Cannot read the array length because "bundles" is null
at org.eclipse.pde.internal.ui.shared.target.TargetContentsGroup$TreeContentProvider.getElements(TargetContentsGroup.java:1169)
at org.eclipse.jface.viewers.StructuredViewer.getRawChildren(StructuredViewer.java:940)
at org.eclipse.jface.viewers.ColumnViewer.getRawChildren(ColumnViewer.java:701)
at org.eclipse.jface.viewers.AbstractTreeViewer.getRawChildren(AbstractTreeViewer.java:1454)
at org.eclipse.jface.viewers.TreeViewer.getRawChildren(TreeViewer.java:352)
at …
```

Fix NPE in TargetContentsGroup
